# Generated by Django 5.2.8 on 2025-11-27 07:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStaffPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, help_text='π.χ. Λογιστήριο, Γραμματεία, Τεχνικός', max_length=100, verbose_name='Θέση Εργασίας')),
                ('can_view_financials', models.BooleanField(default=True, help_text='Μπορεί να βλέπει οικονομικά στοιχεία', verbose_name='Προβολή Οικονομικών')),
                ('can_record_payments', models.BooleanField(default=False, help_text='Μπορεί να καταχωρεί πληρωμές', verbose_name='Καταχώρηση Πληρωμών')),
                ('can_create_expenses', models.BooleanField(default=False, help_text='Μπορεί να δημιουργεί δαπάνες', verbose_name='Δημιουργία Δαπανών')),
                ('can_edit_expenses', models.BooleanField(default=False, help_text='Μπορεί να επεξεργάζεται δαπάνες', verbose_name='Επεξεργασία Δαπανών')),
                ('can_create_announcements', models.BooleanField(default=False, help_text='Μπορεί να δημιουργεί ανακοινώσεις', verbose_name='Δημιουργία Ανακοινώσεων')),
                ('can_send_notifications', models.BooleanField(default=False, help_text='Μπορεί να στέλνει ειδοποιήσεις', verbose_name='Αποστολή Ειδοποιήσεων')),
                ('can_manage_requests', models.BooleanField(default=True, help_text='Μπορεί να διαχειρίζεται αιτήματα συντήρησης', verbose_name='Διαχείριση Αιτημάτων')),
                ('can_manage_maintenance', models.BooleanField(default=False, help_text='Μπορεί να διαχειρίζεται εργασίες συντήρησης', verbose_name='Διαχείριση Συντήρησης')),
                ('can_view_apartments', models.BooleanField(default=True, help_text='Μπορεί να βλέπει πληροφορίες διαμερισμάτων', verbose_name='Προβολή Διαμερισμάτων')),
                ('can_edit_apartments', models.BooleanField(default=False, help_text='Μπορεί να επεξεργάζεται πληροφορίες διαμερισμάτων', verbose_name='Επεξεργασία Διαμερισμάτων')),
                ('can_view_residents', models.BooleanField(default=True, help_text='Μπορεί να βλέπει πληροφορίες ενοίκων', verbose_name='Προβολή Ενοίκων')),
                ('can_invite_residents', models.BooleanField(default=False, help_text='Μπορεί να προσκαλεί ενοίκους στην πλατφόρμα', verbose_name='Πρόσκληση Ενοίκων')),
                ('can_upload_documents', models.BooleanField(default=False, help_text='Μπορεί να ανεβάζει έγγραφα', verbose_name='Ανέβασμα Εγγράφων')),
                ('can_delete_documents', models.BooleanField(default=False, help_text='Μπορεί να διαγράφει έγγραφα', verbose_name='Διαγραφή Εγγράφων')),
                ('is_active', models.BooleanField(default=True, help_text='Αν ο υπάλληλος είναι ενεργός', verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('user', models.OneToOneField(help_text='Ο χρήστης που ανήκουν αυτά τα permissions', on_delete=django.db.models.deletion.CASCADE, related_name='staff_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Υπάλληλος')),
            ],
            options={
                'verbose_name': 'Δικαιώματα Υπαλλήλου',
                'verbose_name_plural': 'Δικαιώματα Υπαλλήλων',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(help_text='Αποθηκεύεται ξεχωριστά για ιστορικούς λόγους', max_length=254, verbose_name='Email Χρήστη')),
                ('user_role', models.CharField(blank=True, max_length=50, verbose_name='Ρόλος Χρήστη')),
                ('action', models.CharField(choices=[('login', 'Σύνδεση'), ('logout', 'Αποσύνδεση'), ('login_failed', 'Αποτυχημένη σύνδεση'), ('payment_create', 'Δημιουργία πληρωμής'), ('payment_edit', 'Επεξεργασία πληρωμής'), ('payment_delete', 'Διαγραφή πληρωμής'), ('expense_create', 'Δημιουργία δαπάνης'), ('expense_edit', 'Επεξεργασία δαπάνης'), ('expense_delete', 'Διαγραφή δαπάνης'), ('announcement_create', 'Δημιουργία ανακοίνωσης'), ('announcement_edit', 'Επεξεργασία ανακοίνωσης'), ('announcement_delete', 'Διαγραφή ανακοίνωσης'), ('request_create', 'Δημιουργία αιτήματος'), ('request_edit', 'Επεξεργασία αιτήματος'), ('request_delete', 'Διαγραφή αιτήματος'), ('request_status', 'Αλλαγή κατάστασης αιτήματος'), ('apartment_edit', 'Επεξεργασία διαμερίσματος'), ('user_create', 'Δημιουργία χρήστη'), ('user_edit', 'Επεξεργασία χρήστη'), ('user_delete', 'Διαγραφή χρήστη'), ('user_invite', 'Πρόσκληση χρήστη'), ('staff_create', 'Δημιουργία υπαλλήλου'), ('staff_edit', 'Επεξεργασία υπαλλήλου'), ('staff_delete', 'Απενεργοποίηση υπαλλήλου'), ('staff_permissions', 'Αλλαγή δικαιωμάτων υπαλλήλου'), ('document_upload', 'Ανέβασμα εγγράφου'), ('document_delete', 'Διαγραφή εγγράφου'), ('data_export', 'Εξαγωγή δεδομένων'), ('settings_change', 'Αλλαγή ρυθμίσεων'), ('other', 'Άλλο')], max_length=50, verbose_name='Ενέργεια')),
                ('action_description', models.TextField(blank=True, verbose_name='Περιγραφή Ενέργειας')),
                ('target_model', models.CharField(blank=True, help_text='Το μοντέλο στο οποίο έγινε η ενέργεια', max_length=100, verbose_name='Μοντέλο')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Αντικειμένου')),
                ('target_description', models.CharField(blank=True, max_length=255, verbose_name='Περιγραφή Αντικειμένου')),
                ('building_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Κτιρίου')),
                ('building_name', models.CharField(blank=True, max_length=255, verbose_name='Όνομα Κτιρίου')),
                ('extra_data', models.JSONField(blank=True, default=dict, help_text='Επιπλέον δεδομένα σε μορφή JSON', verbose_name='Επιπλέον Δεδομένα')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Διεύθυνση')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('severity', models.CharField(choices=[('info', 'Πληροφορία'), ('warning', 'Προειδοποίηση'), ('error', 'Σφάλμα'), ('critical', 'Κρίσιμο')], default='info', max_length=20, verbose_name='Σοβαρότητα')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Ημερομηνία')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Καταγραφή Δραστηριότητας',
                'verbose_name_plural': 'Καταγραφές Δραστηριοτήτων',
                'ordering': ['-created_at'],
                'permissions': [('view_all_activity_logs', 'Can view all activity logs')],
                'indexes': [models.Index(fields=['user', 'created_at'], name='office_staf_user_id_916105_idx'), models.Index(fields=['action', 'created_at'], name='office_staf_action_eebd9f_idx'), models.Index(fields=['building_id', 'created_at'], name='office_staf_buildin_4c1ff0_idx'), models.Index(fields=['target_model', 'target_id'], name='office_staf_target__b97492_idx')],
            },
        ),
    ]
