# Generated by Django 5.2.8 on 2025-12-12 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_staff', '0002_add_office_finance_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officestaffpermissions',
            name='can_view_financials',
            field=models.BooleanField(default=True, help_text='Μπορεί να βλέπει οικονομικά στοιχεία κτιρίων', verbose_name='Προβολή Οικονομικών Κτιρίων'),
        ),
    ]
