# Generated by Django 5.1.9 on 2025-05-14 10:27

import django.db.models.deletion  # type: ignore  # type: ignore  # type: ignore
from django.db import migrations, models  # type: ignore  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
        ('tenants', '0002_client_domain_delete_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='building',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building'),
        ),
    ]
