# Generated by Django 5.2.x on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_migrate_domain_underscores_to_hyphens'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='account_type',
            field=models.CharField(
                choices=[('individual', 'Individual'), ('office', 'Office')],
                default='office',
                help_text='Τύπος λογαριασμού για τιμολόγηση/entitlements (individual ή office).',
                max_length=20,
            ),
        ),
    ]


