# Generated by Django 5.2.6 on 2025-09-08 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0010_apartment_previous_balance'),
        ('buildings', '0015_alter_building_grace_day_of_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('event_type', models.CharField(choices=[('call', 'Τηλεφωνική κλήση'), ('notification', 'Ομαδική ειδοποίηση'), ('payment_delay', 'Καθυστέρηση πληρωμής'), ('maintenance', 'Συντήρηση'), ('project', 'Έργο'), ('urgent', 'Επείγον'), ('meeting', 'Συνάντηση'), ('inspection', 'Επιθεώρηση'), ('reminder', 'Υπενθύμιση')], default='reminder', max_length=20, verbose_name='Τύπος συμβάντος')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μέση'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=10, verbose_name='Προτεραιότητα')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμές'), ('in_progress', 'Σε εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρωμένο'), ('postponed', 'Αναβλήθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('scheduled_date', models.DateTimeField(blank=True, null=True, verbose_name='Προγραμματισμένη ημερομηνία')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία λήξης')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ολοκληρώθηκε στις')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο επικοινωνίας')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email επικοινωνίας')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='Επαναλαμβανόμενο')),
                ('recurrence_pattern', models.CharField(blank=True, help_text="π.χ. 'weekly', 'monthly', 'yearly'", max_length=50, verbose_name='Μοτίβο επανάληψης')),
                ('apartments', models.ManyToManyField(blank=True, help_text='Αφήστε κενό για όλα τα διαμερίσματα του κτιρίου', related_name='events', to='apartments.apartment', verbose_name='Διαμερίσματα')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_events', to=settings.AUTH_USER_MODEL, verbose_name='Ανατέθηκε σε')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Συμβάν',
                'verbose_name_plural': 'Συμβάντα',
                'ordering': ['-priority', 'scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Περιεχόμενο')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('is_internal', models.BooleanField(default=False, help_text='Δεν εμφανίζεται σε ενοίκους', verbose_name='Εσωτερική σημείωση')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Συγγραφέας')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notes', to='events.event', verbose_name='Συμβάν')),
            ],
            options={
                'verbose_name': 'Σημείωση συμβάντος',
                'verbose_name_plural': 'Σημειώσεις συμβάντων',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['building', 'status'], name='events_even_buildin_1fdc89_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['scheduled_date'], name='events_even_schedul_ab5451_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'priority'], name='events_even_event_t_81ec0e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['created_by', 'assigned_to'], name='events_even_created_934093_idx'),
        ),
    ]
