# Generated by Django 5.2.6 on 2025-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='google_event_id',
            field=models.CharField(blank=True, help_text='ID του αντίστοιχου event στο Google Calendar', max_length=255, null=True, verbose_name='Google Event ID'),
        ),
        migrations.AddField(
            model_name='event',
            name='google_sync_enabled',
            field=models.BooleanField(default=True, help_text='Συγχρονισμός αυτού του event με Google Calendar', verbose_name='Συγχρονισμός με Google'),
        ),
        migrations.AddField(
            model_name='event',
            name='last_google_sync',
            field=models.DateTimeField(blank=True, help_text='Τελευταία φορά που συγχρονίστηκε με Google Calendar', null=True, verbose_name='Τελευταίος συγχρονισμός'),
        ),
    ]
