# Generated by Django 5.2.6 on 2025-09-30 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0010_apartment_previous_balance'),
        ('buildings', '0021_alter_building_reserve_fund_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Template name (e.g., 'Υπενθύμιση Οφειλών')", max_length=200)),
                ('category', models.CharField(choices=[('announcement', 'Ανακοίνωση'), ('payment', 'Πληρωμή'), ('maintenance', 'Συντήρηση'), ('meeting', 'Συνέλευση'), ('emergency', 'Έκτακτο'), ('reminder', 'Υπενθύμιση')], db_index=True, max_length=50)),
                ('description', models.TextField(blank=True, help_text='Template description for internal use')),
                ('subject', models.CharField(help_text='Email subject line with {{placeholders}}', max_length=200)),
                ('body_template', models.TextField(help_text='Email body with {{placeholders}}')),
                ('sms_template', models.TextField(blank=True, help_text='Shorter SMS version (160 chars recommended)')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system', models.BooleanField(default=False, help_text='System templates cannot be deleted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='buildings.building')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Rendered email body')),
                ('sms_body', models.TextField(blank=True, help_text='Rendered SMS body (if applicable)')),
                ('notification_type', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS')], default='email', max_length=10)),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('normal', 'Κανονική'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('scheduled', 'Προγραμματισμένο'), ('sending', 'Αποστολή'), ('sent', 'Στάλθηκε'), ('failed', 'Αποτυχία')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text='Send at specific time (null = send immediately)', null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_recipients', models.IntegerField(default=0)),
                ('successful_sends', models.IntegerField(default=0)),
                ('failed_sends', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='buildings.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_created', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, help_text='Template used (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('sending', 'Αποστέλλεται'), ('sent', 'Στάλθηκε'), ('delivered', 'Παραδόθηκε'), ('failed', 'Αποτυχία'), ('bounced', 'Επιστράφηκε')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('opened_at', models.DateTimeField(blank=True, help_text='Email open tracking', null=True)),
                ('clicked_at', models.DateTimeField(blank=True, help_text='Link click tracking', null=True)),
                ('provider_message_id', models.CharField(blank=True, help_text="External provider's message ID (for tracking)", max_length=200)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_receipts', to='apartments.apartment')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.notification')),
            ],
            options={
                'ordering': ['apartment__number'],
                'indexes': [models.Index(fields=['notification', 'status'], name='notificatio_notific_d22635_idx'), models.Index(fields=['apartment', '-created_at'], name='notificatio_apartme_a95b6f_idx')],
                'unique_together': {('notification', 'apartment')},
            },
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['building', 'category'], name='notificatio_buildin_19e023_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationtemplate',
            index=models.Index(fields=['building', 'is_active'], name='notificatio_buildin_b6d0ff_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['building', '-created_at'], name='notificatio_buildin_d7902a_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['building', 'status'], name='notificatio_buildin_1779ee_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['scheduled_at'], name='notificatio_schedul_21ac35_idx'),
        ),
    ]
