# Generated by Django 5.2.6 on 2025-10-01 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_building_reserve_fund_priority'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyNotificationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('common_expense', 'Λογαριασμός Κοινοχρήστων'), ('balance_reminder', 'Υπενθύμιση Οφειλών'), ('custom', 'Προσαρμοσμένη')], default='common_expense', max_length=50)),
                ('day_of_month', models.IntegerField(default=1, help_text='Day of month to trigger (1-31)')),
                ('time_to_send', models.TimeField(default='09:00', help_text='Time to send notification')),
                ('auto_send_enabled', models.BooleanField(default=False, help_text='If True, send automatically without confirmation')),
                ('period_month', models.DateField(help_text='Month this task is for (YYYY-MM-01)')),
                ('status', models.CharField(choices=[('pending_confirmation', 'Αναμονή Επιβεβαίωσης'), ('confirmed', 'Επιβεβαιωμένη'), ('sent', 'Απεσταλμένη'), ('skipped', 'Παραλήφθηκε'), ('auto_sent', 'Απεστάλη Αυτόματα')], db_index=True, default='pending_confirmation', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('building', models.ForeignKey(blank=True, help_text='Null = applies to all buildings', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monthly_tasks', to='buildings.building')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_task', to='notifications.notification')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate')),
            ],
            options={
                'ordering': ['-period_month', '-created_at'],
                'indexes': [models.Index(fields=['period_month', 'status'], name='notificatio_period__494607_idx'), models.Index(fields=['building', 'period_month'], name='notificatio_buildin_5707cd_idx')],
                'unique_together': {('building', 'task_type', 'period_month')},
            },
        ),
    ]
