# Generated by Django 5.2.6 on 2025-10-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_monthlynotificationtask'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional attachment (e.g., common expenses sheet PDF/JPG)', null=True, upload_to='notifications/attachments/%Y/%m/'),
        ),
    ]
