# Generated by Django 5.2.7 on 2025-10-02 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_building_reserve_fund_priority'),
        ('notifications', '0003_notification_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('announcement', 'Ανακοίνωση'), ('vote', 'Ψηφοφορία'), ('maintenance', 'Συντήρηση'), ('project', 'Έργο'), ('common_expense', 'Κοινόχρηστα'), ('urgent', 'Επείγουσα'), ('meeting', 'Συνέλευση'), ('general', 'Γενικό')], db_index=True, max_length=50)),
                ('title', models.CharField(help_text="Event title (e.g., 'Νέα Ανακοίνωση: Συντήρηση Ασανσέρ')", max_length=255)),
                ('description', models.TextField(help_text='Event description/summary')),
                ('url', models.CharField(blank=True, help_text='Link to event detail page (e.g., /announcements/123)', max_length=500)),
                ('icon', models.CharField(blank=True, help_text='Emoji or icon (e.g., 📢, 🗳️, 🔧)', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_date', models.DateTimeField(blank=True, help_text='When the actual event occurs (e.g., meeting date)', null=True)),
                ('included_in_digest', models.BooleanField(db_index=True, default=False, help_text='Has this been included in a digest email?')),
                ('digest_sent_at', models.DateTimeField(blank=True, help_text='When digest containing this event was sent', null=True)),
                ('sent_immediately', models.BooleanField(default=False, help_text='Was this sent as immediate notification (urgent events)?')),
                ('is_urgent', models.BooleanField(default=False, help_text="Send immediately, don't wait for digest")),
                ('related_announcement_id', models.IntegerField(blank=True, null=True)),
                ('related_vote_id', models.IntegerField(blank=True, null=True)),
                ('related_maintenance_id', models.IntegerField(blank=True, null=True)),
                ('related_project_id', models.IntegerField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_events', to='buildings.building')),
                ('immediate_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_events', to='notifications.notification')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['building', '-created_at'], name='notificatio_buildin_c64790_idx'), models.Index(fields=['building', 'included_in_digest'], name='notificatio_buildin_0f7efb_idx'), models.Index(fields=['event_type', '-created_at'], name='notificatio_event_t_d4510d_idx'), models.Index(fields=['is_urgent', 'sent_immediately'], name='notificatio_is_urge_0d6559_idx')],
            },
        ),
    ]
