# Generated by Django 5.2.8 on 2025-12-19 20:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0026_internal_manager_framework'),
        ('notifications', '0004_notificationevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Δευτέρα'), (1, 'Τρίτη'), (2, 'Τετάρτη'), (3, 'Πέμπτη'), (4, 'Παρασκευή'), (5, 'Σάββατο'), (6, 'Κυριακή')], help_text='Day of week for weekly/biweekly tasks (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time this recurring task was executed', null=True),
        ),
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='next_scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Next scheduled execution time', null=True),
        ),
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Μία Φορά'), ('weekly', 'Εβδομαδιαία'), ('biweekly', 'Κάθε 2 Εβδομάδες'), ('monthly', 'Μηνιαία')], default='monthly', help_text='How often to repeat: once, weekly, biweekly, monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlynotificationtask',
            name='day_of_month',
            field=models.IntegerField(blank=True, default=1, help_text='Day of month to trigger (1-31) - used for monthly tasks', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('viber', 'Viber'), ('push', 'Push Notification'), ('all', 'Όλα τα κανάλια')], default='email', max_length=10),
        ),
        migrations.CreateModel(
            name='UserViberSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viber_user_id', models.CharField(help_text='Viber user ID from webhook', max_length=100, unique=True)),
                ('viber_name', models.CharField(blank=True, help_text="User's Viber display name", max_length=200)),
                ('viber_avatar', models.URLField(blank=True, help_text="User's Viber avatar URL")),
                ('is_subscribed', models.BooleanField(default=True, help_text='User has not unsubscribed')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='viber_subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Viber Subscription',
                'verbose_name_plural': 'Viber Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(default='all', help_text="'all' or specific category like 'announcement', 'payment', etc.", max_length=50)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('viber_enabled', models.BooleanField(default=True)),
                ('push_enabled', models.BooleanField(default=True)),
                ('instant_notifications', models.BooleanField(default=True, help_text='Receive notifications immediately')),
                ('digest_only', models.BooleanField(default=False, help_text='Only receive in daily/weekly digest')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text="Don't send between this time...", null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='...and this time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notification_preferences', to='buildings.building')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'building'], name='notificatio_user_id_17bef5_idx'), models.Index(fields=['user', 'category'], name='notificatio_user_id_e0a7cc_idx')],
                'unique_together': {('user', 'building', 'category')},
            },
        ),
        migrations.CreateModel(
            name='UserDeviceToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(help_text='FCM device token', unique=True)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web Browser')], default='android', max_length=20)),
                ('device_name', models.CharField(blank=True, help_text='User-friendly device name', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Token is valid and should receive notifications')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_used_at', models.DateTimeField(blank=True, help_text='Last time this token was used to send notification', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='notificatio_user_id_c115e9_idx'), models.Index(fields=['token'], name='notificatio_token_cbe0a9_idx')],
            },
        ),
    ]
