# Generated by Django 5.2.8 on 2025-12-19 20:24
# FIXED: Removed CreateModel operations for tables that already exist

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='day_of_week',
            field=models.IntegerField(blank=True, choices=[(0, 'Δευτέρα'), (1, 'Τρίτη'), (2, 'Τετάρτη'), (3, 'Πέμπτη'), (4, 'Παρασκευή'), (5, 'Σάββατο'), (6, 'Κυριακή')], help_text='Day of week for weekly/biweekly tasks (0=Monday, 6=Sunday)', null=True),
        ),
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, help_text='Last time this recurring task was executed', null=True),
        ),
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='next_scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Next scheduled execution time', null=True),
        ),
        migrations.AddField(
            model_name='monthlynotificationtask',
            name='recurrence_type',
            field=models.CharField(choices=[('once', 'Μία Φορά'), ('weekly', 'Εβδομαδιαία'), ('biweekly', 'Κάθε 2 Εβδομάδες'), ('monthly', 'Μηνιαία')], default='monthly', help_text='How often to repeat: once, weekly, biweekly, monthly', max_length=20),
        ),
        migrations.AlterField(
            model_name='monthlynotificationtask',
            name='day_of_month',
            field=models.IntegerField(blank=True, default=1, help_text='Day of month to trigger (1-31) - used for monthly tasks', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('both', 'Email & SMS'), ('viber', 'Viber'), ('push', 'Push Notification'), ('all', 'Όλα τα κανάλια')], default='email', max_length=10),
        ),
    ]
