# Generated by Cursor on 2025-12-24
#
# Purpose:
# - This migration exists in production but was missing locally.
# - On some tenant schemas, the underlying tables already exist, causing DuplicateTable errors.
# - We use SafeCreateModel to make this migration idempotent across schemas.

from __future__ import annotations

from django.conf import settings
from django.db import migrations, models
from django.db.utils import ProgrammingError


class SafeCreateModel(migrations.CreateModel):
    """
    A CreateModel that skips DB creation if the table already exists.
    This prevents migrate_schemas from failing on tenants with partially-created tables.
    """

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        model = to_state.apps.get_model(app_label, self.name)
        table_name = model._meta.db_table

        with schema_editor.connection.cursor() as cursor:
            existing_tables = set(schema_editor.connection.introspection.table_names(cursor))

        if table_name in existing_tables:
            return

        try:
            return super().database_forwards(app_label, schema_editor, from_state, to_state)
        except ProgrammingError as exc:
            # Best-effort: if the table appeared concurrently or already existed, skip.
            if "already exists" in str(exc).lower() and table_name in str(exc):
                return
            raise


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_add_recurrence_fields"),
        ("buildings", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        SafeCreateModel(
            name="UserDeviceToken",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.TextField(help_text="FCM device token", unique=True)),
                ("platform", models.CharField(choices=[("android", "Android"), ("ios", "iOS"), ("web", "Web Browser")], default="android", max_length=20)),
                ("device_name", models.CharField(blank=True, help_text="User-friendly device name", max_length=200)),
                ("is_active", models.BooleanField(default=True, help_text="Token is valid and should receive notifications")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_used_at", models.DateTimeField(blank=True, help_text="Last time this token was used to send notification", null=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="device_tokens", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="userdevicetoken",
            index=models.Index(fields=["user", "is_active"], name="notificatio_user_id_2f8d14_idx"),
        ),
        migrations.AddIndex(
            model_name="userdevicetoken",
            index=models.Index(fields=["token"], name="notificatio_token_9f7a0a_idx"),
        ),
        SafeCreateModel(
            name="UserViberSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("viber_user_id", models.CharField(help_text="Viber user ID from webhook", max_length=100, unique=True)),
                ("viber_name", models.CharField(blank=True, help_text="User's Viber display name", max_length=200)),
                ("viber_avatar", models.URLField(blank=True, help_text="User's Viber avatar URL")),
                ("is_subscribed", models.BooleanField(default=True, help_text="User has not unsubscribed")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="viber_subscription", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Viber Subscription",
                "verbose_name_plural": "Viber Subscriptions",
            },
        ),
        SafeCreateModel(
            name="NotificationPreference",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("category", models.CharField(default="all", help_text="'all' or specific category like 'announcement', 'payment', etc.", max_length=50)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("viber_enabled", models.BooleanField(default=True)),
                ("push_enabled", models.BooleanField(default=True)),
                ("instant_notifications", models.BooleanField(default=True, help_text="Receive notifications immediately")),
                ("digest_only", models.BooleanField(default=False, help_text="Only receive in daily/weekly digest")),
                ("quiet_hours_start", models.TimeField(blank=True, help_text="Don't send between this time...", null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, help_text="...and this time", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("building", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.CASCADE, related_name="user_notification_preferences", to="buildings.building")),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="notification_preferences", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("user", "building", "category")},
            },
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user", "building"], name="notificatio_user_id_7d2f1b_idx"),
        ),
        migrations.AddIndex(
            model_name="notificationpreference",
            index=models.Index(fields=["user", "category"], name="notificatio_user_id_0a2d0c_idx"),
        ),
    ]


