# Generated by Django 5.2.7 on 2025-10-16 13:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Plan name (e.g., Starter, Professional, Enterprise)', max_length=100)),
                ('plan_type', models.CharField(choices=[('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], help_text='Unique plan identifier', max_length=20, unique=True)),
                ('description', models.TextField(help_text='Plan description and features')),
                ('monthly_price', models.DecimalField(decimal_places=2, help_text='Monthly price in EUR', max_digits=10)),
                ('yearly_price', models.DecimalField(decimal_places=2, help_text='Yearly price in EUR', max_digits=10)),
                ('max_buildings', models.PositiveIntegerField(default=1, help_text='Maximum number of buildings allowed')),
                ('max_apartments', models.PositiveIntegerField(default=10, help_text='Maximum number of apartments allowed')),
                ('max_users', models.PositiveIntegerField(default=5, help_text='Maximum number of users allowed')),
                ('max_api_calls', models.PositiveIntegerField(default=10000, help_text='Maximum API calls per month')),
                ('max_storage_gb', models.PositiveIntegerField(default=1, help_text='Maximum storage in GB')),
                ('has_analytics', models.BooleanField(default=False, help_text='Advanced analytics features')),
                ('has_custom_integrations', models.BooleanField(default=False, help_text='Custom API integrations')),
                ('has_priority_support', models.BooleanField(default=False, help_text='Priority customer support')),
                ('has_white_label', models.BooleanField(default=False, help_text='White-label solution')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this plan is available for new subscriptions')),
                ('trial_days', models.PositiveIntegerField(default=14, help_text='Free trial period in days')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'ordering': ['monthly_price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('unpaid', 'Unpaid'), ('paused', 'Paused')], default='trial', help_text='Current subscription status', max_length=20)),
                ('billing_interval', models.CharField(choices=[('month', 'Monthly'), ('year', 'Yearly')], default='month', help_text='Billing frequency', max_length=10)),
                ('trial_start', models.DateTimeField(blank=True, help_text='Trial period start date', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='Trial period end date', null=True)),
                ('current_period_start', models.DateTimeField(help_text='Current billing period start')),
                ('current_period_end', models.DateTimeField(help_text='Current billing period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='When subscription was canceled', null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, help_text='Stripe subscription ID', max_length=255)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='Stripe customer ID', max_length=255)),
                ('payment_method_id', models.CharField(blank=True, help_text='Default payment method ID', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current subscription price', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Currency code', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(help_text='Subscription plan', on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
                ('user', models.ForeignKey(help_text='User who owns this subscription', on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Subscription',
                'verbose_name_plural': 'User Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UsageTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('api_calls', 'API Calls'), ('storage_gb', 'Storage (GB)'), ('buildings', 'Buildings'), ('apartments', 'Apartments'), ('users', 'Users')], help_text='Type of usage metric', max_length=20)),
                ('usage_count', models.PositiveIntegerField(help_text='Usage count for this metric')),
                ('usage_limit', models.PositiveIntegerField(help_text='Usage limit for this metric')),
                ('period_start', models.DateTimeField(help_text='Usage tracking period start')),
                ('period_end', models.DateTimeField(help_text='Usage tracking period end')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, help_text='When this usage was recorded')),
                ('subscription', models.ForeignKey(help_text='Associated subscription', on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='billing.usersubscription')),
            ],
            options={
                'verbose_name': 'Usage Tracking',
                'verbose_name_plural': 'Usage Tracking',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Billing cycle status', max_length=20)),
                ('period_start', models.DateTimeField(help_text='Billing period start date')),
                ('period_end', models.DateTimeField(help_text='Billing period end date')),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal before tax', max_digits=10)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, help_text='Tax amount', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total amount including tax', max_digits=10)),
                ('currency', models.CharField(default='EUR', help_text='Currency code', max_length=3)),
                ('stripe_invoice_id', models.CharField(blank=True, help_text='Stripe invoice ID', max_length=255)),
                ('paid_at', models.DateTimeField(blank=True, help_text='When payment was completed', null=True)),
                ('due_date', models.DateTimeField(help_text='Payment due date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(help_text='Associated subscription', on_delete=django.db.models.deletion.CASCADE, related_name='billing_cycles', to='billing.usersubscription')),
            ],
            options={
                'verbose_name': 'Billing Cycle',
                'verbose_name_plural': 'Billing Cycles',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('card', 'Credit Card'), ('sepa', 'SEPA Direct Debit'), ('paypal', 'PayPal'), ('bank_transfer', 'Bank Transfer')], help_text='Type of payment method', max_length=20)),
                ('stripe_payment_method_id', models.CharField(blank=True, help_text='Stripe payment method ID', max_length=255)),
                ('card_brand', models.CharField(blank=True, help_text='Card brand (Visa, Mastercard, etc.)', max_length=20)),
                ('card_last4', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4)),
                ('card_exp_month', models.PositiveIntegerField(blank=True, help_text='Card expiration month', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('card_exp_year', models.PositiveIntegerField(blank=True, help_text='Card expiration year', null=True)),
                ('is_default', models.BooleanField(default=False, help_text='Default payment method for this user')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this payment method is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who owns this payment method', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-is_default', '-created_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='billing_pay_user_id_773219_idx'), models.Index(fields=['stripe_payment_method_id'], name='billing_pay_stripe__44aa09_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['user', 'status'], name='billing_use_user_id_de2ed8_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['stripe_subscription_id'], name='billing_use_stripe__7ef53e_idx'),
        ),
        migrations.AddIndex(
            model_name='usersubscription',
            index=models.Index(fields=['current_period_end'], name='billing_use_current_ad2f32_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['subscription', 'metric_type'], name='billing_usa_subscri_543457_idx'),
        ),
        migrations.AddIndex(
            model_name='usagetracking',
            index=models.Index(fields=['period_start', 'period_end'], name='billing_usa_period__a8a827_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usagetracking',
            unique_together={('subscription', 'metric_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['subscription', 'status'], name='billing_bil_subscri_07f4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['due_date'], name='billing_bil_due_dat_c72211_idx'),
        ),
        migrations.AddIndex(
            model_name='billingcycle',
            index=models.Index(fields=['stripe_invoice_id'], name='billing_bil_stripe__a42f90_idx'),
        ),
    ]
