# Generated by Django 5.2.7 on 2025-10-16 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_create_billing_models'),
    ]

    operations = [
    ]
