# Generated by Django 5.2.7 on 2025-10-16 13:16

from django.db import migrations
from decimal import Decimal


def create_default_plans(apps, schema_editor):
    """Create default subscription plans"""
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    
    # Starter Plan - Basic building management
    starter_plan, created = SubscriptionPlan.objects.get_or_create(
        plan_type='starter',
        defaults={
            'name': 'Starter Plan',
            'description': 'Perfect for small buildings with basic management needs. Includes essential features for building administration.',
            'monthly_price': Decimal('29.00'),
            'yearly_price': Decimal('290.00'),  # 2 months free
            'max_buildings': 1,
            'max_apartments': 20,
            'max_users': 10,
            'max_api_calls': 10000,
            'max_storage_gb': 1,
            'has_analytics': False,
            'has_custom_integrations': False,
            'has_priority_support': False,
            'has_white_label': False,
            'is_active': True,
            'trial_days': 14,
        }
    )
    
    # Professional Plan - Advanced features
    professional_plan, created = SubscriptionPlan.objects.get_or_create(
        plan_type='professional',
        defaults={
            'name': 'Professional Plan',
            'description': 'Advanced building management with analytics, reporting, and enhanced features for growing properties.',
            'monthly_price': Decimal('59.00'),
            'yearly_price': Decimal('590.00'),  # 2 months free
            'max_buildings': 5,
            'max_apartments': 100,
            'max_users': 25,
            'max_api_calls': 50000,
            'max_storage_gb': 10,
            'has_analytics': True,
            'has_custom_integrations': False,
            'has_priority_support': True,
            'has_white_label': False,
            'is_active': True,
            'trial_days': 14,
        }
    )
    
    # Enterprise Plan - Full features
    enterprise_plan, created = SubscriptionPlan.objects.get_or_create(
        plan_type='enterprise',
        defaults={
            'name': 'Enterprise Plan',
            'description': 'Complete solution for large property portfolios with custom integrations, white-label options, and premium support.',
            'monthly_price': Decimal('99.00'),
            'yearly_price': Decimal('990.00'),  # 2 months free
            'max_buildings': 999999,  # Unlimited (large number)
            'max_apartments': 999999,  # Unlimited (large number)
            'max_users': 999999,  # Unlimited (large number)
            'max_api_calls': 200000,
            'max_storage_gb': 100,
            'has_analytics': True,
            'has_custom_integrations': True,
            'has_priority_support': True,
            'has_white_label': True,
            'is_active': True,
            'trial_days': 30,
        }
    )
    
    print(f"✅ Created subscription plans:")
    print(f"  - {starter_plan.name}: €{starter_plan.monthly_price}/month")
    print(f"  - {professional_plan.name}: €{professional_plan.monthly_price}/month")
    print(f"  - {enterprise_plan.name}: €{enterprise_plan.monthly_price}/month")


def reverse_default_plans(apps, schema_editor):
    """Remove default subscription plans"""
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    SubscriptionPlan.objects.filter(
        plan_type__in=['starter', 'professional', 'enterprise']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_create_billing_models'),
    ]

    operations = [
        migrations.RunPython(create_default_plans, reverse_default_plans),
    ]
