# Generated by Django 5.2.7 on 2025-10-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_create_default_subscription_plans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_apartments',
            field=models.IntegerField(default=10, help_text='Maximum number of apartments allowed (-1 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_buildings',
            field=models.IntegerField(default=1, help_text='Maximum number of buildings allowed (-1 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=5, help_text='Maximum number of users allowed (-1 for unlimited)'),
        ),
    ]
