# Generated by Django 5.2.7 on 2025-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_fix_unlimited_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_monthly',
            field=models.CharField(blank=True, help_text='Stripe price ID for monthly billing', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_price_id_yearly',
            field=models.CharField(blank=True, help_text='Stripe price ID for yearly billing', max_length=100),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, help_text='Stripe product ID', max_length=100),
        ),
    ]
