# Generated by Django 5.2.7 on 2025-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_subscriptionplan_stripe_price_id_monthly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_apartments',
            field=models.IntegerField(default=10, help_text='Maximum number of apartments allowed (999999 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_buildings',
            field=models.IntegerField(default=1, help_text='Maximum number of buildings allowed (999999 for unlimited)'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='max_users',
            field=models.IntegerField(default=5, help_text='Maximum number of users allowed (999999 for unlimited)'),
        ),
    ]
