# Generated by Django 5.2.7 on 2025-10-19 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_alter_subscriptionplan_max_apartments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='tenant_domain',
            field=models.CharField(blank=True, help_text='Tenant domain for this subscription (e.g., etherm2021.localhost)', max_length=255, null=True),
        ),
    ]
