# Generated by Django 5.2.8 on 2025-12-07 04:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_add_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='includes_kiosk_hardware',
            field=models.BooleanField(default=False, help_text='If True, plan includes Kiosk hardware and installation'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='max_buildings_online_signup',
            field=models.PositiveIntegerField(default=5, help_text='Max buildings for online signup (more = "Contact Us")'),
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='uses_tiered_pricing',
            field=models.BooleanField(default=True, help_text='If True, pricing is determined by PricingTier based on apartment count'),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base monthly price (legacy - use PricingTier for tiered pricing)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='name',
            field=models.CharField(help_text='Plan name (e.g., Free, Cloud, Info Point)', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_type',
            field=models.CharField(choices=[('free', 'Free'), ('cloud', 'Cloud'), ('kiosk', 'Info Point (Kiosk)'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], help_text='Unique plan identifier', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base yearly price (legacy - use PricingTier for tiered pricing)', max_digits=10),
        ),
        migrations.CreateModel(
            name='PricingTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_category', models.CharField(choices=[('free', 'Free'), ('cloud', 'Cloud'), ('kiosk', 'Info Point (Kiosk)')], max_length=20, verbose_name='Κατηγορία Πακέτου')),
                ('min_apartments', models.PositiveIntegerField(help_text='Κάτω όριο διαμερισμάτων για αυτό το tier', verbose_name='Ελάχιστα Διαμερίσματα')),
                ('max_apartments', models.PositiveIntegerField(blank=True, help_text='Άνω όριο (null = απεριόριστα)', null=True, verbose_name='Μέγιστα Διαμερίσματα')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Μηνιαία Τιμή (€)')),
                ('yearly_price', models.DecimalField(blank=True, decimal_places=2, help_text='Αν είναι null, υπολογίζεται αυτόματα με έκπτωση', max_digits=10, null=True, verbose_name='Ετήσια Τιμή (€)')),
                ('yearly_discount_percent', models.DecimalField(decimal_places=2, default=Decimal('16.67'), help_text='Έκπτωση για ετήσια πληρωμή (default: 2 μήνες δωρεάν = 16.67%)', max_digits=5, verbose_name='Ετήσια Έκπτωση (%)')),
                ('stripe_price_id_monthly', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID (Monthly)')),
                ('stripe_price_id_yearly', models.CharField(blank=True, max_length=100, verbose_name='Stripe Price ID (Yearly)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Σειρά Εμφάνισης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Κλίμακα Τιμολόγησης',
                'verbose_name_plural': 'Κλίμακες Τιμολόγησης',
                'ordering': ['plan_category', 'min_apartments'],
                'unique_together': {('plan_category', 'min_apartments')},
            },
        ),
    ]
