# Generated by Django 5.2.x on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_add_pricing_tier_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_item_id_web',
            field=models.CharField(
                blank=True,
                help_text='Stripe subscription item ID for Web per-apartment line item',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_item_id_premium',
            field=models.CharField(
                blank=True,
                help_text='Stripe subscription item ID for Premium add-on per-apartment line item',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_total_apartments',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Last synced total apartments (sum of Building.apartments_count across tenant)',
            ),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_premium_apartments',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Last synced premium apartments (sum of Building.apartments_count where premium_enabled=true)',
            ),
        ),
    ]


