# Generated by Django 5.2.x on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_add_subscription_item_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_subscription_item_id_iot',
            field=models.CharField(
                blank=True,
                help_text='Stripe subscription item ID for IoT add-on per-apartment line item',
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_iot_apartments',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Last synced IoT apartments (sum of Building.apartments_count where iot_enabled=true)',
            ),
        ),
    ]

