# Generated by Django 5.2.x on 2026-01-04

from decimal import Decimal
from django.db import migrations


def create_web_premium_plans(apps, schema_editor):
    SubscriptionPlan = apps.get_model('billing', 'SubscriptionPlan')
    PricingTier = apps.get_model('billing', 'PricingTier')

    plans_data = [
        {
            'plan_type': 'free',
            'name': 'Free',
            'description': 'Βασικό φύλλο κοινοχρήστων για μικρές πολυκατοικίες (έως 7 διαμερίσματα)',
            'monthly_price': Decimal('0.00'),
            'yearly_price': Decimal('0.00'),
            'uses_tiered_pricing': True,
            'includes_kiosk_hardware': False,
            'max_buildings_online_signup': 1,
            'is_active': True,
        },
        {
            'plan_type': 'web',
            'name': 'Concierge Web',
            'description': 'Πλήρης πλατφόρμα διαχείρισης χωρίς οθόνη εισόδου (χρέωση ανά διαμέρισμα)',
            'monthly_price': Decimal('1.00'),
            'yearly_price': Decimal('10.00'),
            'uses_tiered_pricing': True,
            'includes_kiosk_hardware': False,
            'max_buildings_online_signup': 5,
            'is_active': True,
        },
        {
            'plan_type': 'premium',
            'name': 'Concierge Premium',
            'description': 'Kiosk + AI + Αρχείο (χρέωση ανά διαμέρισμα)',
            'monthly_price': Decimal('1.80'),
            'yearly_price': Decimal('18.00'),
            'uses_tiered_pricing': True,
            'includes_kiosk_hardware': True,
            'max_buildings_online_signup': 5,
            'is_active': True,
        },
        {
            'plan_type': 'premium_iot',
            'name': 'Concierge Premium + IoT',
            'description': 'Premium + Smart Heating (χρέωση ανά διαμέρισμα)',
            'monthly_price': Decimal('2.30'),
            'yearly_price': Decimal('23.00'),
            'uses_tiered_pricing': True,
            'includes_kiosk_hardware': True,
            'max_buildings_online_signup': 5,
            'is_active': True,
        },
    ]

    for plan in plans_data:
        SubscriptionPlan.objects.update_or_create(
            plan_type=plan['plan_type'],
            defaults=plan,
        )

    tiers_data = [
        {
            'plan_category': 'free',
            'min_apartments': 1,
            'max_apartments': 7,
            'monthly_price': Decimal('0.00'),
            'yearly_discount_percent': Decimal('0.00'),
            'display_order': 1,
            'is_active': True,
        },
        {
            'plan_category': 'web',
            'min_apartments': 1,
            'max_apartments': None,
            'monthly_price': Decimal('1.00'),
            'yearly_discount_percent': Decimal('16.67'),
            'display_order': 10,
            'is_active': True,
        },
        {
            'plan_category': 'premium',
            'min_apartments': 1,
            'max_apartments': None,
            'monthly_price': Decimal('1.80'),
            'yearly_discount_percent': Decimal('16.67'),
            'display_order': 20,
            'is_active': True,
        },
        {
            'plan_category': 'premium_iot',
            'min_apartments': 1,
            'max_apartments': None,
            'monthly_price': Decimal('2.30'),
            'yearly_discount_percent': Decimal('16.67'),
            'display_order': 30,
            'is_active': True,
        },
    ]

    for tier in tiers_data:
        PricingTier.objects.update_or_create(
            plan_category=tier['plan_category'],
            min_apartments=tier['min_apartments'],
            defaults=tier,
        )


def noop_reverse(apps, schema_editor):
    # No destructive rollback; keep records if migration is reversed.
    return


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_add_iot_subscription_item_fields'),
    ]

    operations = [
        migrations.RunPython(create_web_premium_plans, noop_reverse),
    ]

