web: gunicorn new_concierge_backend.wsgi:application --bind 0.0.0.0:$PORT --workers 2
release: python manage.py migrate_schemas --shared && python manage.py migrate_schemas --tenant && python manage.py collectstatic --noinput
