# Generated by Django 5.2.4 on 2025-08-02 17:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_building_management_office_address_and_more'),
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Έργου')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('project_type', models.CharField(choices=[('maintenance', 'Συντήρηση'), ('renovation', 'Ανακαίνιση'), ('construction', 'Κατασκευή'), ('installation', 'Εγκατάσταση'), ('repair', 'Επισκευή'), ('upgrade', 'Αναβάθμιση'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Έργου')),
                ('status', models.CharField(choices=[('planning', 'Σχεδιασμός'), ('bidding', 'Διαγωνισμός'), ('awarded', 'Ανατεθειμένο'), ('in_progress', 'Σε Εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρώθηκε')], default='planning', max_length=20, verbose_name='Κατάσταση')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Προϋπολογισμός')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Πραγματικό Κόστος')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('estimated_duration', models.IntegerField(blank=True, help_text='Διάρκεια σε ημέρες', null=True, verbose_name='Εκτιμώμενη Διάρκεια')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Τοποθεσία')),
                ('specifications', models.TextField(blank=True, verbose_name='Προδιαγραφές')),
                ('requirements', models.TextField(blank=True, verbose_name='Απαιτήσεις')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Έργο',
                'verbose_name_plural': 'Έργα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό Προσφοράς')),
                ('description', models.TextField(verbose_name='Περιγραφή Προσφοράς')),
                ('technical_specifications', models.TextField(blank=True, verbose_name='Τεχνικές Προδιαγραφές')),
                ('delivery_time', models.IntegerField(help_text='Χρόνος παράδοσης σε ημέρες', verbose_name='Χρόνος Παράδοσης')),
                ('warranty_period', models.IntegerField(help_text='Περίοδος εγγύησης σε μήνες', verbose_name='Περίοδος Εγγύησης')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('under_review', 'Υπό Αξιολόγηση'), ('accepted', 'Αποδεκτή'), ('rejected', 'Απορριφθείσα'), ('withdrawn', 'Αποσυρθείσα')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('submitted_date', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Υποβολής')),
                ('evaluation_date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αξιολόγησης')),
                ('evaluation_notes', models.TextField(blank=True, verbose_name='Σημειώσεις Αξιολόγησης')),
                ('evaluation_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Βαθμολογία Αξιολόγησης')),
                ('offer_file', models.FileField(blank=True, upload_to='offers/%Y/%m/', verbose_name='Αρχείο Προσφοράς')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='maintenance.contractor', verbose_name='Συνεργείο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Προσφορά',
                'verbose_name_plural': 'Προσφορές',
                'ordering': ['-submitted_date'],
                'unique_together': {('project', 'contractor')},
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('service', 'Υπηρεσίες'), ('construction', 'Κατασκευή'), ('maintenance', 'Συντήρηση'), ('consulting', 'Σύμβουλος'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Συμβολαίου')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Συμβολαίου')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Συμβολαίου')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό Συμβολαίου')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('active', 'Ενεργό'), ('completed', 'Ολοκληρωμένο'), ('terminated', 'Λυμένο'), ('expired', 'Ληγμένο')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('payment_terms', models.TextField(blank=True, verbose_name='Όροι Πληρωμής')),
                ('warranty_terms', models.TextField(blank=True, verbose_name='Όροι Εγγύησης')),
                ('contract_file', models.FileField(blank=True, upload_to='contracts/%Y/%m/', verbose_name='Αρχείο Συμβολαίου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='maintenance.contractor', verbose_name='Συνεργείο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='projects.offer', verbose_name='Προσφορά')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Συμβόλαιο',
                'verbose_name_plural': 'Συμβόλαια',
                'ordering': ['-created_at'],
            },
        ),
    ]
