# Generated by Django 5.2.6 on 2025-09-19 23:40

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0019_add_reserve_fund_priority'),
        ('financial', '0040_add_hybrid_balance_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contractor_name', models.CharField(default='', max_length=200, verbose_name='Όνομα Συνεργείου')),
                ('contractor_contact', models.CharField(blank=True, max_length=200, null=True, verbose_name='Στοιχεία Επικοινωνίας')),
                ('contractor_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο')),
                ('contractor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('contractor_address', models.TextField(blank=True, null=True, verbose_name='Διεύθυνση')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ποσό Προσφοράς')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Περιγραφή Προσφοράς')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name='Όροι Πληρωμής')),
                ('warranty_period', models.CharField(blank=True, max_length=100, null=True, verbose_name='Περίοδος Εγγύησης')),
                ('completion_time', models.CharField(blank=True, max_length=100, null=True, verbose_name='Χρόνος Ολοκλήρωσης')),
                ('status', models.CharField(choices=[('submitted', 'Υποβλήθηκε'), ('under_review', 'Υπό Αξιολόγηση'), ('accepted', 'Εγκεκριμένη'), ('rejected', 'Απορρίφθηκε'), ('withdrawn', 'Ανακλήθηκε')], default='submitted', max_length=20, verbose_name='Κατάσταση')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Υποβολής')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αξιολόγησης')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Αξιολογήθηκε από')),
            ],
            options={
                'verbose_name': 'Προσφορά',
                'verbose_name_plural': 'Προσφορές',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='offers/%Y/%m/%d/', verbose_name='Αρχείο')),
                ('filename', models.CharField(max_length=255, verbose_name='Όνομα Αρχείου')),
                ('file_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Τύπος Αρχείου')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγεθος Αρχείου')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Ανεβάσματος')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='projects.offer', verbose_name='Προσφορά')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Ανεβάστηκε από')),
            ],
            options={
                'verbose_name': 'Αρχείο Προσφοράς',
                'verbose_name_plural': 'Αρχεία Προσφορών',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος Έργου')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Εκτιμώμενο Κόστος')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μεσαία'), ('high', 'Υψηλή'), ('urgent', 'Επείγον')], default='medium', max_length=10, verbose_name='Προτεραιότητα')),
                ('status', models.CharField(choices=[('planning', 'Σχεδιασμός'), ('tendering', 'Διαγωνισμός'), ('evaluation', 'Αξιολόγηση'), ('approved', 'Εγκεκριμένο'), ('in_progress', 'Σε Εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρωμένο')], default='planning', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ημερομηνία Ενημέρωσης')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Προθεσμία')),
                ('tender_deadline', models.DateField(blank=True, null=True, verbose_name='Προθεσμία Υποβολής Προσφορών')),
                ('general_assembly_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Γενικής Συνελεύσης')),
                ('selected_contractor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Επιλεγμένος Αναδόχος')),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Τελικό Κόστος')),
                ('payment_terms', models.TextField(blank=True, null=True, verbose_name='Όροι Πληρωμής')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('linked_expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='financial.expense', verbose_name='Συνδεδεμένη Δαπάνη')),
            ],
            options={
                'verbose_name': 'Έργο',
                'verbose_name_plural': 'Έργα',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='projects.project', verbose_name='Έργο'),
        ),
        migrations.CreateModel(
            name='ProjectExpense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200, verbose_name='Περιγραφή')),
                ('expense_type', models.CharField(choices=[('material', 'Υλικά'), ('labor', 'Εργασία'), ('equipment', 'Εξοπλισμός'), ('permit', 'Άδεια'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Δαπάνης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Ποσό')),
                ('expense_date', models.DateField(verbose_name='Ημερομηνία Δαπάνης')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Δαπάνη Έργου',
                'verbose_name_plural': 'Δαπάνες Έργων',
                'ordering': ['-expense_date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote_type', models.CharField(choices=[('approve', 'Έγκριση'), ('reject', 'Απόρριψη'), ('abstain', 'Αποχή')], max_length=10, verbose_name='Τύπος Ψήφου')),
                ('voter_name', models.CharField(max_length=200, verbose_name='Όνομα Ψηφοφόρου')),
                ('apartment', models.CharField(max_length=20, verbose_name='Διαμέρισμα')),
                ('participation_mills', models.PositiveIntegerField(verbose_name='Μοίρες Συμμετοχής')),
                ('voted_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Ψηφοφορίας')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Σημειώσεις')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.offer', verbose_name='Προσφορά')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Ψηφοφορία Έργου',
                'verbose_name_plural': 'Ψηφοφορίες Έργων',
                'ordering': ['-voted_at'],
                'unique_together': {('project', 'apartment')},
            },
        ),
    ]
