# Generated by Django 5.2.6 on 2025-09-20 15:58

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Προκαταβολή'),
        ),
        migrations.AddField(
            model_name='offer',
            name='installments',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Αριθμός Δόσεων'),
        ),
        migrations.AddField(
            model_name='offer',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AddField(
            model_name='project',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Προκαταβολή'),
        ),
        migrations.AddField(
            model_name='project',
            name='installments',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Αριθμός Δόσεων'),
        ),
        migrations.AddField(
            model_name='project',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
