# Generated by Django 5.2.6 on 2025-09-04 08:37

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_contractor_availability_contractor_emergency_contact_and_more'),
        ('projects', '0002_alter_contract_payment_terms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='advance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Προκαταβολή'),
        ),
        migrations.AddField(
            model_name='contract',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, verbose_name='Παραδοτέα'),
        ),
        migrations.AddField(
            model_name='contract',
            name='guarantee_terms',
            field=models.TextField(blank=True, verbose_name='Όροι Εγγύησης'),
        ),
        migrations.AddField(
            model_name='contract',
            name='po_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Παραγγελίας (PO)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='retention_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ποσοστό Παρακράτησης %'),
        ),
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.CharField(default='EUR', max_length=3, verbose_name='Νόμισμα'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_awarded',
            field=models.BooleanField(default=False, verbose_name='Έχει Ανατεθεί'),
        ),
        migrations.AddField(
            model_name='offer',
            name='scoring_breakdown',
            field=models.JSONField(blank=True, default=dict, verbose_name='Ανάλυση Βαθμολόγησης'),
        ),
        migrations.AddField(
            model_name='offer',
            name='tax_included',
            field=models.BooleanField(default=True, verbose_name='Περιλαμβάνει ΦΠΑ'),
        ),
        migrations.AddField(
            model_name='offer',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Ισχύει έως'),
        ),
        migrations.AddField(
            model_name='project',
            name='decision_mode',
            field=models.CharField(choices=[('kiosk', 'Kiosk'), ('board', 'Διοικητικό'), ('direct', 'Απευθείας')], default='board', max_length=10, verbose_name='Τύπος Απόφασης'),
        ),
        migrations.AddField(
            model_name='project',
            name='direct_assignment_reason',
            field=models.TextField(blank=True, verbose_name='Αιτιολόγηση Απευθείας Ανάθεσης'),
        ),
        migrations.AddField(
            model_name='project',
            name='policy_threshold_exceeded',
            field=models.BooleanField(default=False, verbose_name='Υπέρβαση Ορίου Πολιτικής'),
        ),
        migrations.AddField(
            model_name='project',
            name='visibility',
            field=models.CharField(choices=[('internal', 'Εσωτερικό'), ('public', 'Δημόσιο')], default='internal', max_length=10, verbose_name='Ορατότητα'),
        ),
        migrations.CreateModel(
            name='Decision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('kiosk', 'Kiosk'), ('board', 'Διοικητικό')], max_length=10, verbose_name='Λειτουργία')),
                ('result', models.CharField(choices=[('approved', 'Εγκρίθηκε'), ('rejected', 'Απορρίφθηκε'), ('postponed', 'Αναβλήθηκε')], max_length=10, verbose_name='Αποτέλεσμα')),
                ('quorum', models.PositiveIntegerField(blank=True, null=True, verbose_name='Απαρτία')),
                ('threshold', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Όριο %')),
                ('minutes_text', models.TextField(blank=True, verbose_name='Πρακτικά (κείμενο)')),
                ('minutes_file', models.FileField(blank=True, null=True, upload_to='decisions/%Y/%m/', verbose_name='Πρακτικά (αρχείο)')),
                ('occurred_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Απόφασης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_decisions', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Απόφαση',
                'verbose_name_plural': 'Αποφάσεις',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcurementEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('open', 'Ανοικτή'), ('invite', 'Με Πρόσκληση')], default='open', max_length=10, verbose_name='Στρατηγική')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Έναρξη Υποβολής')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Λήξη Υποβολής')),
                ('documents', models.JSONField(blank=True, default=list, verbose_name='Έγγραφα/Αρχεία')),
                ('criteria', models.JSONField(blank=True, default=dict, verbose_name='Κριτήρια Αξιολόγησης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invited_vendors', models.ManyToManyField(blank=True, related_name='procurement_events', to='maintenance.contractor', verbose_name='Προσκεκλημένοι Ανάδοχοι')),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='procurement', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Γεγονός Προμήθειας',
                'verbose_name_plural': 'Γεγονότα Προμήθειας',
            },
        ),
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Προθεσμία')),
                ('status', models.CharField(choices=[('todo', 'Προς Υλοποίηση'), ('in_progress', 'Σε Εξέλιξη'), ('done', 'Ολοκληρωμένο')], default='todo', max_length=20, verbose_name='Κατάσταση')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='Πρόοδος %')),
                ('evidence_files', models.JSONField(blank=True, default=list, verbose_name='Αποδεικτικά Αρχεία')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee_contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to='maintenance.contractor', verbose_name='Ανάδοχος')),
                ('assignee_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_project_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ανατεθειμένος Χρήστης')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Εργασία Έργου',
                'verbose_name_plural': 'Εργασίες Έργου',
                'ordering': ['-created_at'],
            },
        ),
    ]
