# Generated by Django 5.2.7 on 2025-10-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_offer_advance_payment_offer_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assembly_is_online',
            field=models.BooleanField(default=False, verbose_name='Διαδικτυακή Συνέλευση'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_location',
            field=models.CharField(blank=True, help_text='π.χ. Pilotis, Διαμέρισμα Α2', max_length=200, null=True, verbose_name='Τοποθεσία Συνέλευσης'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ώρα Γενικής Συνέλευσης'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Σύνδεσμος Zoom'),
        ),
    ]
