# Generated by Django 5.2.6 on 2025-09-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_contract_advance_amount_contract_deliverables_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procurementevent',
            name='invited_vendors',
        ),
        migrations.RemoveField(
            model_name='procurementevent',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='assignee_contractor',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='assignee_user',
        ),
        migrations.RemoveField(
            model_name='projecttask',
            name='project',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='deliverables',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='guarantee_terms',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='retention_percent',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_awarded',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='scoring_breakdown',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='tax_included',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='valid_until',
        ),
        migrations.RemoveField(
            model_name='project',
            name='decision_mode',
        ),
        migrations.RemoveField(
            model_name='project',
            name='direct_assignment_reason',
        ),
        migrations.RemoveField(
            model_name='project',
            name='policy_threshold_exceeded',
        ),
        migrations.RemoveField(
            model_name='project',
            name='visibility',
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('due_at', models.DateTimeField(blank=True, null=True, verbose_name='Προθεσμία')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Ποσό')),
                ('status', models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('in_progress', 'Σε εξέλιξη'), ('awaiting_approval', 'Προς έγκριση'), ('approved', 'Εγκρίθηκε'), ('overdue', 'Ληξιπρόθεσμο')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Έγκρισης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_milestones', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'Ορόσημο',
                'verbose_name_plural': 'Ορόσημα',
                'ordering': ['due_at'],
            },
        ),
        migrations.DeleteModel(
            name='Decision',
        ),
        migrations.DeleteModel(
            name='ProcurementEvent',
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='projects_mi_project_dc545b_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'due_at'], name='projects_mi_project_06d14d_idx'),
        ),
    ]
