# Generated by Django 5.2.7 on 2025-10-06 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_assembly_is_online_project_assembly_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assembly_is_physical',
            field=models.BooleanField(default=False, verbose_name='Φυσική Παρουσία'),
        ),
    ]
