# Generated by Django 5.2.6 on 2025-09-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_procurementevent_invited_vendors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/', verbose_name='Συνημμένο'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_file',
            field=models.FileField(blank=True, null=True, upload_to='offers/%Y/%m/', verbose_name='Αρχείο Προσφοράς'),
        ),
    ]
