# Generated by Django 5.2.7 on 2025-10-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_add_assembly_is_physical'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_auto_record',
            field=models.BooleanField(default=False, verbose_name='Αυτόματη Εγγραφή'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_host_video',
            field=models.BooleanField(default=True, verbose_name='Βίντεο Οργανωτή'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_meeting_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Meeting ID'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_mute_on_entry',
            field=models.BooleanField(default=True, verbose_name='Σίγαση κατά Είσοδο'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Σημειώσεις Zoom'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_participant_video',
            field=models.BooleanField(default=False, verbose_name='Βίντεο Συμμετεχόντων'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_password',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Κωδικός Zoom'),
        ),
        migrations.AddField(
            model_name='project',
            name='assembly_zoom_waiting_room',
            field=models.BooleanField(default=True, verbose_name='Αίθουσα Αναμονής'),
        ),
    ]
