# Generated by Django 5.2.6 on 2025-09-05 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_project_attachment_alter_offer_offer_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος RFQ')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Προθεσμία Υποβολής')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('sent', 'Στάλθηκε'), ('received', 'Ελήφθησαν'), ('closed', 'Κλειστό')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_rfqs', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='projects.project', verbose_name='Έργο')),
            ],
            options={
                'verbose_name': 'RFQ',
                'verbose_name_plural': 'RFQs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='rfq',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='projects.rfq', verbose_name='RFQ'),
        ),
    ]
