# Generated by Django 5.2.7 on 2025-10-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_add_zoom_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectvote',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_votes', to='projects.offer', verbose_name='Προσφορά'),
        ),
        migrations.AlterField(
            model_name='projectvote',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_votes', to='projects.project', verbose_name='Έργο'),
        ),
    ]
