# Generated by Django 5.2.8 on 2025-11-20 03:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_projectvote_offer_alter_projectvote_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='installments',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(60, message='Ο μέγιστος αριθμός δόσεων είναι 60 (5 χρόνια)')], verbose_name='Αριθμός Δόσεων'),
        ),
        migrations.AlterField(
            model_name='project',
            name='installments',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(60, message='Ο μέγιστος αριθμός δόσεων είναι 60 (5 χρόνια)')], verbose_name='Αριθμός Δόσεων'),
        ),
    ]
