# Generated by Django 5.2.8 on 2025-12-09 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0002_add_email_tracking_fields'),
        ('projects', '0007_alter_offer_installments_alter_project_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='linked_assembly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_projects', to='assemblies.assembly', verbose_name='Συνδεδεμένη Συνέλευση'),
        ),
    ]
