# Generated by Django 5.2.8 on 2025-12-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0008_add_linked_assembly"),
    ]

    operations = [
        migrations.AddField(
            model_name="offer",
            name="marketplace_provider_id",
            field=models.UUIDField(
                blank=True,
                db_index=True,
                help_text="UUID του Marketplace provider (public schema) αν η προσφορά προήλθε από το marketplace.",
                null=True,
                verbose_name="Marketplace Provider ID",
            ),
        ),
    ]


