# Generated by Django 5.2.4 on 2025-08-01 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0005_building_management_office_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Όνομα του chat room (συνήθως το όνομα του κτιρίου)', max_length=255, verbose_name='Όνομα Chat Room')),
                ('is_active', models.BooleanField(default=True, help_text='Αν το chat room είναι ενεργό', verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_room', to='buildings.building', verbose_name='Κτίριο')),
            ],
            options={
                'verbose_name': 'Chat Room',
                'verbose_name_plural': 'Chat Rooms',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Κείμενο'), ('image', 'Εικόνα'), ('file', 'Αρχείο'), ('system', 'Σύστημα')], default='text', max_length=10, verbose_name='Τύπος Μηνύματος')),
                ('content', models.TextField(help_text='Το περιεχόμενο του μηνύματος', verbose_name='Περιεχόμενο')),
                ('file_url', models.URLField(blank=True, help_text='URL για εικόνες ή αρχεία', null=True, verbose_name='URL Αρχείου')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Όνομα Αρχείου')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Μέγεθος Αρχείου (bytes)')),
                ('is_edited', models.BooleanField(default=False, help_text='Αν το μήνυμα έχει επεξεργαστεί', verbose_name='Επεξεργασμένο')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Επεξεργασίας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to=settings.AUTH_USER_MODEL, verbose_name='Αποστολέας')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatroom', verbose_name='Chat Room')),
            ],
            options={
                'verbose_name': 'Chat Message',
                'verbose_name_plural': 'Chat Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Συνδεδεμένος')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Εμφάνιση')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.chatroom', verbose_name='Chat Room')),
            ],
            options={
                'verbose_name': 'Chat Participant',
                'verbose_name_plural': 'Chat Participants',
                'unique_together': {('chat_room', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ChatNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unread_count', models.PositiveIntegerField(default=0, verbose_name='Αριθμός Μη Διαβασμένων')),
                ('last_read_at', models.DateTimeField(auto_now_add=True, verbose_name='Τελευταία Ανάγνωση')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
                ('chat_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='chat.chatroom', verbose_name='Chat Room')),
            ],
            options={
                'verbose_name': 'Chat Notification',
                'verbose_name_plural': 'Chat Notifications',
                'unique_together': {('user', 'chat_room')},
            },
        ),
    ]
