# Generated by Django 5.2.8 on 2025-12-03 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0026_internal_manager_framework'),
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(help_text='Κτίριο στο οποίο ξεκίνησε η συνομιλία (για context)', on_delete=django.db.models.deletion.CASCADE, related_name='direct_conversations', to='buildings.building', verbose_name='Κτίριο')),
                ('participant_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_one', to=settings.AUTH_USER_MODEL, verbose_name='Συμμετέχων 1')),
                ('participant_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations_as_two', to=settings.AUTH_USER_MODEL, verbose_name='Συμμετέχων 2')),
            ],
            options={
                'verbose_name': 'Direct Conversation',
                'verbose_name_plural': 'Direct Conversations',
                'ordering': ['-updated_at'],
                'unique_together': {('participant_one', 'participant_two', 'building')},
            },
        ),
        migrations.CreateModel(
            name='DirectMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('text', 'Κείμενο'), ('image', 'Εικόνα'), ('file', 'Αρχείο')], default='text', max_length=10, verbose_name='Τύπος Μηνύματος')),
                ('content', models.TextField(verbose_name='Περιεχόμενο')),
                ('file_url', models.URLField(blank=True, null=True, verbose_name='URL Αρχείου')),
                ('file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Όνομα Αρχείου')),
                ('is_read', models.BooleanField(default=False, verbose_name='Διαβάστηκε')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ανάγνωσης')),
                ('is_edited', models.BooleanField(default=False, verbose_name='Επεξεργασμένο')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.directconversation', verbose_name='Συνομιλία')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_direct_messages', to=settings.AUTH_USER_MODEL, verbose_name='Αποστολέας')),
            ],
            options={
                'verbose_name': 'Direct Message',
                'verbose_name_plural': 'Direct Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnlineStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_online', models.BooleanField(default=False, verbose_name='Συνδεδεμένος')),
                ('last_activity', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Δραστηριότητα')),
                ('status_message', models.CharField(blank=True, help_text="Π.χ. 'Διαθέσιμος', 'Απασχολημένος', κλπ.", max_length=100, null=True, verbose_name='Μήνυμα Κατάστασης')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='online_status', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Online Status',
                'verbose_name_plural': 'Online Statuses',
            },
        ),
    ]
