# Generated by Django 5.2.8 on 2025-12-17 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_add_reactions_reply_delete'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatNotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_notifications', models.CharField(choices=[('all', 'Όλα τα μηνύματα'), ('mentions', 'Μόνο αναφορές'), ('dm_only', 'Μόνο ιδιωτικά μηνύματα'), ('none', 'Καμία ειδοποίηση')], default='all', help_text='Πότε να λαμβάνετε ειδοποιήσεις για μηνύματα', max_length=20, verbose_name='Ειδοποιήσεις Chat')),
                ('dm_notifications', models.BooleanField(default=True, help_text='Λήψη ειδοποιήσεων για ιδιωτικά μηνύματα', verbose_name='Ειδοποιήσεις Ιδιωτικών')),
                ('sound_enabled', models.BooleanField(default=True, help_text='Αναπαραγωγή ήχου για νέα μηνύματα', verbose_name='Ήχος')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Από ποια ώρα να μην στέλνονται ειδοποιήσεις', null=True, verbose_name='Ώρα Έναρξης Ησυχίας')),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='Μέχρι ποια ώρα να μην στέλνονται ειδοποιήσεις', null=True, verbose_name='Ώρα Λήξης Ησυχίας')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chat_notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Chat Notification Preference',
                'verbose_name_plural': 'Chat Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.TextField(help_text='Push service endpoint URL', verbose_name='Endpoint URL')),
                ('p256dh', models.CharField(help_text='Client public key for encryption', max_length=255, verbose_name='P256DH Key')),
                ('auth', models.CharField(help_text='Authentication secret', max_length=255, verbose_name='Auth Secret')),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=500, null=True, verbose_name='User Agent')),
                ('is_active', models.BooleanField(default=True, help_text='Αν το subscription είναι ακόμα ενεργό', verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Push Subscription',
                'verbose_name_plural': 'Push Subscriptions',
                'unique_together': {('user', 'endpoint')},
            },
        ),
    ]
