# Generated by Django 5.2.5 on 2025-09-03 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_apartment_previous_balance'),
        ('buildings', '0015_alter_building_grace_day_of_month'),
        ('todo_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('due_soon', 'Λήγει Σύντομα'), ('overdue', 'Λήξει'), ('completed', 'Ολοκληρώθηκε'), ('assigned', 'Ανατέθηκε'), ('reminder', 'Υπενθύμιση')], max_length=20, verbose_name='Τύπος Ειδοποίησης')),
                ('message', models.TextField(blank=True, verbose_name='Μήνυμα')),
                ('is_read', models.BooleanField(default=False, verbose_name='Διαβασμένη')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Διαβάστηκε')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
            ],
            options={
                'verbose_name': 'Ειδοποίηση TODO',
                'verbose_name_plural': 'Ειδοποιήσεις TODO',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TodoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('frequency', models.CharField(choices=[('daily', 'Καθημερινά'), ('weekly', 'Εβδομαδιαία'), ('monthly', 'Μηνιαία'), ('quarterly', 'Τριμηνιαία'), ('yearly', 'Ετήσια'), ('custom', 'Προσαρμοσμένη')], default='monthly', max_length=20, verbose_name='Συχνότητα')),
                ('custom_days', models.IntegerField(blank=True, null=True, verbose_name='Προσαρμοσμένες Ημέρες')),
                ('auto_create', models.BooleanField(default=False, verbose_name='Αυτόματη Δημιουργία')),
                ('last_created', models.DateTimeField(blank=True, null=True, verbose_name='Τελευταία Δημιουργία')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μεσαία'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=20, verbose_name='Προτεραιότητα')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Εκτιμώμενες Ώρες')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Δημιουργήθηκε')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε')),
            ],
            options={
                'verbose_name': 'Πρότυπο TODO',
                'verbose_name_plural': 'Πρότυπα TODO',
                'ordering': ['frequency', 'title'],
            },
        ),
        migrations.AlterModelOptions(
            name='todocategory',
            options={'ordering': ['name'], 'verbose_name': 'Κατηγορία TODO', 'verbose_name_plural': 'Κατηγορίες TODO'},
        ),
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['-priority', 'due_date', '-created_at'], 'verbose_name': 'TODO Item', 'verbose_name_plural': 'TODO Items'},
        ),
        migrations.AddField(
            model_name='todocategory',
            name='color',
            field=models.CharField(choices=[('blue', 'Μπλε'), ('green', 'Πράσινο'), ('yellow', 'Κίτρινο'), ('orange', 'Πορτοκαλί'), ('red', 'Κόκκινο'), ('purple', 'Μωβ'), ('gray', 'Γκρι')], default='blue', max_length=20, verbose_name='Χρώμα'),
        ),
        migrations.AddField(
            model_name='todocategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='todocategory',
            name='icon',
            field=models.CharField(default='check-square', max_length=50, verbose_name='Εικονίδιο'),
        ),
        migrations.AddField(
            model_name='todocategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό'),
        ),
        migrations.AddField(
            model_name='todocategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='actual_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Πραγματικές Ώρες'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='todos', to='apartments.apartment'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='attachments',
            field=models.JSONField(blank=True, default=list, verbose_name='Συνημμένα'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ολοκληρώθηκε'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='estimated_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Εκτιμώμενες Ώρες'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μεσαία'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=20, verbose_name='Προτεραιότητα'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Ετικέτες'),
        ),
        migrations.AddField(
            model_name='todoitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Ενημερώθηκε'),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='status',
            field=models.CharField(choices=[('pending', 'Εκκρεμεί'), ('in_progress', 'Σε Εξέλιξη'), ('completed', 'Ολοκληρώθηκε'), ('cancelled', 'Ακυρώθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterUniqueTogether(
            name='todocategory',
            unique_together={('name', 'building')},
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['building', 'status'], name='todo_manage_buildin_d8edc9_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['building', 'due_date'], name='todo_manage_buildin_dfac5c_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['assigned_to', 'status'], name='todo_manage_assigne_61328a_idx'),
        ),
        migrations.AddIndex(
            model_name='todoitem',
            index=models.Index(fields=['category', 'status'], name='todo_manage_categor_737e80_idx'),
        ),
        migrations.AddField(
            model_name='todonotification',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='todo_management.todoitem'),
        ),
        migrations.AddField(
            model_name='todonotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='todotemplate',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_templates', to='buildings.building'),
        ),
        migrations.AddField(
            model_name='todotemplate',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='todo_management.todocategory'),
        ),
        migrations.AddIndex(
            model_name='todonotification',
            index=models.Index(fields=['user', 'is_read'], name='todo_manage_user_id_da2567_idx'),
        ),
        migrations.AddIndex(
            model_name='todonotification',
            index=models.Index(fields=['todo', 'notification_type'], name='todo_manage_todo_id_5cfba9_idx'),
        ),
    ]
