# Generated by Django 5.2.6 on 2025-09-04 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todo_management', '0002_todonotification_todotemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('primary_due_at', models.DateTimeField(blank=True, null=True)),
                ('recurrence_rule', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='todo_management.todoitem')),
            ],
            options={
                'verbose_name': 'Σύνδεση TODO',
                'verbose_name_plural': 'Συνδέσεις TODO',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='todo_manage_content_8e11e4_idx')],
            },
        ),
    ]
