# Generated by Django 5.2.6 on 2025-09-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_management', '0003_todolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolink',
            name='object_id',
            field=models.TextField(),
        ),
    ]
