# Generated by Django 5.2.4 on 2025-08-06 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0007_building_current_reserve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Όνομα/Επωνυμία')),
                ('collaborator_type', models.CharField(choices=[('consultant', 'Σύμβουλος'), ('contractor', 'Ανάδοχος'), ('specialist', 'Ειδικός'), ('advisor', 'Σύμβουλος'), ('partner', 'Συνεργάτης'), ('vendor', 'Προμηθευτής'), ('service_provider', 'Πάροχος Υπηρεσιών'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Συνεργάτη')),
                ('contact_person', models.CharField(max_length=255, verbose_name='Επικοινωνία')),
                ('phone', models.CharField(max_length=20, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.TextField(verbose_name='Διεύθυνση')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ')),
                ('vat_number', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ')),
                ('website', models.URLField(blank=True, verbose_name='Ιστοσελίδα')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('expertise_areas', models.JSONField(default=list, help_text='List με τους τομείς εξειδίκευσης', verbose_name='Τομείς Εξειδίκευσης')),
                ('status', models.CharField(choices=[('active', 'Ενεργός'), ('inactive', 'Ανενεργός'), ('suspended', 'Ανασταλμένος'), ('terminated', 'Τερματισμένος')], default='active', max_length=20, verbose_name='Κατάσταση')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Αξιολόγηση')),
                ('hourly_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ωριαίος Τιμολογιακός Ταρίφ')),
                ('availability', models.CharField(choices=[('available', 'Διαθέσιμος'), ('busy', 'Απασχολημένος'), ('unavailable', 'Μη Διαθέσιμος')], default='available', max_length=20, verbose_name='Διαθεσιμότητα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Συνεργάτης',
                'verbose_name_plural': 'Συνεργάτες',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Συμβολαίου')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Συμβολαίου')),
                ('contract_type', models.CharField(choices=[('service', 'Υπηρεσίες'), ('consulting', 'Συμβουλευτική'), ('maintenance', 'Συντήρηση'), ('project', 'Έργο'), ('support', 'Υποστήριξη'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Συμβολαίου')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('active', 'Ενεργό'), ('expired', 'Ληγμένο'), ('terminated', 'Τερματισμένο'), ('renewed', 'Ανανεωμένο')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Συνολική Αξία')),
                ('payment_terms', models.TextField(verbose_name='Όροι Πληρωμής')),
                ('scope_of_work', models.TextField(verbose_name='Πεδίο Εργασίας')),
                ('deliverables', models.TextField(verbose_name='Παραδοτέα')),
                ('terms_conditions', models.TextField(verbose_name='Όροι & Προϋποθέσεις')),
                ('contract_file', models.FileField(blank=True, upload_to='collaboration_contracts/%Y/%m/', verbose_name='Αρχείο Συμβολαίου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_contracts', to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaboration_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='collaborators.collaborator', verbose_name='Συνεργάτης')),
            ],
            options={
                'verbose_name': 'Συμβόλαιο Συνεργασίας',
                'verbose_name_plural': 'Συμβόλαια Συνεργασίας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Έργου')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('project_type', models.CharField(choices=[('consulting', 'Συμβουλευτική'), ('implementation', 'Υλοποίηση'), ('maintenance', 'Συντήρηση'), ('training', 'Εκπαίδευση'), ('audit', 'Ελεγκτική'), ('research', 'Έρευνα'), ('development', 'Ανάπτυξη'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Έργου')),
                ('status', models.CharField(choices=[('planning', 'Σχεδιασμός'), ('active', 'Ενεργό'), ('on_hold', 'Σε Αναμονή'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρώθηκε')], default='planning', max_length=20, verbose_name='Κατάσταση')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Προϋπολογισμός')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Πραγματικό Κόστος')),
                ('deliverables', models.JSONField(default=list, help_text='List με τα παραδοτέα του έργου', verbose_name='Παραδοτέα')),
                ('milestones', models.JSONField(default=list, help_text='List με τα ορόσημα του έργου', verbose_name='Ορόσημα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaboration_projects', to='buildings.building', verbose_name='Κτίριο')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_collaboration_projects', to=settings.AUTH_USER_MODEL, verbose_name='Διευθυντής Έργου')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='collaborators.collaborator', verbose_name='Συνεργάτης')),
            ],
            options={
                'verbose_name': 'Έργο Συνεργασίας',
                'verbose_name_plural': 'Έργα Συνεργασίας',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Συνάντησης')),
                ('meeting_type', models.CharField(choices=[('kickoff', 'Εκκίνηση Έργου'), ('progress', 'Πρόοδος'), ('review', 'Ανασκόπηση'), ('planning', 'Σχεδιασμός'), ('issue', 'Επίλυση Προβλήματος'), ('closure', 'Ολοκλήρωση'), ('other', 'Άλλο')], default='other', max_length=20, verbose_name='Τύπος Συνάντησης')),
                ('scheduled_at', models.DateTimeField(verbose_name='Προγραμματισμένη Ώρα')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Διάρκεια (λεπτά)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Τοποθεσία')),
                ('is_online', models.BooleanField(default=False, verbose_name='Διαδικτυακή')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Σύνδεσμος Συνάντησης')),
                ('agenda', models.TextField(blank=True, verbose_name='Ημερήσια Διάταξη')),
                ('minutes', models.TextField(blank=True, verbose_name='Πρακτικά')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendees', models.ManyToManyField(related_name='collaboration_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Παρευρισκόμενοι')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_collaboration_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='collaborators.collaborationproject', verbose_name='Έργο')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='collaborators.collaborator', verbose_name='Συνεργάτης')),
            ],
            options={
                'verbose_name': 'Συνάντηση Συνεργασίας',
                'verbose_name_plural': 'Συναντήσεις Συνεργασίας',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='CollaborationInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Τιμολογίου')),
                ('issue_date', models.DateField(verbose_name='Ημερομηνία Έκδοσης')),
                ('due_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσό')),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Ποσό ΦΠΑ')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Συνολικό Ποσό')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('sent', 'Αποσταλμένο'), ('paid', 'Εισπραχθέν'), ('overdue', 'Ληξιπρόθεσμο'), ('cancelled', 'Ακυρώθηκε')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('invoice_file', models.FileField(blank=True, upload_to='collaboration_invoices/%Y/%m/', verbose_name='Αρχείο Τιμολογίου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='collaborators.collaborationcontract', verbose_name='Συμβόλαιο')),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='collaborators.collaborator', verbose_name='Συνεργάτης')),
            ],
            options={
                'verbose_name': 'Τιμολόγιο Συνεργασίας',
                'verbose_name_plural': 'Τιμολόγια Συνεργασίας',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='CollaboratorPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Έναρξη Περιόδου')),
                ('period_end', models.DateField(verbose_name='Λήξη Περιόδου')),
                ('projects_completed', models.PositiveIntegerField(default=0, verbose_name='Ολοκληρωμένα Έργα')),
                ('projects_total', models.PositiveIntegerField(default=0, verbose_name='Συνολικά Έργα')),
                ('average_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Μέση Αξιολόγηση')),
                ('on_time_delivery_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ποσοστό Εγκαίρων Παράδοσης (%)')),
                ('quality_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Βαθμός Ποιότητας')),
                ('communication_score', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Βαθμός Επικοινωνίας')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collaborator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='collaborators.collaborator', verbose_name='Συνεργάτης')),
            ],
            options={
                'verbose_name': 'Απόδοση Συνεργάτη',
                'verbose_name_plural': 'Αποδόσεις Συνεργατών',
                'ordering': ['-period_end'],
                'unique_together': {('collaborator', 'period_start', 'period_end')},
            },
        ),
    ]
