# Generated by Django 5.2.8 on 2025-12-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0011_apartment_kiosk_token'),
        ('buildings', '0026_internal_manager_framework'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='MAC Address ή Unique Serial Number', max_length=100, unique=True, verbose_name='Device ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Συσκευής')),
                ('device_type', models.CharField(choices=[('shelly_1', 'Shelly 1/1PM'), ('sonoff_mini', 'Sonoff Mini'), ('custom_esp', 'Custom ESP32'), ('virtual', 'Virtual Simulator')], default='shelly_1', max_length=20)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Τελευταία Επικοινωνία')),
                ('current_status', models.BooleanField(default=False, verbose_name='Τρέχουσα Κατάσταση (ON/OFF)')),
                ('api_key', models.CharField(blank=True, help_text='Κλειδί για Authentication συσκευής', max_length=64)),
                ('apartment', models.ForeignKey(blank=True, help_text='Αν η συσκευή αφορά συγκεκριμένο διαμέρισμα (αυτονομία)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='heating_devices', to='apartments.apartment', verbose_name='Διαμέρισμα')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heating_devices', to='buildings.building', verbose_name='Κτίριο')),
            ],
            options={
                'verbose_name': 'Συσκευή Θέρμανσης (IoT)',
                'verbose_name_plural': 'Συσκευές Θέρμανσης (IoT)',
            },
        ),
        migrations.CreateModel(
            name='HeatingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(verbose_name='Έναρξη')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Λήξη')),
                ('duration_minutes', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Διάρκεια (λεπτά)')),
                ('is_billed', models.BooleanField(default=False, verbose_name='Έχει Χρεωθεί')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='iot_heating.heatingdevice', verbose_name='Συσκευή')),
            ],
            options={
                'verbose_name': 'Συνεδρία Θέρμανσης',
                'verbose_name_plural': 'Συνεδρίες Θέρμανσης',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TelemetryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField(verbose_name='Raw Data')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='iot_heating.heatingdevice')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
