# Generated by Django 5.2.8 on 2025-12-29 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0029_building_trial_ends_at'),
        ('iot_heating', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeatingControlProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curve_value', models.PositiveSmallIntegerField(default=60, verbose_name='Καμπύλη λειτουργίας (%)')),
                ('min_external_temp', models.SmallIntegerField(default=8, verbose_name='Ελάχιστη θερμοκρασία εκκίνησης (°C)')),
                ('schedule', models.JSONField(blank=True, default=list, verbose_name='Ωράρια λειτουργίας')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημ/νία δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία ενημέρωση')),
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='heating_profile', to='buildings.building', verbose_name='Κτίριο')),
            ],
            options={
                'verbose_name': 'Ρυθμίσεις Smart Heating',
                'verbose_name_plural': 'Ρυθμίσεις Smart Heating',
            },
        ),
    ]
