// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(dashboard)/admin/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/calendar">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/admin/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/announcements/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/announcements/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/announcements/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/announcements/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/announcements">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/apartments/enhanced/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apartments/enhanced">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/apartments/enhanced/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/apartments/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apartments/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/apartments/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/apartments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/apartments">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/apartments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/[id]/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/[id]/announcements">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/[id]/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/[id]/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/[id]/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/[id]/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/[id]/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/[id]/requests">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/[id]/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/assign-resident/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/assign-resident">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/assign-resident/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/buildings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/buildings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/calendar/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/calendar">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/calendar/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/chat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/chat">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/chat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/collaborators/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/collaborators">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/collaborators/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/data-migration/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/data-migration">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/data-migration/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/documents/[id]/review/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents/[id]/review">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/documents/[id]/review/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/documents/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/documents">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/documents/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/financial-tests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financial-tests">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/financial-tests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/financial/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/financial">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/financial/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/kiosk-settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kiosk-settings">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/kiosk-settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/contractors/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/contractors/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/contractors/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/contractors/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/contractors/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/contractors/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/contractors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/contractors">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/contractors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/receipts/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/receipts/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/receipts/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/receipts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/receipts/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/receipts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/receipts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/receipts">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/receipts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/scheduled/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/scheduled/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/scheduled/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/scheduled/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/scheduled/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/scheduled/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/scheduled/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/scheduled/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/scheduled/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/scheduled/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/scheduled">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/scheduled/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/tickets/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/tickets/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/tickets/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/tickets/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/tickets/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/tickets/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/tickets/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/tickets">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/tickets/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/work-orders/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/work-orders/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/work-orders/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/work-orders/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/work-orders/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/work-orders/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/maintenance/work-orders/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/maintenance/work-orders">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/maintenance/work-orders/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/map-visualization/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/map-visualization">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/map-visualization/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/contracts/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/contracts/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/contracts/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/contracts/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/contracts">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/contracts/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/milestones/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/milestones/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/milestones/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/offers/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/offers/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/offers/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/offers/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/offers/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/offers/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/offers/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/offers/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/offers/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/offers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/offers">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/offers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/projects/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/projects">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/projects/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/reports/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/projects/reports">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/reports/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/requests/[id]/edit/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/[id]/edit">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/requests/[id]/edit/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/requests/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/requests/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/requests/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/requests/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/requests/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/requests">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/requests/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/residents/assign/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/residents/assign">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/residents/assign/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/residents/list/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/residents/list">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/residents/list/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/residents/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/residents/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/residents/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/suppliers/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/suppliers">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/suppliers/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/system-health/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/system-health">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/system-health/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/teams/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/teams">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/teams/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/votes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/votes/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/votes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/votes/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/votes/new">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/votes/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/votes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/votes">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/votes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/connect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/connect">> = Specific
  const handler = {} as typeof import("../../app/connect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug-street-view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug-street-view">> = Specific
  const handler = {} as typeof import("../../app/debug-street-view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug">> = Specific
  const handler = {} as typeof import("../../app/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/info-screen/[buildingId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/info-screen/[buildingId]">> = Specific
  const handler = {} as typeof import("../../app/info-screen/[buildingId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/kiosk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/kiosk">> = Specific
  const handler = {} as typeof import("../../app/kiosk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/logout/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/logout">> = Specific
  const handler = {} as typeof import("../../app/logout/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-form-submission/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-form-submission">> = Specific
  const handler = {} as typeof import("../../app/test-form-submission/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-intro-animation/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-intro-animation">> = Specific
  const handler = {} as typeof import("../../app/test-intro-animation/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-kiosk/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-kiosk">> = Specific
  const handler = {} as typeof import("../../app/test-kiosk/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-logo/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-logo">> = Specific
  const handler = {} as typeof import("../../app/test-logo/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/test-street-view/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/test-street-view">> = Specific
  const handler = {} as typeof import("../../app/test-street-view/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unauthorized/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unauthorized">> = Specific
  const handler = {} as typeof import("../../app/unauthorized/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/verify-payment/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/verify-payment/[id]">> = Specific
  const handler = {} as typeof import("../../app/verify-payment/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/community-messages/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/community-messages">> = Specific
  const handler = {} as typeof import("../../app/api/community-messages/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/financial/common-expenses/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/financial/common-expenses">> = Specific
  const handler = {} as typeof import("../../app/api/financial/common-expenses/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/financial/previous-balance/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/financial/previous-balance">> = Specific
  const handler = {} as typeof import("../../app/api/financial/previous-balance/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/maintenance/contractors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/maintenance/contractors">> = Specific
  const handler = {} as typeof import("../../app/api/maintenance/contractors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/news/multiple/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news/multiple">> = Specific
  const handler = {} as typeof import("../../app/api/news/multiple/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/news">> = Specific
  const handler = {} as typeof import("../../app/api/news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/contracts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/contracts">> = Specific
  const handler = {} as typeof import("../../app/api/projects/contracts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/dashboard/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/dashboard">> = Specific
  const handler = {} as typeof import("../../app/api/projects/dashboard/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/offers/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/offers/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/projects/offers/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/offers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/offers">> = Specific
  const handler = {} as typeof import("../../app/api/projects/offers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/rfqs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects/rfqs">> = Specific
  const handler = {} as typeof import("../../app/api/projects/rfqs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/projects/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/projects">> = Specific
  const handler = {} as typeof import("../../app/api/projects/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quote/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote">> = Specific
  const handler = {} as typeof import("../../app/api/quote/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/weather/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/weather">> = Specific
  const handler = {} as typeof import("../../app/api/weather/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/(dashboard)/buildings/[id]/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/buildings/[id]">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/buildings/[id]/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/financial/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/financial">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/financial/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(dashboard)/projects/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/projects">> = Specific
  const handler = {} as typeof import("../../app/(dashboard)/projects/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/display/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/display">> = Specific
  const handler = {} as typeof import("../../app/display/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
