# Generated by Django 5.2.4 on 2025-07-24 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vote',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ψηφοφορία', 'verbose_name_plural': 'Ψηφοφορίες'},
        ),
        migrations.AlterModelOptions(
            name='votesubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Ψήφος', 'verbose_name_plural': 'Ψήφοι'},
        ),
        migrations.AddField(
            model_name='vote',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Ενεργή ψηφοφορία'),
        ),
        migrations.AddField(
            model_name='vote',
            name='is_urgent',
            field=models.BooleanField(default=False, help_text='Επείγουσα ψηφοφορία'),
        ),
        migrations.AddField(
            model_name='vote',
            name='min_participation',
            field=models.IntegerField(default=0, help_text='Ελάχιστο ποσοστό συμμετοχής για έγκυρα αποτελέσματα (%)'),
        ),
        migrations.AddField(
            model_name='vote',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='votesubmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='buildings.building'),
        ),
    ]
