# Generated by Django 5.0.14 on 2025-07-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
        ('votes', '0002_alter_vote_options_alter_votesubmission_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Αφήστε κενό για ψηφοφορία σε όλα τα κτίρια', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='buildings.building'),
        ),
    ]
