# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_add_vote_source_to_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='votesubmission',
            name='last_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='VoteSubmissionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('choice', models.CharField(choices=[('ΝΑΙ', 'ΝΑΙ'), ('ΟΧΙ', 'ΟΧΙ'), ('ΛΕΥΚΟ', 'ΛΕΥΚΟ')], max_length=50)),
                ('mills', models.PositiveIntegerField(default=0)),
                ('vote_source', models.CharField(choices=[('app', 'Εφαρμογή'), ('email', 'Email Link'), ('pre_vote', 'Ηλεκτρονικά (Pre-voting)'), ('live', 'Φυσική Παρουσία'), ('proxy', 'Εξουσιοδότηση')], default='app', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_submission_actor_events', to=settings.AUTH_USER_MODEL)),
                ('previous_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_events', to='votes.votesubmissionevent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_submission_events', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_events', to='votes.vote')),
                ('vote_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='votes.votesubmission')),
            ],
            options={
                'verbose_name': 'Ιστορικό Υποβολής Ψήφου',
                'verbose_name_plural': 'Ιστορικό Υποβολών Ψήφων',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='votesubmission',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='votes.votesubmissionevent'),
        ),
    ]
