# Generated by Codex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0006_vote_submission_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='votesubmissionevent',
            name='prev_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='votesubmissionevent',
            name='event_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
