// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin/calendar" | "/announcements" | "/announcements/[id]" | "/announcements/new" | "/apartments" | "/apartments/enhanced" | "/apartments/new" | "/buildings" | "/buildings/[id]" | "/buildings/[id]/announcements" | "/buildings/[id]/dashboard" | "/buildings/[id]/edit" | "/buildings/[id]/requests" | "/buildings/assign-resident" | "/buildings/new" | "/calendar" | "/chat" | "/collaborators" | "/connect" | "/dashboard" | "/data-migration" | "/debug" | "/debug-street-view" | "/documents" | "/documents/[id]/review" | "/financial" | "/financial-tests" | "/info-screen/[buildingId]" | "/kiosk" | "/kiosk-settings" | "/kiosk-widgets" | "/login" | "/logout" | "/maintenance" | "/maintenance/contractors" | "/maintenance/contractors/[id]/edit" | "/maintenance/contractors/new" | "/maintenance/receipts" | "/maintenance/receipts/[id]/edit" | "/maintenance/receipts/new" | "/maintenance/reports" | "/maintenance/scheduled" | "/maintenance/scheduled/[id]" | "/maintenance/scheduled/[id]/edit" | "/maintenance/scheduled/new" | "/maintenance/tickets" | "/maintenance/tickets/[id]" | "/maintenance/tickets/new" | "/maintenance/work-orders" | "/maintenance/work-orders/[id]" | "/maintenance/work-orders/new" | "/map-visualization" | "/projects" | "/projects/[id]" | "/projects/[id]/edit" | "/projects/contracts" | "/projects/contracts/new" | "/projects/milestones/new" | "/projects/new" | "/projects/offers" | "/projects/offers/[id]" | "/projects/offers/[id]/edit" | "/projects/offers/new" | "/projects/projects" | "/projects/reports" | "/register" | "/requests" | "/requests/[id]" | "/requests/[id]/edit" | "/requests/new" | "/residents/assign" | "/residents/list" | "/residents/new" | "/suppliers" | "/system-health" | "/teams" | "/test-form-submission" | "/test-intro-animation" | "/test-kiosk" | "/test-logo" | "/test-street-view" | "/unauthorized" | "/verify-payment/[id]" | "/votes" | "/votes/[id]" | "/votes/new"
type AppRouteHandlerRoutes = "/api/community-messages" | "/api/financial/common-expenses" | "/api/financial/previous-balance" | "/api/kiosk/widgets/config" | "/api/maintenance/contractors" | "/api/news" | "/api/news/multiple" | "/api/projects" | "/api/projects/[id]" | "/api/projects/contracts" | "/api/projects/dashboard" | "/api/projects/offers" | "/api/projects/offers/[id]" | "/api/projects/rfqs" | "/api/quote" | "/api/weather"
type PageRoutes = never
type LayoutRoutes = "/" | "/buildings/[id]" | "/display" | "/financial" | "/projects"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin/calendar": {}
  "/announcements": {}
  "/announcements/[id]": { "id": string; }
  "/announcements/new": {}
  "/apartments": {}
  "/apartments/enhanced": {}
  "/apartments/new": {}
  "/api/community-messages": {}
  "/api/financial/common-expenses": {}
  "/api/financial/previous-balance": {}
  "/api/kiosk/widgets/config": {}
  "/api/maintenance/contractors": {}
  "/api/news": {}
  "/api/news/multiple": {}
  "/api/projects": {}
  "/api/projects/[id]": { "id": string; }
  "/api/projects/contracts": {}
  "/api/projects/dashboard": {}
  "/api/projects/offers": {}
  "/api/projects/offers/[id]": { "id": string; }
  "/api/projects/rfqs": {}
  "/api/quote": {}
  "/api/weather": {}
  "/buildings": {}
  "/buildings/[id]": { "id": string; }
  "/buildings/[id]/announcements": { "id": string; }
  "/buildings/[id]/dashboard": { "id": string; }
  "/buildings/[id]/edit": { "id": string; }
  "/buildings/[id]/requests": { "id": string; }
  "/buildings/assign-resident": {}
  "/buildings/new": {}
  "/calendar": {}
  "/chat": {}
  "/collaborators": {}
  "/connect": {}
  "/dashboard": {}
  "/data-migration": {}
  "/debug": {}
  "/debug-street-view": {}
  "/display": {}
  "/documents": {}
  "/documents/[id]/review": { "id": string; }
  "/financial": {}
  "/financial-tests": {}
  "/info-screen/[buildingId]": { "buildingId": string; }
  "/kiosk": {}
  "/kiosk-settings": {}
  "/kiosk-widgets": {}
  "/login": {}
  "/logout": {}
  "/maintenance": {}
  "/maintenance/contractors": {}
  "/maintenance/contractors/[id]/edit": { "id": string; }
  "/maintenance/contractors/new": {}
  "/maintenance/receipts": {}
  "/maintenance/receipts/[id]/edit": { "id": string; }
  "/maintenance/receipts/new": {}
  "/maintenance/reports": {}
  "/maintenance/scheduled": {}
  "/maintenance/scheduled/[id]": { "id": string; }
  "/maintenance/scheduled/[id]/edit": { "id": string; }
  "/maintenance/scheduled/new": {}
  "/maintenance/tickets": {}
  "/maintenance/tickets/[id]": { "id": string; }
  "/maintenance/tickets/new": {}
  "/maintenance/work-orders": {}
  "/maintenance/work-orders/[id]": { "id": string; }
  "/maintenance/work-orders/new": {}
  "/map-visualization": {}
  "/projects": {}
  "/projects/[id]": { "id": string; }
  "/projects/[id]/edit": { "id": string; }
  "/projects/contracts": {}
  "/projects/contracts/new": {}
  "/projects/milestones/new": {}
  "/projects/new": {}
  "/projects/offers": {}
  "/projects/offers/[id]": { "id": string; }
  "/projects/offers/[id]/edit": { "id": string; }
  "/projects/offers/new": {}
  "/projects/projects": {}
  "/projects/reports": {}
  "/register": {}
  "/requests": {}
  "/requests/[id]": { "id": string; }
  "/requests/[id]/edit": { "id": string; }
  "/requests/new": {}
  "/residents/assign": {}
  "/residents/list": {}
  "/residents/new": {}
  "/suppliers": {}
  "/system-health": {}
  "/teams": {}
  "/test-form-submission": {}
  "/test-intro-animation": {}
  "/test-kiosk": {}
  "/test-logo": {}
  "/test-street-view": {}
  "/unauthorized": {}
  "/verify-payment/[id]": { "id": string; }
  "/votes": {}
  "/votes/[id]": { "id": string; }
  "/votes/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/buildings/[id]": never
  "/display": never
  "/financial": never
  "/projects": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
