# Generated by Django 5.2.4 on 2025-08-02 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicereceipt',
            name='building',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='contractor',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='ScheduledMaintenance',
        ),
        migrations.DeleteModel(
            name='ServiceReceipt',
        ),
    ]
