# Generated by Django 5.2.4 on 2025-08-02 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_building_management_office_address_and_more'),
        ('maintenance', '0002_remove_servicereceipt_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledMaintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('scheduled_date', models.DateField(verbose_name='Προγραμματισμένη Ημερομηνία')),
                ('estimated_duration', models.IntegerField(help_text='Διάρκεια σε ώρες', verbose_name='Εκτιμώμενη Διάρκεια')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μέτρια'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=20, verbose_name='Προτεραιότητα')),
                ('status', models.CharField(choices=[('scheduled', 'Προγραμματισμένο'), ('in_progress', 'Σε Εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρώθηκε')], default='scheduled', max_length=20, verbose_name='Κατάσταση')),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Εκτιμώμενο Κόστος')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Πραγματικό Κόστος')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Τοποθεσία')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_maintenance', to='buildings.building', verbose_name='Κτίριο')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_work', to='maintenance.contractor', verbose_name='Συνεργείο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_maintenance', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Προγραμματισμένη Συντήρηση',
                'verbose_name_plural': 'Προγραμματισμένες Συντηρήσεις',
                'ordering': ['scheduled_date', 'priority'],
            },
        ),
        migrations.CreateModel(
            name='ServiceReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(verbose_name='Ημερομηνία Υπηρεσίας')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό')),
                ('receipt_file', models.FileField(upload_to='receipts/%Y/%m/', verbose_name='Απόδειξη')),
                ('description', models.TextField(verbose_name='Περιγραφή Υπηρεσίας')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Τιμολογίου')),
                ('payment_status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('paid', 'Πληρωμένο'), ('overdue', 'Ληξιπρόθεσμο')], default='pending', max_length=20, verbose_name='Κατάσταση Πληρωμής')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_receipts', to='buildings.building', verbose_name='Κτίριο')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='maintenance.contractor', verbose_name='Συνεργείο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Απόδειξη Υπηρεσίας',
                'verbose_name_plural': 'Αποδείξεις Υπηρεσιών',
                'ordering': ['-service_date'],
            },
        ),
    ]
