# Generated by Django 5.2.4 on 2025-08-06 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_scheduledmaintenance_servicereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='availability',
            field=models.CharField(choices=[('available', 'Διαθέσιμο'), ('busy', 'Απασχολημένο'), ('unavailable', 'Μη Διαθέσιμο')], default='available', max_length=20, verbose_name='Διαθεσιμότητα'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Επείγουσα Επικοινωνία'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Επείγουσο Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='hourly_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Ωριαίος Τιμολογιακός Ταρίφ'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='insurance_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Ασφάλισης'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Αριθμός Άδειας'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Βαθμός Αξιοπιστίας'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='response_time_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Χρόνος Απόκρισης (ώρες)'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='specializations',
            field=models.JSONField(default=list, help_text='List με τις εξειδικεύσεις του συνεργείου', verbose_name='Εξειδικεύσεις'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='status',
            field=models.CharField(choices=[('active', 'Ενεργό'), ('inactive', 'Ανενεργό'), ('suspended', 'Ανασταλμένο'), ('terminated', 'Τερματισμένο')], default='active', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='vat_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='website',
            field=models.URLField(blank=True, verbose_name='Ιστοσελίδα'),
        ),
        migrations.AlterField(
            model_name='contractor',
            name='service_type',
            field=models.CharField(choices=[('repair', 'Επισκευές'), ('cleaning', 'Καθαριότητα'), ('security', 'Ασφάλεια'), ('electrical', 'Ηλεκτρολογικά'), ('plumbing', 'Υδραυλικά'), ('heating', 'Θέρμανση/Κλιματισμός'), ('elevator', 'Ανελκυστήρες'), ('landscaping', 'Κηπουρική'), ('painting', 'Βαψίματα'), ('carpentry', 'Ξυλουργική'), ('masonry', 'Κατασκευές'), ('technical', 'Τεχνικές Υπηρεσίες'), ('maintenance', 'Συντήρηση'), ('emergency', 'Επείγοντα'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Υπηρεσίας'),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Εισπράξεως'),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Εκκρεμεί'), ('paid', 'Εισπραχθέν'), ('overdue', 'Ληξιπρόθεσμο')], default='pending', max_length=20, verbose_name='Κατάσταση Εισπράξεως'),
        ),
    ]
