# Generated by Django 5.2.6 on 2025-09-04 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0010_apartment_previous_balance'),
        ('buildings', '0015_alter_building_grace_day_of_month'),
        ('maintenance', '0004_contractor_availability_contractor_emergency_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('category', models.CharField(choices=[('electrical', 'Ηλεκτρολογικά'), ('plumbing', 'Υδραυλικά'), ('elevator', 'Ανελκυστήρας'), ('hvac', 'Θέρμανση/Κλιματισμός'), ('cleaning', 'Καθαριότητα'), ('security', 'Ασφάλεια'), ('general', 'Γενικό'), ('other', 'Άλλο')], default='general', max_length=30, verbose_name='Κατηγορία')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μέτρια'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=20, verbose_name='Προτεραιότητα')),
                ('status', models.CharField(choices=[('open', 'Ανοιχτό'), ('triaged', 'Κατηγοριοποιημένο'), ('in_progress', 'Σε εξέλιξη'), ('waiting_vendor', 'Αναμονή συνεργείου'), ('blocked', 'Μπλοκαρισμένο'), ('completed', 'Ολοκληρωμένο'), ('closed', 'Κλειστό'), ('cancelled', 'Ακυρώθηκε')], default='open', max_length=20, verbose_name='Κατάσταση')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Τοποθεσία')),
                ('sla_due_at', models.DateTimeField(blank=True, null=True, verbose_name='Προθεσμία SLA')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Κλεισίματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_tickets', to='apartments.apartment', verbose_name='Διαμέρισμα')),
                ('assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Υπεύθυνος')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='buildings.building', verbose_name='Κτίριο')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='maintenance.contractor', verbose_name='Συνεργείο')),
                ('reporter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Αναφέρων')),
            ],
            options={
                'verbose_name': 'Αίτημα Συντήρησης',
                'verbose_name_plural': 'Αιτήματα Συντήρησης',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduled', 'Προγραμματισμένο'), ('assigned', 'Ανατεθειμένο'), ('en_route', 'Καθοδόν'), ('in_progress', 'Σε εξέλιξη'), ('paused', 'Παύση'), ('done', 'Ολοκληρώθηκε'), ('verified', 'Επαληθεύτηκε'), ('cancelled', 'Ακυρώθηκε')], default='scheduled', max_length=20, verbose_name='Κατάσταση')),
                ('scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Προγραμματισμένη Ημ/νία')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Έναρξη')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Λήξη')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Τοποθεσία')),
                ('cost_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Εκτίμηση Κόστους')),
                ('actual_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Πραγματικό Κόστος')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Υπεύθυνος')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.contractor', verbose_name='Συνεργείο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_work_orders', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='maintenance.maintenanceticket', verbose_name='Αίτημα')),
            ],
            options={
                'verbose_name': 'Εντολή Εργασίας',
                'verbose_name_plural': 'Εντολές Εργασίας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['building', 'status'], name='maintenance_buildin_9868c9_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['building', 'priority'], name='maintenance_buildin_984eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceticket',
            index=models.Index(fields=['building', 'sla_due_at'], name='maintenance_buildin_4945ec_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['status'], name='maintenance_status_5c5a38_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['scheduled_at'], name='maintenance_schedul_6817c6_idx'),
        ),
    ]
