# Generated by Django 5.2.6 on 2025-09-04 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenanceticket_workorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='tickets/%Y/%m/', verbose_name='Συνημμένο'),
        ),
    ]
