# Generated by Django 5.2.6 on 2025-09-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0024_add_financial_receipt'),
        ('maintenance', '0006_maintenanceticket_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereceipt',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_service_receipts', to='financial.expense', verbose_name='Συνδεδεμένη Δαπάνη'),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='Απόδειξη'),
        ),
    ]
