# Generated by Django 5.2.6 on 2025-09-06 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_servicereceipt_linked_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereceipt',
            name='scheduled_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_receipts', to='maintenance.scheduledmaintenance', verbose_name='Σχετικό Έργο'),
        ),
    ]
