# Generated by Django 5.2.6 on 2025-09-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_servicereceipt_scheduled_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Επαναλαμβανόμενο'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='recurrence_frequency',
            field=models.CharField(blank=True, choices=[('weekly', 'Εβδομαδιαία'), ('monthly', 'Μηνιαία'), ('bimonthly', 'Ανά 2 μήνες'), ('quarterly', 'Τριμηνιαία'), ('semiannual', 'Εξαμηνιαία'), ('annual', 'Ετήσια')], max_length=20, null=True, verbose_name='Συχνότητα'),
        ),
    ]
