# Generated by Django 5.2.6 on 2025-09-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_scheduledmaintenance_is_recurring_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledmaintenance',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='scheduledmaintenance',
            name='recurrence_frequency',
        ),
    ]
