# Generated by Django 5.2.6 on 2025-09-06 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_alter_building_grace_day_of_month'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('financial', '0029_remove_expense_linked_scheduled_maintenance_and_more'),
        ('maintenance', '0010_remove_scheduledmaintenance_is_recurring_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicereceipt',
            name='issued_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Έκδοσης'),
        ),
        migrations.AddField(
            model_name='servicereceipt',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής'),
        ),
        migrations.AddField(
            model_name='servicereceipt',
            name='payment_kind',
            field=models.CharField(choices=[('advance', 'Προκαταβολή'), ('partial', 'Μερική Καταβολή'), ('installment', 'Δόση Πλάνου'), ('settlement', 'Εξόφληση')], default='partial', max_length=20, verbose_name='Είδος Πληρωμής'),
        ),
        migrations.AddField(
            model_name='servicereceipt',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('card', 'Κάρτα'), ('other', 'Άλλο')], default='cash', max_length=20, verbose_name='Τρόπος Πληρωμής'),
        ),
        migrations.AddField(
            model_name='servicereceipt',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Αρ. συναλλαγής/IBAN ref/αρ. παραστατικού', max_length=100, verbose_name='Αναφορά Πληρωμής'),
        ),
        migrations.AddField(
            model_name='servicereceipt',
            name='signed_by_vendor_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Υπογραφή Συνεργείου'),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_service_receipts', to='financial.expense', verbose_name='Συνδεδεμένη Δαπάνη'),
        ),
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('plan_type', models.CharField(choices=[('fixed_installments', 'Σταθερές Δόσεις'), ('milestones', 'Ορόσημα'), ('periodic', 'Περιοδικό')], default='fixed_installments', max_length=30, verbose_name='Τύπος Πλάνου')),
                ('status', models.CharField(choices=[('active', 'Ενεργό'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρωμένο')], default='active', max_length=20, verbose_name='Κατάσταση')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Συνολικό Ποσό')),
                ('num_installments', models.PositiveIntegerField(blank=True, null=True, verbose_name='Αριθμός Δόσεων')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ποσό Ανά Δόση')),
                ('frequency', models.CharField(blank=True, choices=[('monthly', 'Μηνιαίο'), ('quarterly', 'Τριμηνιαίο'), ('yearly', 'Ετήσιο')], max_length=20, null=True, verbose_name='Συχνότητα')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Έναρξη')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Λήξη')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Επόμενη Ληκτότητα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_plans', to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_plans', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Πλάνο Πληρωμών',
                'verbose_name_plural': 'Πλάνα Πληρωμών',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσό Δόσης')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Καταβεβλημένο Ποσό')),
                ('status', models.CharField(choices=[('due', 'Ληκτό'), ('partial', 'Μερικώς Εξοφλημένο'), ('paid', 'Εξοφλημένο'), ('overdue', 'Ληξιπρόθεσμο')], default='due', max_length=20, verbose_name='Κατάσταση')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installments', to='maintenance.servicereceipt', verbose_name='Απόδειξη')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='maintenance.paymentplan', verbose_name='Πλάνο Πληρωμών')),
            ],
            options={
                'verbose_name': 'Δόση Πληρωμής',
                'verbose_name_plural': 'Δόσεις Πληρωμής',
                'ordering': ['due_date', 'id'],
            },
        ),
        migrations.AddField(
            model_name='servicereceipt',
            name='payment_plan',
            field=models.ForeignKey(blank=True, help_text='Προαιρετικά συνδέστε την απόδειξη σε πλάνο πληρωμών', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipts', to='maintenance.paymentplan', verbose_name='Σχέδιο Πληρωμών'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['building', 'status'], name='maintenance_buildin_284ea6_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentplan',
            index=models.Index(fields=['building', 'plan_type'], name='maintenance_buildin_767f97_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentinstallment',
            index=models.Index(fields=['due_date', 'status'], name='maintenance_due_dat_f38525_idx'),
        ),
    ]
