# Generated by Django 5.2.6 on 2025-09-06 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_remove_expense_linked_scheduled_maintenance_and_more'),
        ('maintenance', '0011_servicereceipt_issued_at_servicereceipt_paid_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentplan',
            name='building',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='paymentplan',
            name='owner_content_type',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='payment_plan',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='issued_at',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='paid_at',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='payment_kind',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='payment_reference',
        ),
        migrations.RemoveField(
            model_name='servicereceipt',
            name='signed_by_vendor_at',
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_service_receipts', to='financial.expense', verbose_name='Συνδεδεμένη Δαπάνη'),
        ),
        migrations.DeleteModel(
            name='PaymentInstallment',
        ),
        migrations.DeleteModel(
            name='PaymentPlan',
        ),
    ]
