# Generated by Django 5.2.6 on 2025-09-07 00:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_remove_paymentplan_building_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installment_number', models.PositiveIntegerField(verbose_name='Αριθμός Δόσης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσό')),
                ('due_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Πληρωθέν Ποσό')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('paid', 'Εξοφλήθηκε'), ('overdue', 'Ληξιπρόθεσμη'), ('cancelled', 'Ακυρώθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Τρόπος Πληρωμής')),
                ('transaction_reference', models.CharField(blank=True, max_length=100, verbose_name='Αναφορά Συναλλαγής')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Δόση Πληρωμής',
                'verbose_name_plural': 'Δόσεις Πληρωμών',
                'ordering': ['due_date', 'installment_number'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Απόδειξης')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Ημερομηνία Έκδοσης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ποσό')),
                ('payment_date', models.DateField(verbose_name='Ημερομηνία Πληρωμής')),
                ('payment_method', models.CharField(max_length=50, verbose_name='Τρόπος Πληρωμής')),
                ('payer_name', models.CharField(max_length=255, verbose_name='Όνομα Πληρωτή')),
                ('payer_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Πληρωτή')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('issued', 'Εκδόθηκε'), ('sent', 'Στάλθηκε'), ('acknowledged', 'Παραλήφθηκε'), ('disputed', 'Αμφισβητείται')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('digital_signature', models.TextField(blank=True, verbose_name='Ψηφιακή Υπογραφή')),
                ('signature_timestamp', models.DateTimeField(blank=True, null=True, verbose_name='Χρονική Σήμανση Υπογραφής')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='Αρχείο PDF')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='maintenance.paymentinstallment', verbose_name='Δόση')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Εκδόθηκε από')),
            ],
            options={
                'verbose_name': 'Απόδειξη Πληρωμής',
                'verbose_name_plural': 'Αποδείξεις Πληρωμών',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='PaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('lump_sum', 'Εφάπαξ'), ('installments', 'Δόσεις'), ('milestone', 'Ορόσημα'), ('monthly', 'Μηνιαίες Πληρωμές')], default='lump_sum', max_length=20, verbose_name='Τύπος Πληρωμής')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Συνολικό Ποσό')),
                ('number_of_installments', models.PositiveIntegerField(default=1, verbose_name='Αριθμός Δόσεων')),
                ('installment_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ποσό Δόσης')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης')),
                ('payment_frequency_days', models.PositiveIntegerField(default=30, verbose_name='Συχνότητα Πληρωμής (ημέρες)')),
                ('status', models.CharField(choices=[('active', 'Ενεργό'), ('completed', 'Ολοκληρωμένο'), ('cancelled', 'Ακυρώθηκε'), ('suspended', 'Αναστολή')], default='active', max_length=20, verbose_name='Κατάσταση')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_schedules', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('scheduled_maintenance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_schedule', to='maintenance.scheduledmaintenance', verbose_name='Προγραμματισμένη Συντήρηση')),
            ],
            options={
                'verbose_name': 'Πρόγραμμα Πληρωμών',
                'verbose_name_plural': 'Προγράμματα Πληρωμών',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='payment_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='maintenance.paymentschedule', verbose_name='Πρόγραμμα Πληρωμών'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentinstallment',
            unique_together={('payment_schedule', 'installment_number')},
        ),
    ]
