# Generated by Django 5.2.6 on 2025-09-07 03:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_remove_expense_linked_scheduled_maintenance_and_more'),
        ('maintenance', '0013_paymentinstallment_paymentreceipt_paymentschedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='digital_signature',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='issued_by',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='payer_email',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='payer_name',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='paymentreceipt',
            name='signature_timestamp',
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='installment_type',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Τύπος Δόσης (full/advance/installment/periodic/milestone)'),
        ),
        migrations.AddField(
            model_name='paymentinstallment',
            name='payment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Έγκρισης'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Εγκρίθηκε από'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αρχειοθέτησης'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='contractor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='maintenance.contractor', verbose_name='Συνεργείο'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='contractor_invoice',
            field=models.FileField(blank=True, null=True, upload_to='contractor_invoices/%Y/%m/', verbose_name='Τιμολόγιο Συνεργείου'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='contractor_signature',
            field=models.TextField(blank=True, verbose_name='Ψηφιακή Υπογραφή Συνεργείου'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='contractor_signature_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Υπογραφής'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='contractor_signature_ip',
            field=models.CharField(blank=True, max_length=64, verbose_name='IP Υπογραφής'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='description',
            field=models.TextField(blank=True, verbose_name='Περιγραφή'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_payment_receipts', to='financial.expense', verbose_name='Συνδεδεμένη Δαπάνη'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='receipt_file',
            field=models.FileField(blank=True, null=True, upload_to='payment_receipts/%Y/%m/', verbose_name='Αρχείο Απόδειξης'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='receipt_type',
            field=models.CharField(choices=[('advance', 'Προκαταβολή'), ('installment', 'Δόση'), ('final', 'Εξόφληση'), ('periodic', 'Περιοδική Καταβολή'), ('payment', 'Πληρωμή')], default='payment', max_length=20, verbose_name='Τύπος Απόδειξης'),
        ),
        migrations.AddField(
            model_name='paymentreceipt',
            name='scheduled_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to='maintenance.scheduledmaintenance', verbose_name='Προγραμματισμένη Συντήρηση'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='advance_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ποσοστό Προκαταβολής (%)'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='installment_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Αριθμός Δόσεων'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='installment_frequency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Συχνότητα Δόσεων (weekly/monthly/biweekly)'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='periodic_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ποσό Περιοδικής Καταβολής'),
        ),
        migrations.AddField(
            model_name='paymentschedule',
            name='periodic_frequency',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Συχνότητα Περιοδικών (weekly/monthly/quarterly/annual)'),
        ),
        migrations.AlterField(
            model_name='paymentinstallment',
            name='paid_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής (legacy)'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='installment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt', to='maintenance.paymentinstallment', verbose_name='Δόση'),
        ),
        migrations.AlterField(
            model_name='paymentreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Πρόχειρο'), ('issued', 'Εκδόθηκε'), ('signed', 'Υπογεγραμμένη'), ('approved', 'Εγκεκριμένη'), ('archived', 'Αρχειοθετημένη'), ('disputed', 'Αμφισβητείται')], default='draft', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='installment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Ποσό Δόσης (legacy)'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='number_of_installments',
            field=models.PositiveIntegerField(default=1, verbose_name='Αριθμός Δόσεων (legacy)'),
        ),
        migrations.AlterField(
            model_name='paymentschedule',
            name='payment_type',
            field=models.CharField(choices=[('lump_sum', 'Εφάπαξ'), ('advance_installments', 'Προκαταβολή + Δόσεις'), ('periodic', 'Περιοδικές Καταβολές'), ('milestone_based', 'Βάσει Ορόσημων')], default='lump_sum', max_length=20, verbose_name='Τύπος Πληρωμής'),
        ),
    ]
