# Generated by Django 5.2.6 on 2025-09-07 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0029_remove_expense_linked_scheduled_maintenance_and_more'),
        ('maintenance', '0014_remove_paymentreceipt_digital_signature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenance_tasks', to='financial.expense', verbose_name='Συνδεδεμένη Δαπάνη'),
        ),
    ]
