# Generated by Django 5.2.6 on 2025-09-09 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_scheduledmaintenance_linked_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ενοποιημένο πεδίο κόστους για απλοποιημένη διεπαφή', max_digits=10, null=True, verbose_name='Συνολικό Κόστος'),
        ),
    ]
