# Generated by Django 5.2.6 on 2025-09-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_add_total_cost_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='advance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Προκαταβολή'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='installments',
            field=models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Αριθμός Δόσεων'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Μετρητά, Τραπεζική Μεταφορά, Επιταγή, Κάρτα, Δόσεις', max_length=50, null=True, verbose_name='Τρόπος Πληρωμής'),
        ),
    ]
