# Generated by Django 5.2.6 on 2025-09-20 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_scheduledmaintenance_advance_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='contractor_contact',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Επαφή Συνεργείου'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='contractor_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Συνεργείου'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='contractor_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Όνομα Συνεργείου'),
        ),
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='contractor_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Τηλέφωνο Συνεργείου'),
        ),
    ]
