# Generated by Django 5.2.6 on 2025-09-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_scheduledmaintenance_contractor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='payment_terms',
            field=models.TextField(blank=True, help_text='Όροι και προϋποθέσεις πληρωμής από την εγκεκριμένη προσφορά', null=True, verbose_name='Όροι Πληρωμής'),
        ),
    ]
