# Generated by Django 5.2.6 on 2025-09-22 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_scheduledmaintenance_payment_terms'),
        ('projects', '0002_offer_advance_payment_offer_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledmaintenance',
            name='linked_project',
            field=models.ForeignKey(blank=True, help_text='Αν προέρχεται από εγκεκριμένη προσφορά', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scheduled_maintenances', to='projects.project', verbose_name='Συνδεδεμένο Έργο'),
        ),
    ]
