# Generated by Django 5.2.8 on 2025-12-21 01:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_add_linked_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplacePartner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_verified', models.BooleanField(default=True, verbose_name='Επαληθευμένος')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Προβεβλημένος')),
                ('short_description', models.CharField(blank=True, max_length=255, verbose_name='Σύντομη Περιγραφή')),
                ('detailed_description', models.TextField(blank=True, verbose_name='Αναλυτική Περιγραφή')),
                ('special_offers', models.TextField(blank=True, verbose_name='Ειδικές Προσφορές για Ενοίκους')),
                ('portfolio_links', models.JSONField(blank=True, default=list, verbose_name='Links Έργων')),
                ('show_in_marketplace', models.BooleanField(default=True, verbose_name='Εμφάνιση στο Marketplace')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contractor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_profile', to='maintenance.contractor', verbose_name='Συνεργείο')),
            ],
            options={
                'verbose_name': 'Συνεργάτης Marketplace',
                'verbose_name_plural': 'Συνεργάτες Marketplace',
                'ordering': ['-is_featured', 'contractor__name'],
            },
        ),
    ]
