# Generated by Django 5.2.8 on 2025-12-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assembly',
            name='email_1day_sent',
            field=models.BooleanField(default=False, verbose_name='Υπενθύμιση 1 ημέρας'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_1day_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_3days_sent',
            field=models.BooleanField(default=False, verbose_name='Υπενθύμιση 3 ημερών'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_3days_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_7days_sent',
            field=models.BooleanField(default=False, verbose_name='Υπενθύμιση 7 ημερών'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_7days_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_initial_sent',
            field=models.BooleanField(default=False, help_text='Επόμενη ημέρα από convening', verbose_name='Αρχική Ειδοποίηση Εστάλη'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_initial_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_sameday_sent',
            field=models.BooleanField(default=False, verbose_name='Υπενθύμιση ημέρας συνέλευσης'),
        ),
        migrations.AddField(
            model_name='assembly',
            name='email_sameday_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
