# Generated by Django 5.2.8 on 2025-12-21 01:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0002_add_email_tracking_fields'),
        ('buildings', '0026_internal_manager_framework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityPoll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Δημοσκόπησης')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('allow_multiple_choices', models.BooleanField(default=False, verbose_name='Πολλαπλές Επιλογές')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Λήξη')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Δημιουργίας')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Τελευταία Ενημέρωση')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_community_polls', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_polls', to='buildings.building', verbose_name='Κτίριο')),
            ],
            options={
                'verbose_name': 'Δημοσκόπηση Κοινότητας',
                'verbose_name_plural': 'Δημοσκοπήσεις Κοινότητας',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=255, verbose_name='Κείμενο Επιλογής')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Σειρά')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='assemblies.communitypoll', verbose_name='Δημοσκόπηση')),
            ],
            options={
                'verbose_name': 'Επιλογή Δημοσκόπησης',
                'verbose_name_plural': 'Επιλογές Δημοσκοπήσεων',
                'ordering': ['poll', 'order'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Ψήφου')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='assemblies.polloption', verbose_name='Επιλογή')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='assemblies.communitypoll', verbose_name='Δημοσκόπηση')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Ψήφος Δημοσκόπησης',
                'verbose_name_plural': 'Ψήφοι Δημοσκοπήσεων',
            },
        ),
        migrations.AddConstraint(
            model_name='pollvote',
            constraint=models.UniqueConstraint(fields=('poll', 'user', 'option'), name='uniq_poll_user_option_vote'),
        ),
    ]
