# Generated by Codex
from django.db import migrations, models
import django.db.models.deletion
import uuid
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('assemblies', '0006_add_proxy_assignment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssemblyVoteEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vote', models.CharField(choices=[('approve', 'Υπέρ'), ('reject', 'Κατά'), ('abstain', 'Λευκό')], max_length=10)),
                ('mills', models.PositiveIntegerField()),
                ('vote_source', models.CharField(choices=[('pre_vote', 'Pre-voting'), ('live', 'Κατά τη Συνέλευση'), ('proxy', 'Με Εξουσιοδότηση')], default='live', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('receipt_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assembly_vote_actor_events', to=settings.AUTH_USER_MODEL)),
                ('agenda_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_events', to='assemblies.agendaitem')),
                ('assembly_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='assemblies.assemblyvote')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_events', to='assemblies.assemblyattendee')),
                ('previous_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_events', to='assemblies.assemblyvoteevent')),
            ],
            options={
                'verbose_name': 'Ιστορικό Ψήφου Συνέλευσης',
                'verbose_name_plural': 'Ιστορικό Ψήφων Συνέλευσης',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.AddField(
            model_name='assemblyvote',
            name='last_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assemblies.assemblyvoteevent'),
        ),
    ]
