# Generated by Django 5.2.6 on 2025-09-15 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_parser', '0001_initial'),
        ('financial', '0036_monthlybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentupload',
            name='linked_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_document', to='financial.expense'),
        ),
        migrations.AddField(
            model_name='documentupload',
            name='original_file_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('awaiting_confirmation', 'Awaiting Confirmation'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=25),
        ),
    ]
