# Generated by Django 5.0.14 on 2025-06-03 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('role', models.CharField(choices=[('manager', 'Διαχειριστής'), ('owner', 'Ιδιοκτήτης'), ('tenant', 'Ένοικος')], default='tenant', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residents', to='buildings.building')),
            ],
            options={
                'ordering': ('building', 'apartment'),
            },
        ),
    ]
