# Generated by Django 5.1.9 on 2025-05-13 23:56

import django.db.models.deletion  # type: ignore  # type: ignore  # type: ignore
from django.conf import settings  # type: ignore  # type: ignore  # type: ignore
from django.db import migrations, models  # type: ignore  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('in_progress', 'Σε εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('rejected', 'Απορρίφθηκε')], default='pending', max_length=20)),
                ('type', models.CharField(blank=True, choices=[('maintenance', 'Συντήρηση'), ('cleaning', 'Καθαριότητα'), ('technical', 'Τεχνικό'), ('other', 'Άλλο')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to='buildings.building')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_requests', to=settings.AUTH_USER_MODEL)),
                ('supporters', models.ManyToManyField(blank=True, related_name='supported_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UrgentRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('supporter_count', models.PositiveIntegerField()),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urgent_logs', to='user_requests.userrequest')),
            ],
        ),
    ]
