# Generated by Django 5.2.4 on 2025-07-24 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urgentrequestlog',
            options={'ordering': ['-triggered_at'], 'verbose_name': 'Καταγραφή Επείγοντος Αιτήματος', 'verbose_name_plural': 'Καταγραφές Επείγοντων Αιτημάτων'},
        ),
        migrations.AlterModelOptions(
            name='userrequest',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Αίτημα Χρήστη', 'verbose_name_plural': 'Αιτήματα Χρηστών'},
        ),
        migrations.AddField(
            model_name='urgentrequestlog',
            name='action_taken',
            field=models.CharField(blank=True, help_text='Τι ενέργεια έγινε για το επείγον αίτημα', max_length=255),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='estimated_completion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='notes',
            field=models.TextField(blank=True, help_text='Σημειώσεις από διαχειριστές'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='priority',
            field=models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μέτρια'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Σε εκκρεμότητα'), ('in_progress', 'Σε εξέλιξη'), ('completed', 'Ολοκληρωμένο'), ('rejected', 'Απορρίφθηκε'), ('cancelled', 'Ακυρώθηκε')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='type',
            field=models.CharField(blank=True, choices=[('maintenance', 'Συντήρηση'), ('cleaning', 'Καθαριότητα'), ('technical', 'Τεχνικό'), ('security', 'Ασφάλεια'), ('noise', 'Θόρυβος'), ('other', 'Άλλο')], max_length=20),
        ),
    ]
