# Generated by Django 5.2.4 on 2025-07-31 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_requests', '0003_alter_urgentrequestlog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='apartment_number',
            field=models.CharField(blank=True, help_text='Apartment number if applicable', max_length=20),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='contractor_notes',
            field=models.TextField(blank=True, help_text='Notes from contractor'),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='cost_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='location',
            field=models.CharField(blank=True, help_text='Specific location in building', max_length=100),
        ),
        migrations.AddField(
            model_name='userrequest',
            name='photos',
            field=models.JSONField(blank=True, default=list, help_text='List of photo URLs'),
        ),
    ]
