# Generated by Django 5.2.4 on 2025-07-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Ανακοίνωση', 'verbose_name_plural': 'Ανακοινώσεις'},
        ),
        migrations.AddField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(default=0, help_text='Υψηλότερος αριθμός = υψηλότερη προτεραιότητα'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
