# Generated by Django 5.2.1 on 2025-05-23 20:13

import django.db.models.deletion  # type: ignore  # type: ignore  # type: ignore
from django.conf import settings  # type: ignore  # type: ignore  # type: ignore
from django.db import migrations, models  # type: ignore  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_announcements', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
