# Generated by Django 5.0.14 on 2025-07-25 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_alter_announcement_options_announcement_priority_and_more'),
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='building',
            field=models.ForeignKey(blank=True, help_text='Αφήστε κενό για ανακοίνωση σε όλα τα κτίρια', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='buildings.building'),
        ),
    ]
