# Generated by Django 5.2.7 on 2025-10-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_alter_announcement_building'),
        ('projects', '0006_alter_projectvote_offer_alter_projectvote_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Σύνδεση με έργο - διαγράφεται αυτόματα όταν διαγραφεί το έργο', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='projects.project'),
        ),
    ]
