# Generated by Django 5.2.7 on 2025-10-08 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0005_announcement_project'),
        ('projects', '0006_alter_projectvote_offer_alter_projectvote_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='projects',
            field=models.ManyToManyField(blank=True, help_text='Πολλαπλά έργα για ανακοινώσεις συνελεύσεων', related_name='assembly_announcements', to='projects.project'),
        ),
    ]
