# Generated by Django 5.x on 2025-12-24

import decimal
import uuid

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MarketplaceProvider",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255, verbose_name="Όνομα")),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("repair", "Επισκευές"),
                            ("cleaning", "Καθαριότητα"),
                            ("security", "Ασφάλεια"),
                            ("electrical", "Ηλεκτρολογικά"),
                            ("plumbing", "Υδραυλικά"),
                            ("heating", "Θέρμανση/Κλιματισμός"),
                            ("elevator", "Ανελκυστήρες"),
                            ("landscaping", "Κηπουρική"),
                            ("painting", "Βαψίματα"),
                            ("carpentry", "Ξυλουργική"),
                            ("masonry", "Κατασκευές"),
                            ("technical", "Τεχνικές Υπηρεσίες"),
                            ("maintenance", "Συντήρηση"),
                            ("emergency", "Επείγοντα"),
                            ("other", "Άλλο"),
                        ],
                        db_index=True,
                        max_length=30,
                        verbose_name="Κατηγορία",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργός")),
                ("show_in_marketplace", models.BooleanField(default=True, verbose_name="Εμφάνιση στο Marketplace")),
                ("is_verified", models.BooleanField(default=False, verbose_name="Επαληθευμένος")),
                ("is_featured", models.BooleanField(default=False, verbose_name="Προβεβλημένος")),
                (
                    "rating",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=3,
                        validators=[MinValueValidator(decimal.Decimal("0.00")), MaxValueValidator(decimal.Decimal("5.00"))],
                        verbose_name="Αξιολόγηση",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30, verbose_name="Τηλέφωνο")),
                ("email", models.EmailField(blank=True, default="", max_length=254, verbose_name="Email")),
                ("website", models.URLField(blank=True, default="", verbose_name="Ιστοσελίδα")),
                ("address", models.TextField(blank=True, default="", verbose_name="Διεύθυνση")),
                ("short_description", models.CharField(blank=True, default="", max_length=255, verbose_name="Σύντομη Περιγραφή")),
                ("detailed_description", models.TextField(blank=True, default="", verbose_name="Αναλυτική Περιγραφή")),
                ("special_offers", models.TextField(blank=True, default="", verbose_name="Ειδικές Προσφορές")),
                ("coupon_code", models.CharField(blank=True, default="", max_length=50, verbose_name="Κωδικός Έκπτωσης")),
                ("coupon_description", models.CharField(blank=True, default="", max_length=255, verbose_name="Περιγραφή Κουπονιού")),
                ("portfolio_links", models.JSONField(blank=True, default=list, verbose_name="Portfolio Links")),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Γεωγραφικό Πλάτος")),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name="Γεωγραφικό Μήκος")),
                (
                    "service_radius_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Προαιρετική ακτίνα εξυπηρέτησης. Αν είναι κενό, δεν φιλτράρει απόσταση.",
                        max_digits=6,
                        null=True,
                        verbose_name="Ακτίνα Εξυπηρέτησης (km)",
                    ),
                ),
                (
                    "is_nationwide",
                    models.BooleanField(
                        default=False,
                        help_text="Αν είναι ενεργό, αγνοεί φίλτρα μέγιστης απόστασης.",
                        verbose_name="Εξυπηρέτηση Πανελλαδικά",
                    ),
                ),
                (
                    "default_commission_rate_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[MinValueValidator(decimal.Decimal("0.00")), MaxValueValidator(decimal.Decimal("100.00"))],
                        verbose_name="Default Προμήθεια Πλατφόρμας (%)",
                    ),
                ),
                (
                    "stripe_account_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Για μελλοντικό Stripe Connect (προαιρετικό στο v1).",
                        max_length=255,
                        verbose_name="Stripe Connect Account ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace Provider",
                "verbose_name_plural": "Marketplace Providers",
                "ordering": ["-is_featured", "-is_verified", "-rating", "name"],
            },
        ),
        migrations.CreateModel(
            name="MarketplaceCommission",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tenant_schema", models.CharField(db_index=True, max_length=64, verbose_name="Tenant Schema")),
                ("building_id", models.IntegerField(blank=True, db_index=True, null=True, verbose_name="Building ID (tenant)")),
                ("project_id", models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Project ID (tenant)")),
                ("offer_id", models.UUIDField(blank=True, db_index=True, null=True, verbose_name="Offer ID (tenant)")),
                ("provider_id", models.UUIDField(db_index=True, verbose_name="Provider ID (public)")),
                (
                    "provider_name_snapshot",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Provider Name (snapshot)"),
                ),
                ("gross_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Μικτό Ποσό")),
                (
                    "commission_rate_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                        validators=[MinValueValidator(decimal.Decimal("0.00")), MaxValueValidator(decimal.Decimal("100.00"))],
                        verbose_name="Προμήθεια (%)",
                    ),
                ),
                ("commission_amount", models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name="Ποσό Προμήθειας")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("invoiced", "Invoiced"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace Commission",
                "verbose_name_plural": "Marketplace Commissions",
                "ordering": ["-created_at"],
                "unique_together": {("tenant_schema", "offer_id")},
            },
        ),
        migrations.AddIndex(
            model_name="marketplaceprovider",
            index=models.Index(fields=["service_type"], name="marketplace__service__6f8df8_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceprovider",
            index=models.Index(fields=["show_in_marketplace", "is_active"], name="marketplace__show_i__c9d6f8_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceprovider",
            index=models.Index(fields=["is_featured"], name="marketplace__is_fea__0b87ad_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceprovider",
            index=models.Index(fields=["rating"], name="marketplace__rating__7b3d8d_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplacecommission",
            index=models.Index(fields=["tenant_schema", "building_id"], name="marketplace__tenant__bldg__2d2b2f_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplacecommission",
            index=models.Index(fields=["tenant_schema", "project_id"], name="marketplace__tenant__proj__b1d3f7_idx"),
        ),
    ]


