# Generated by Django 5.2.8 on 2025-12-24 00:00

import decimal

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace_public", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceCommissionPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("repair", "Επισκευές"),
                            ("cleaning", "Καθαριότητα"),
                            ("security", "Ασφάλεια"),
                            ("electrical", "Ηλεκτρολογικά"),
                            ("plumbing", "Υδραυλικά"),
                            ("heating", "Θέρμανση/Κλιματισμός"),
                            ("elevator", "Ανελκυστήρες"),
                            ("landscaping", "Κηπουρική"),
                            ("painting", "Βαψίματα"),
                            ("carpentry", "Ξυλουργική"),
                            ("masonry", "Κατασκευές"),
                            ("technical", "Τεχνικές Υπηρεσίες"),
                            ("maintenance", "Συντήρηση"),
                            ("emergency", "Επείγοντα"),
                            ("other", "Άλλο"),
                        ],
                        db_index=True,
                        max_length=30,
                        unique=True,
                        verbose_name="Κατηγορία",
                    ),
                ),
                (
                    "base_commission_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=5,
                        validators=[MinValueValidator(decimal.Decimal("0.00")), MaxValueValidator(decimal.Decimal("100.00"))],
                        verbose_name="Base Προμήθεια (%)",
                    ),
                ),
                (
                    "featured_bonus_commission_rate_percent",
                    models.DecimalField(
                        decimal_places=2,
                        default=decimal.Decimal("0.00"),
                        max_digits=5,
                        validators=[MinValueValidator(decimal.Decimal("0.00")), MaxValueValidator(decimal.Decimal("100.00"))],
                        verbose_name="Featured Bonus (%)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Ενεργό")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace Commission Policy",
                "verbose_name_plural": "Marketplace Commission Policies",
                "ordering": ["service_type"],
            },
        ),
        migrations.AddField(
            model_name="marketplaceprovider",
            name="featured_bonus_commission_rate_percent_override",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Αν ο provider είναι featured, αυτό το bonus υπερισχύει του featured bonus της κατηγορίας.",
                max_digits=5,
                null=True,
                validators=[MinValueValidator(decimal.Decimal("0.00")), MaxValueValidator(decimal.Decimal("100.00"))],
                verbose_name="Override Featured Bonus (%)",
            ),
        ),
    ]


