# Generated by Django 5.2.8 on 2025-12-24 00:00

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace_public", "0002_commission_policy_and_featured_bonus_override"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketplaceOfferRequest",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("token", models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ("tenant_schema", models.CharField(db_index=True, max_length=64)),
                ("tenant_host", models.CharField(blank=True, default="", help_text="π.χ. theo.newconcierge.app", max_length=255)),
                ("building_id", models.IntegerField(blank=True, db_index=True, null=True)),
                ("project_id", models.UUIDField(db_index=True)),
                ("provider_id", models.UUIDField(db_index=True)),
                ("provider_name_snapshot", models.CharField(blank=True, default="", max_length=255)),
                ("provider_email_snapshot", models.EmailField(blank=True, default="", max_length=254)),
                ("provider_phone_snapshot", models.CharField(blank=True, default="", max_length=30)),
                ("project_title_snapshot", models.CharField(blank=True, default="", max_length=255)),
                ("project_description_snapshot", models.TextField(blank=True, default="")),
                ("requested_by_user_id", models.IntegerField(blank=True, null=True)),
                ("requested_by_email_snapshot", models.EmailField(blank=True, default="", max_length=254)),
                ("message_to_provider", models.TextField(blank=True, default="")),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("opened", "Opened"), ("submitted", "Submitted"), ("cancelled", "Cancelled")],
                        db_index=True,
                        default="sent",
                        max_length=20,
                    ),
                ),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_offer_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Marketplace Offer Request",
                "verbose_name_plural": "Marketplace Offer Requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="marketplaceofferrequest",
            index=models.Index(fields=["tenant_schema", "project_id"], name="marketplace__tenant__e3ce41_idx"),
        ),
        migrations.AddIndex(
            model_name="marketplaceofferrequest",
            index=models.Index(fields=["tenant_schema", "building_id"], name="marketplace__tenant__1b4a62_idx"),
        ),
    ]


