# Generated by Django 5.0.14 on 2025-06-03 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Όνομα')),
                ('address', models.CharField(max_length=255, verbose_name='Διεύθυνση')),
                ('city', models.CharField(max_length=100, verbose_name='Πόλη')),
                ('postal_code', models.CharField(max_length=10, verbose_name='Τ.Κ.')),
                ('apartments_count', models.PositiveIntegerField(default=0, verbose_name='Σύνολο Διαμερισμάτων')),
                ('internal_manager_name', models.CharField(blank=True, max_length=255)),
                ('internal_manager_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(blank=True, max_length=10)),
                ('role', models.CharField(choices=[('resident', 'Κάτοικος'), ('representative', 'Εκπρόσωπος')], default='resident', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
