# Generated by Django 5.2.4 on 2025-07-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='street_view_image',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Εικόνα Street View'),
        ),
    ]
