# Generated by Django 5.2.1 on 2025-05-24 19:23

import django.db.models.deletion  # type: ignore  # type: ignore
from django.conf import settings  # type: ignore  # type: ignore
from django.db import migrations, models  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0002_alter_building_manager'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='address',
            field=models.CharField(max_length=255, verbose_name='Διεύθυνση'),
        ),
        migrations.AlterField(
            model_name='building',
            name='apartments_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Σύνολο Διαμερισμάτων'),
        ),
        migrations.AlterField(
            model_name='building',
            name='city',
            field=models.CharField(max_length=100, verbose_name='Πόλη'),
        ),
        migrations.AlterField(
            model_name='building',
            name='internal_manager_name',
            field=models.CharField(blank=True, default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='internal_manager_phone',
            field=models.CharField(blank=True, default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_buildings', to=settings.AUTH_USER_MODEL, verbose_name='Διαχειριστής'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Όνομα'),
        ),
        migrations.AlterField(
            model_name='building',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='Τ.Κ.'),
        ),
    ]
