# Generated by Django 5.2.4 on 2025-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_building_street_view_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Γεωγραφικό πλάτος (latitude) από Google Maps', max_digits=9, null=True, verbose_name='Γεωγραφικό Πλάτος'),
        ),
        migrations.AddField(
            model_name='building',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Γεωγραφικό μήκος (longitude) από Google Maps', max_digits=9, null=True, verbose_name='Γεωγραφικό Μήκος'),
        ),
    ]
