# Generated by Django 5.2.1 on 2025-05-25 16:48

import django.db.models.deletion  # type: ignore  # type: ignore  # type: ignore
from django.conf import settings  # type: ignore  # type: ignore  # type: ignore
from django.db import migrations, models  # type: ignore  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0003_alter_building_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartment', models.CharField(blank=True, max_length=10)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='buildings.building')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('building', 'resident')},
            },
        ),
    ]
