# Generated by Django 5.0.14 on 2025-07-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_building_latitude_building_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='management_office_address',
            field=models.CharField(blank=True, help_text='Διεύθυνση του γραφείου διαχείρισης', max_length=255, verbose_name='Διεύθυνση Γραφείου Διαχείρισης'),
        ),
        migrations.AddField(
            model_name='building',
            name='management_office_name',
            field=models.CharField(blank=True, help_text='Όνομα της εταιρείας/γραφείου διαχείρισης', max_length=255, verbose_name='Όνομα Γραφείου Διαχείρισης'),
        ),
        migrations.AddField(
            model_name='building',
            name='management_office_phone',
            field=models.CharField(blank=True, help_text='Τηλέφωνο επικοινωνίας με το γραφείο διαχείρισης', max_length=20, verbose_name='Τηλέφωνο Γραφείου Διαχείρισης'),
        ),
    ]
