# Generated by Django 5.2.1 on 2025-05-26 01:08

import django.utils.timezone  # type: ignore  # type: ignore
from django.db import migrations, models  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0004_buildingmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingmembership',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='buildingmembership',
            name='role',
            field=models.CharField(choices=[('resident', 'Κάτοικος'), ('representative', 'Εκπρόσωπος')], default='resident', max_length=20),
        ),
    ]
