# Generated by Django 5.2.4 on 2025-08-03 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0005_building_management_office_address_and_more'),
    ]

    operations = [
    ]
