# Generated by Django 5.2.4 on 2025-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0006_auto_20250803_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='current_reserve',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Τρέχον αποθεματικό του κτιρίου σε ευρώ', max_digits=10, verbose_name='Τρέχον Αποθεματικό'),
        ),
    ]
