# Generated by Django 5.2.5 on 2025-08-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_building_current_reserve'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='heating_fixed_percentage',
            field=models.DecimalField(decimal_places=2, default=30.0, help_text='Ποσοστό παγίου κόστους θέρμανσης (π.χ. 30% = 30.00)', max_digits=5, verbose_name='Ποσοστό Παγίου Θέρμανσης'),
        ),
        migrations.AddField(
            model_name='building',
            name='reserve_contribution_per_apartment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Πάγια εισφορά αποθεματικού ανά διαμέρισμα σε ευρώ', max_digits=6, verbose_name='Πάγια Εισφορά Αποθεματικού ανά Διαμέρισμα'),
        ),
    ]
