# Generated by Django 5.2.5 on 2025-08-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0008_building_heating_fixed_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='management_fee_per_apartment',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Μηνιαία αμοιβή διαχείρισης ανά διαμέρισμα σε ευρώ', max_digits=6, verbose_name='Αμοιβή Διαχείρισης ανά Διαμέρισμα'),
        ),
    ]
