# Generated by Django 5.2.5 on 2025-08-14 00:02

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0009_building_management_fee_per_apartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Πακέτου')),
                ('description', models.TextField(verbose_name='Περιγραφή Υπηρεσιών')),
                ('fee_per_apartment', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Αμοιβή ανά Διαμέρισμα (€)')),
                ('services_included', models.JSONField(default=list, verbose_name='Υπηρεσίες που Περιλαμβάνονται')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Πακέτο Υπηρεσιών',
                'verbose_name_plural': 'Πακέτα Υπηρεσιών',
                'ordering': ['fee_per_apartment'],
            },
        ),
        migrations.AlterField(
            model_name='building',
            name='management_fee_per_apartment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Αμοιβή διαχείρισης ανά διαμέρισμα σε ευρώ', max_digits=8, verbose_name='Αμοιβή Διαχείρισης ανά Διαμέρισμα'),
        ),
        migrations.AddField(
            model_name='building',
            name='service_package',
            field=models.ForeignKey(blank=True, help_text='Επιλεγμένο πακέτο υπηρεσιών διαχείρισης', null=True, on_delete=django.db.models.deletion.SET_NULL, to='buildings.servicepackage', verbose_name='Πακέτο Υπηρεσιών'),
        ),
    ]
