# Generated by Django 5.2.5 on 2025-08-16 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0010_servicepackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='reserve_fund_duration_months',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Διάρκεια συλλογής αποθεματικού σε μήνες', null=True, verbose_name='Διάρκεια Συλλογής (μήνες)'),
        ),
        migrations.AddField(
            model_name='building',
            name='reserve_fund_goal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Στόχος αποθεματικού σε ευρώ', max_digits=10, null=True, verbose_name='Στόχος Αποθεματικού'),
        ),
        migrations.AddField(
            model_name='building',
            name='reserve_fund_start_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία έναρξης συλλογής αποθεματικού', null=True, verbose_name='Ημερομηνία Έναρξης Συλλογής'),
        ),
        migrations.AddField(
            model_name='building',
            name='reserve_fund_target_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία ολοκλήρωσης του στόχου αποθεματικού', null=True, verbose_name='Ημερομηνία Ολοκλήρωσης Στόχου'),
        ),
    ]
