# Generated by Django 5.2.5 on 2025-01-27 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0011_building_reserve_fund_duration_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='grace_day_of_month',
            field=models.PositiveSmallIntegerField(
                default=15,
                help_text='Ημέρα του μήνα μετά την οποία οι οφειλές θεωρούνται καθυστερημένες',
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name='Ημέρα Έναρξης Καθυστέρησης'
            ),
        ),
    ]
