# Generated by Django 5.2.5 on 2025-08-30 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0012_building_grace_day_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='internal_manager_apartment',
            field=models.CharField(blank=True, help_text='Αριθμός διαμερίσματος του εσωτερικού διαχειριστή', max_length=10, verbose_name='Διαμέρισμα Εσωτερικού Διαχειριστή'),
        ),
        migrations.AddField(
            model_name='building',
            name='internal_manager_collection_schedule',
            field=models.CharField(blank=True, default='Δευ-Παρ 9:00-17:00', help_text='Ημέρες και ώρες είσπραξης κοινοχρήστων από τον εσωτερικό διαχειριστή', max_length=255, verbose_name='Ωράριο Είσπραξης Κοινοχρήστων'),
        ),
        migrations.AlterField(
            model_name='building',
            name='internal_manager_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Όνομα Εσωτερικού Διαχειριστή'),
        ),
        migrations.AlterField(
            model_name='building',
            name='internal_manager_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Εσωτερικού Διαχειριστή'),
        ),
    ]
