# Generated by Django 5.2.5 on 2025-08-31 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0013_building_internal_manager_apartment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='reserve_contribution_per_apartment',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Πάγια εισφορά αποθεματικού ανά διαμέρισμα σε ευρώ', max_digits=6, verbose_name='Πάγια Εισφορά Αποθεματικού ανά Διαμέρισμα'),
        ),
    ]
