# Generated by Django 5.2.5 on 2025-09-03 04:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0014_fix_reserve_fund_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='grace_day_of_month',
            field=models.PositiveSmallIntegerField(default=15, help_text='Ημέρα του μήνα μετά την οποία οι οφειλές θεωρούνται καθυστερημένες', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ημέρα Έναρξης Οφειλής'),
        ),
    ]
