# Generated by Django 5.2.6 on 2025-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_alter_building_grace_day_of_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='google_calendar_enabled',
            field=models.BooleanField(default=False, help_text='Ενεργοποίηση του Google Calendar για αυτό το κτίριο', verbose_name='Google Calendar Ενεργό'),
        ),
        migrations.AddField(
            model_name='building',
            name='google_calendar_id',
            field=models.CharField(blank=True, help_text='ID του Google Calendar για αυτό το κτίριο', max_length=255, null=True, verbose_name='Google Calendar ID'),
        ),
        migrations.AddField(
            model_name='building',
            name='google_calendar_sync_enabled',
            field=models.BooleanField(default=True, help_text='Αυτόματος συγχρονισμός events με Google Calendar', verbose_name='Αυτόματος Συγχρονισμός'),
        ),
    ]
