# Generated by Django 5.2.6 on 2025-09-12 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0016_building_google_calendar_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='heating_system',
            field=models.CharField(choices=[('none', 'Χωρίς Κεντρική Θέρμανση'), ('conventional', 'Συμβατικό (Κατανομή με χιλιοστά)'), ('hour_meters', 'Αυτονομία με Ωρομετρητές'), ('heat_meters', 'Αυτονομία με Θερμιδομετρητές')], default='none', help_text='Επιλέξτε τον τρόπο κατανομής των δαπανών θέρμανσης.', max_length=20, verbose_name='Σύστημα Θέρμανσης'),
        ),
        migrations.AlterField(
            model_name='building',
            name='heating_fixed_percentage',
            field=models.PositiveIntegerField(default=30, help_text='Το ποσοστό της δαπάνης που κατανέμεται ως πάγιο (π.χ. 30%). Εφαρμόζεται μόνο σε συστήματα με αυτονομία.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ποσοστό Παγίου Θέρμανσης (%)'),
        ),
    ]
