# Generated by Django 5.2.6 on 2025-09-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_add_heating_system_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='service_package_start_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία έναρξης ισχύος του πακέτου υπηρεσιών', null=True, verbose_name='Ημερομηνία Έναρξης Πακέτου'),
        ),
    ]
