# Generated by Django 5.2.6 on 2025-09-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0019_add_reserve_fund_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='financial_system_start_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία έναρξης χρήσης του οικονομικού συστήματος. Αν δεν οριστεί, χρησιμοποιείται η 1η Ιανουαρίου του έτους.', null=True, verbose_name='Ημερομηνία Έναρξης Συστήματος'),
        ),
    ]
