# Generated by Django 5.2.6 on 2025-09-24 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0020_add_financial_system_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='reserve_fund_priority',
            field=models.CharField(choices=[('after_obligations', 'Μετά τις Εκκρεμότητες'), ('always', 'Πάντα (Ανεξάρτητα)')], default='always', help_text='Πότε να συλλέγεται το αποθεματικό: μετά τις εκκρεμότητες ή πάντα', max_length=20, verbose_name='Προτεραιότητα Συλλογής Αποθεματικού'),
        ),
    ]
