# Generated by Django 5.2.7 on 2025-10-08 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_building_reserve_fund_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='grace_day_of_month',
            field=models.PositiveSmallIntegerField(default=1, help_text='Ημέρα του μήνα μετά την οποία οι οφειλές θεωρούνται καθυστερημένες', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ημέρα Έναρξης Οφειλής'),
        ),
    ]
