# Generated by Django 5.2.7 on 2025-10-09 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0022_alter_building_grace_day_of_month'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='reserve_fund_priority',
        ),
    ]
