# Generated by Django 5.2.7 on 2025-10-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0023_remove_reserve_fund_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='manager',
        ),
        migrations.AddField(
            model_name='building',
            name='manager_id',
            field=models.IntegerField(blank=True, help_text='ID του χρήστη-διαχειριστή από το public schema', null=True, verbose_name='Διαχειριστής (User ID από Public Schema)'),
        ),
    ]
