# Generated by Django 5.2.8 on 2025-11-20 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0024_change_manager_to_manager_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='financial_system_start_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία έναρξης χρήσης του οικονομικού συστήματος. Αν αφεθεί κενό, υπολογίζεται αυτόματα η 1η του μήνα που δημιουργήθηκε το κτίριο. Αν οριστεί, χρησιμοποιείται πάντα η 1η του μήνα της εισαγμένης ημερομηνίας.', null=True, verbose_name='Ημερομηνία Έναρξης Συστήματος'),
        ),
    ]
