# Generated by Django 5.2.8 on 2025-11-25 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0025_alter_building_financial_system_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buildingmembership',
            options={'verbose_name': 'Μέλος Πολυκατοικίας', 'verbose_name_plural': 'Μέλη Πολυκατοικίας'},
        ),
        migrations.AddField(
            model_name='building',
            name='internal_manager',
            field=models.ForeignKey(blank=True, help_text='Ο χρήστης που είναι εσωτερικός διαχειριστής της πολυκατοικίας', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_buildings_internal', to=settings.AUTH_USER_MODEL, verbose_name='Εσωτερικός Διαχειριστής'),
        ),
        migrations.AddField(
            model_name='building',
            name='internal_manager_can_record_payments',
            field=models.BooleanField(default=False, help_text='Αν ο εσωτερικός διαχειριστής μπορεί να καταχωρεί πληρωμές', verbose_name='Δικαίωμα Καταχώρησης Πληρωμών'),
        ),
        migrations.AlterField(
            model_name='building',
            name='internal_manager_name',
            field=models.CharField(blank=True, help_text='Πληροφοριακό πεδίο - χρησιμοποιείται αν δεν υπάρχει συνδεδεμένος χρήστης', max_length=255, verbose_name='Όνομα Εσωτερικού Διαχειριστή'),
        ),
        migrations.AlterField(
            model_name='buildingmembership',
            name='role',
            field=models.CharField(choices=[('resident', 'Κάτοικος'), ('representative', 'Εκπρόσωπος'), ('internal_manager', 'Εσωτερικός Διαχειριστής')], default='resident', max_length=20),
        ),
    ]
