# Generated by Django 5.2.x on 2025-12-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0026_internal_manager_framework'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='premium_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Αν είναι ενεργό, το συγκεκριμένο κτίριο έχει πρόσβαση σε Premium λειτουργίες (Kiosk + AI).',
                verbose_name='Premium Ενεργό (Kiosk + AI)',
            ),
        ),
    ]


