# Generated by Django 5.2.x on 2026-01-04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0027_building_premium_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='iot_enabled',
            field=models.BooleanField(
                default=False,
                help_text='Αν είναι ενεργό, το συγκεκριμένο κτίριο έχει πρόσβαση σε Premium + IoT λειτουργίες (Smart Heating).',
                verbose_name='Premium + IoT Ενεργό (Smart Heating)',
            ),
        ),
    ]

