# Generated by Codex

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0028_building_iot_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='trial_ends_at',
            field=models.DateField(
                blank=True,
                help_text='Λήξη trial ανά πολυκατοικία (default: +14 ημέρες)',
                null=True,
                verbose_name='Λήξη Trial',
            ),
        ),
    ]
