# Generated by Django 5.2.4 on 2025-07-26 02:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(help_text='π.χ. Α1, Β2, 101, κλπ', max_length=10, verbose_name='Αριθμός Διαμερίσματος')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Όροφος')),
                ('owner_name', models.CharField(blank=True, max_length=255, verbose_name='Όνομα Ιδιοκτήτη')),
                ('owner_phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Ιδιοκτήτη')),
                ('owner_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Ιδιοκτήτη')),
                ('ownership_percentage', models.DecimalField(blank=True, decimal_places=3, help_text='Ποσοστό ιδιοκτησίας σε χιλιοστά', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Χιλιοστά Ιδιοκτησίας (%)')),
                ('tenant_name', models.CharField(blank=True, max_length=255, verbose_name='Όνομα Ενοίκου')),
                ('tenant_phone', models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο Ενοίκου')),
                ('tenant_email', models.EmailField(blank=True, max_length=254, verbose_name='Email Ενοίκου')),
                ('is_rented', models.BooleanField(default=False, verbose_name='Είναι Ενοικιασμένο')),
                ('rent_start_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έναρξης Ενοικίασης')),
                ('rent_end_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης Ενοικίασης')),
                ('square_meters', models.PositiveIntegerField(blank=True, null=True, verbose_name='Τετραγωνικά Μέτρα')),
                ('bedrooms', models.PositiveIntegerField(blank=True, null=True, verbose_name='Υπνοδωμάτια')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='buildings.building', verbose_name='Κτίριο')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_apartments', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης Ιδιοκτήτης')),
                ('tenant_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rented_apartments', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης Ενοίκου')),
            ],
            options={
                'verbose_name': 'Διαμέρισμα',
                'verbose_name_plural': 'Διαμερίσματα',
                'ordering': ['building', 'number'],
                'unique_together': {('building', 'number')},
            },
        ),
    ]
