# Generated by Django 5.2.4 on 2025-07-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='owner_phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Δεύτερο Τηλέφωνο Ιδιοκτήτη'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='tenant_phone2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Δεύτερο Τηλέφωνο Ενοίκου'),
        ),
    ]
