# Generated by Django 5.2.4 on 2025-07-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Διαμέρισμα με ιδιοκτήτη που δεν κατοικείται', verbose_name='Είναι Κλειστό/Μη Κατοικημένο'),
        ),
    ]
