# Generated by Django 5.2.4 on 2025-08-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_apartment_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Τρέχον υπόλοιπο διαμερίσματος (+ = πιστωτικό, - = οφειλή)', max_digits=10, verbose_name='Τρέχον Υπόλοιπο'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='participation_mills',
            field=models.PositiveIntegerField(blank=True, help_text='Χιλιοστά συμμετοχής για κατανομή δαπανών', null=True, verbose_name='Χιλιοστά Συμμετοχής'),
        ),
    ]
