# Generated by Django 5.2.5 on 2025-08-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_current_balance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='elevator_mills',
            field=models.PositiveIntegerField(blank=True, help_text='Χιλιοστά συμμετοχής για δαπάνες ανελκυστήρα', null=True, verbose_name='Χιλιοστά Ανελκυστήρα'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='heating_mills',
            field=models.PositiveIntegerField(blank=True, help_text='Χιλιοστά συμμετοχής για δαπάνες θέρμανσης', null=True, verbose_name='Χιλιοστά Θέρμανσης'),
        ),
    ]
