# Generated by Django 5.2.5 on 2025-08-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_apartment_elevator_mills_apartment_heating_mills'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='general_expenses_mills',
            field=models.PositiveIntegerField(blank=True, help_text='Χιλιοστά συμμετοχής για γενικές δαπάνες κτιρίου', null=True, verbose_name='Χιλιοστά Γενικών Δαπανών'),
        ),
    ]
