# Generated by Django 5.2.4 on 2025-08-08 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_apartment_general_expenses_mills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='general_expenses_mills',
        ),
    ]
