# Generated by Django 5.2.5 on 2025-08-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_remove_apartment_general_expenses_mills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='identifier',
            field=models.CharField(blank=True, help_text='π.χ. ΙΣ2, Α1, Β4', max_length=20, verbose_name='Διακριτικό Διαμερίσματος'),
        ),
    ]
