# Generated by Django 5.2.5 on 2025-09-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0009_alter_apartment_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Υπόλοιπο προηγούμενων μηνών (+ = πιστωτικό, - = οφειλή)', max_digits=10, verbose_name='Προηγούμενο Υπόλοιπο'),
        ),
    ]
