# Generated by Django 5.2.6 on 2025-09-26 16:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0021_alter_building_reserve_fund_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskWidgetConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.JSONField(default=dict, help_text='JSON configuration for kiosk widgets and settings')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kiosk_configs', to='buildings.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_kiosk_configs', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_kiosk_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Kiosk Widget Configuration',
                'verbose_name_plural': 'Kiosk Widget Configurations',
                'unique_together': {('building',)},
            },
        ),
    ]
