# Generated by Django 5.2.6 on 2025-09-27 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_building_reserve_fund_priority'),
        ('kiosk', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KioskDisplaySettings',
            fields=[
                ('building', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='buildings.building')),
                ('slide_duration', models.IntegerField(default=10000)),
                ('auto_slide', models.BooleanField(default=True)),
                ('show_navigation', models.BooleanField(default=True)),
                ('background_image', models.CharField(blank=True, max_length=200)),
                ('theme', models.CharField(default='default', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kiosk_display_configs',
            },
        ),
        migrations.CreateModel(
            name='KioskWidget',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('widget_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('greek_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('greek_description', models.TextField(blank=True)),
                ('category', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('settings', models.JSONField(default=dict)),
                ('component', models.CharField(max_length=100)),
                ('data_source', models.CharField(blank=True, max_length=200)),
                ('is_custom', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kiosk_widget_configs',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='KioskWidgetConfig',
        ),
        migrations.AddIndex(
            model_name='kioskwidget',
            index=models.Index(fields=['widget_id'], name='kiosk_widge_widget__129fa6_idx'),
        ),
        migrations.AddIndex(
            model_name='kioskwidget',
            index=models.Index(fields=['building', 'enabled'], name='kiosk_widge_buildin_facd04_idx'),
        ),
        migrations.AddIndex(
            model_name='kioskwidget',
            index=models.Index(fields=['category'], name='kiosk_widge_categor_5bf9dd_idx'),
        ),
    ]
