# Generated by Django 5.2.7 on 2025-10-12 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0003_kioskscene_widgetplacement'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='kioskscene',
            new_name='kiosk_scene_buildin_000d6a_idx',
            old_name='kiosk_scene_building_enabled_idx',
        ),
        migrations.RenameIndex(
            model_name='kioskscene',
            new_name='kiosk_scene_order_a20980_idx',
            old_name='kiosk_scene_order_idx',
        ),
        migrations.RenameIndex(
            model_name='widgetplacement',
            new_name='kiosk_widge_scene_i_f85631_idx',
            old_name='kiosk_widge_scene_i_idx',
        ),
    ]
