# Generated by Django 5.2.8 on 2025-11-29 21:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0026_internal_manager_framework'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Κατηγορίας')),
                ('category_type', models.CharField(choices=[('platform', 'Πλατφόρμα & Λογισμικό'), ('staff', 'Προσωπικό'), ('utilities', 'Λειτουργικά Έξοδα'), ('equipment', 'Εξοπλισμός'), ('professional', 'Επαγγελματικές Υπηρεσίες'), ('marketing', 'Marketing & Διαφήμιση'), ('rent', 'Ενοίκιο Γραφείου'), ('insurance', 'Ασφάλειες'), ('taxes', 'Φόροι & Τέλη'), ('other', 'Λοιπά Έξοδα')], default='other', max_length=20, verbose_name='Τύπος Κατηγορίας')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Εικονίδιο')),
                ('color', models.CharField(default='slate', max_length=20, verbose_name='Χρώμα')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('is_system', models.BooleanField(default=False, verbose_name='Κατηγορία Συστήματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Κατηγορία Εξόδων Γραφείου',
                'verbose_name_plural': 'Κατηγορίες Εξόδων Γραφείου',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeIncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Κατηγορίας')),
                ('category_type', models.CharField(choices=[('management_fee', 'Αμοιβές Διαχείρισης'), ('extra_services', 'Έκτακτες Υπηρεσίες'), ('commissions', 'Προμήθειες'), ('consulting', 'Συμβουλευτικές Υπηρεσίες'), ('other', 'Λοιπά Έσοδα')], default='other', max_length=20, verbose_name='Τύπος Κατηγορίας')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Εικονίδιο')),
                ('color', models.CharField(default='emerald', max_length=20, verbose_name='Χρώμα')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('is_system', models.BooleanField(default=False, verbose_name='Κατηγορία Συστήματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Κατηγορία Εσόδων Γραφείου',
                'verbose_name_plural': 'Κατηγορίες Εσόδων Γραφείου',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeFinancialSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Έτος')),
                ('month', models.PositiveIntegerField(verbose_name='Μήνας')),
                ('total_income', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Συνολικά Έσοδα')),
                ('total_expenses', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Συνολικά Έξοδα')),
                ('net_result', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Καθαρό Αποτέλεσμα')),
                ('income_by_category', models.JSONField(default=dict, verbose_name='Έσοδα ανά Κατηγορία')),
                ('expenses_by_category', models.JSONField(default=dict, verbose_name='Έξοδα ανά Κατηγορία')),
                ('income_by_building', models.JSONField(default=dict, verbose_name='Έσοδα ανά Κτίριο')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Κλειστός Μήνας')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Κλεισίματος')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Μηνιαία Σύνοψη Γραφείου',
                'verbose_name_plural': 'Μηνιαίες Συνόψεις Γραφείου',
                'ordering': ['-year', '-month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='OfficeExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ποσό (€)')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('payment_method', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('card', 'Κάρτα'), ('check', 'Επιταγή'), ('direct_debit', 'Πάγια Εντολή'), ('other', 'Άλλο')], default='bank_transfer', max_length=20, verbose_name='Τρόπος Πληρωμής')),
                ('is_paid', models.BooleanField(default=True, verbose_name='Πληρώθηκε')),
                ('paid_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('recurrence', models.CharField(choices=[('once', 'Εφάπαξ'), ('monthly', 'Μηνιαίο'), ('quarterly', 'Τριμηνιαίο'), ('yearly', 'Ετήσιο')], default='once', max_length=20, verbose_name='Επανάληψη')),
                ('supplier_name', models.CharField(blank=True, max_length=255, verbose_name='Προμηθευτής')),
                ('supplier_vat', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ Προμηθευτή')),
                ('document', models.FileField(blank=True, null=True, upload_to='office_expenses/%Y/%m/', verbose_name='Παραστατικό')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Παραστατικού')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_expenses', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='office_finance.officeexpensecategory', verbose_name='Κατηγορία')),
            ],
            options={
                'verbose_name': 'Έξοδο Γραφείου',
                'verbose_name_plural': 'Έξοδα Γραφείου',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='office_fina_date_e29d25_idx'), models.Index(fields=['category'], name='office_fina_categor_6214c9_idx'), models.Index(fields=['-date', 'category'], name='office_fina_date_3691cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='OfficeIncome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Ποσό (€)')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('received', 'Εισπράχθηκε'), ('cancelled', 'Ακυρώθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('card', 'Κάρτα'), ('check', 'Επιταγή'), ('direct_debit', 'Πάγια Εντολή'), ('other', 'Άλλο')], max_length=20, verbose_name='Τρόπος Είσπραξης')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Είσπραξης')),
                ('recurrence', models.CharField(choices=[('once', 'Εφάπαξ'), ('monthly', 'Μηνιαίο'), ('quarterly', 'Τριμηνιαίο'), ('yearly', 'Ετήσιο')], default='once', max_length=20, verbose_name='Επανάληψη')),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='Πελάτης')),
                ('client_vat', models.CharField(blank=True, max_length=20, verbose_name='ΑΦΜ Πελάτη')),
                ('document', models.FileField(blank=True, null=True, upload_to='office_income/%Y/%m/', verbose_name='Παραστατικό')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Τιμολογίου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(blank=True, help_text='Συνδέστε με κτίριο αν είναι αμοιβή διαχείρισης', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_incomes', to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_office_incomes', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomes', to='office_finance.officeincomecategory', verbose_name='Κατηγορία')),
            ],
            options={
                'verbose_name': 'Έσοδο Γραφείου',
                'verbose_name_plural': 'Έσοδα Γραφείου',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='office_fina_date_c309ad_idx'), models.Index(fields=['category'], name='office_fina_categor_0b63e1_idx'), models.Index(fields=['building'], name='office_fina_buildin_346141_idx'), models.Index(fields=['status'], name='office_fina_status_8c8ce0_idx'), models.Index(fields=['-date', 'category'], name='office_fina_date_5e9abe_idx')],
            },
        ),
    ]
