# Generated by Django 5.2.4 on 2025-08-06 06:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0007_building_current_reserve'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Όνομα Ρόλου')),
                ('role_type', models.CharField(choices=[('leader', 'Ηγέτης'), ('member', 'Μέλος'), ('specialist', 'Ειδικός'), ('assistant', 'Βοηθός'), ('trainee', 'Εκπαιδευόμενος')], max_length=20, verbose_name='Τύπος Ρόλου')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('permissions', models.JSONField(default=dict, help_text='JSON object με τα δικαιώματα του ρόλου', verbose_name='Δικαιώματα')),
                ('is_default', models.BooleanField(default=False, verbose_name='Προεπιλεγμένος Ρόλος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ρόλος Ομάδας',
                'verbose_name_plural': 'Ρόλοι Ομάδων',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Όνομα Ομάδας')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('team_type', models.CharField(choices=[('management', 'Διαχείριση'), ('maintenance', 'Συντήρηση'), ('cleaning', 'Καθαριότητα'), ('security', 'Ασφάλεια'), ('technical', 'Τεχνική Υποστήριξη'), ('administrative', 'Διοικητική Υποστήριξη'), ('project', 'Έργα'), ('emergency', 'Επείγοντα'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Ομάδας')),
                ('status', models.CharField(choices=[('active', 'Ενεργή'), ('inactive', 'Ανενεργή'), ('suspended', 'Ανασταλμένη')], default='active', max_length=20, verbose_name='Κατάσταση')),
                ('max_members', models.PositiveIntegerField(default=10, verbose_name='Μέγιστος Αριθμός Μελών')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='buildings.building', verbose_name='Κτίριο')),
                ('leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL, verbose_name='Ηγέτης Ομάδας')),
            ],
            options={
                'verbose_name': 'Ομάδα',
                'verbose_name_plural': 'Ομάδες',
                'ordering': ['name'],
                'unique_together': {('building', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TeamMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Συνάντησης')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('meeting_type', models.CharField(choices=[('regular', 'Τακτική'), ('emergency', 'Επείγουσα'), ('planning', 'Σχεδιασμού'), ('review', 'Ανασκόπησης'), ('training', 'Εκπαίδευσης')], default='regular', max_length=20, verbose_name='Τύπος Συνάντησης')),
                ('scheduled_at', models.DateTimeField(verbose_name='Προγραμματισμένη Ώρα')),
                ('duration', models.PositiveIntegerField(default=60, verbose_name='Διάρκεια (λεπτά)')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Τοποθεσία')),
                ('is_online', models.BooleanField(default=False, verbose_name='Διαδικτυακή')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Σύνδεσμος Συνάντησης')),
                ('agenda', models.TextField(blank=True, verbose_name='Ημερήσια Διάταξη')),
                ('minutes', models.TextField(blank=True, verbose_name='Πρακτικά')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_meetings', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='teams.team', verbose_name='Ομάδα')),
            ],
            options={
                'verbose_name': 'Συνάντηση Ομάδας',
                'verbose_name_plural': 'Συναντήσεις Ομάδων',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Ενεργό'), ('inactive', 'Ανενεργό'), ('suspended', 'Ανασταλμένο'), ('left', 'Αποχώρησε')], default='active', max_length=20, verbose_name='Κατάσταση')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία Ένταξης')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Αποχώρησης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργό')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team', verbose_name='Ομάδα')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to='teams.teamrole', verbose_name='Ρόλος')),
            ],
            options={
                'verbose_name': 'Μέλος Ομάδας',
                'verbose_name_plural': 'Μέλη Ομάδων',
                'ordering': ['-joined_at'],
                'unique_together': {('team', 'user')},
            },
        ),
        migrations.CreateModel(
            name='TeamTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Εργασίας')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('priority', models.CharField(choices=[('low', 'Χαμηλή'), ('medium', 'Μέτρια'), ('high', 'Υψηλή'), ('urgent', 'Επείγουσα')], default='medium', max_length=20, verbose_name='Προτεραιότητα')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('in_progress', 'Σε Εξέλιξη'), ('completed', 'Ολοκληρώθηκε'), ('cancelled', 'Ακυρώθηκε')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ολοκλήρωσης')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Εκτιμώμενες Ώρες')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Πραγματικές Ώρες')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='teams.teammember', verbose_name='Ανατέθηκε σε')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_team_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='teams.team', verbose_name='Ομάδα')),
            ],
            options={
                'verbose_name': 'Εργασία Ομάδας',
                'verbose_name_plural': 'Εργασίες Ομάδων',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField(verbose_name='Έναρξη Περιόδου')),
                ('period_end', models.DateField(verbose_name='Λήξη Περιόδου')),
                ('tasks_completed', models.PositiveIntegerField(default=0, verbose_name='Ολοκληρωμένες Εργασίες')),
                ('tasks_total', models.PositiveIntegerField(default=0, verbose_name='Συνολικές Εργασίες')),
                ('average_completion_time', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Μέσος Χρόνος Ολοκλήρωσης (ώρες)')),
                ('satisfaction_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Αξιολόγηση Ικανοποίησης')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_records', to='teams.team', verbose_name='Ομάδα')),
            ],
            options={
                'verbose_name': 'Απόδοση Ομάδας',
                'verbose_name_plural': 'Αποδόσεις Ομάδων',
                'ordering': ['-period_end'],
                'unique_together': {('team', 'period_start', 'period_end')},
            },
        ),
    ]
