#!/usr/bin/env python3
"""
🔍 Script για έλεγχο hardcoded ετών στον κώδικα
"""

import os
import sys
import re
from pathlib import Path

def find_hardcoded_years(directory):
    """Βρίσκει hardcoded έτη στον κώδικα"""
    
    current_year = 2025  # Τρέχον έτος
    next_year = 2026
    
    hardcoded_files = []
    
    # Patterns για hardcoded έτη
    patterns = [
        r'2024',  # Hardcoded 2024
        r'2025',  # Hardcoded 2025 (μπορεί να είναι σωστό αλλά ας το ελέγξουμε)
    ]
    
    # Αγνοούμε migration files και backup files
    ignore_patterns = [
        'migrations/',
        '.backup',
        '__pycache__/',
        '.pyc',
        'media/',
        'static/',
        'logs/',
    ]
    
    # Αγνοούμε σχόλια και documentation
    comment_patterns = [
        r'# Generated by Django',
        r'# Created:',
        r'# Updated:',
        r'Updated: 2025',
        r'Created: 2025',
    ]
    
    for root, dirs, files in os.walk(directory):
        # Αγνοούμε συγκεκριμένους φακέλους
        dirs[:] = [d for d in dirs if not any(pattern in d for pattern in ignore_patterns)]
        
        for file in files:
            if file.endswith('.py'):
                file_path = os.path.join(root, file)
                
                # Αγνοούμε backup files
                if any(pattern in file_path for pattern in ignore_patterns):
                    continue
                
                try:
                    with open(file_path, 'r', encoding='utf-8') as f:
                        content = f.read()
                        lines = content.split('\n')
                        
                        issues = []
                        for line_num, line in enumerate(lines, 1):
                            # Αγνοούμε σχόλια και documentation
                            if any(pattern in line for pattern in comment_patterns):
                                continue
                                
                            # Αγνοούμε migration files
                            if 'migrations/' in file_path and '# Generated by Django' in line:
                                continue
                            
                            # Ελέγχουμε για hardcoded έτη
                            for pattern in patterns:
                                if re.search(pattern, line):
                                    # Ελέγχουμε αν είναι σε string ή comment
                                    if ('"' + pattern + '"' in line or 
                                        "'" + pattern + "'" in line or
                                        f'date({pattern}' in line or
                                        f'year={pattern}' in line or
                                        f'__year={pattern}' in line or
                                        f'date__year={pattern}' in line):
                                        
                                        issues.append({
                                            'line': line_num,
                                            'content': line.strip(),
                                            'pattern': pattern
                                        })
                        
                        if issues:
                            hardcoded_files.append({
                                'file': file_path,
                                'issues': issues
                            })
                
                except Exception as e:
                    print(f"❌ Σφάλμα στο αρχείο {file_path}: {e}")
    
    return hardcoded_files

def suggest_fixes(hardcoded_files):
    """Προτείνει διορθώσεις για hardcoded έτη"""
    
    suggestions = []
    
    for file_info in hardcoded_files:
        file_path = file_info['file']
        issues = file_info['issues']
        
        file_suggestions = {
            'file': file_path,
            'suggestions': []
        }
        
        for issue in issues:
            line = issue['content']
            pattern = issue['pattern']
            
            if pattern == '2024':
                if 'date__year=2024' in line:
                    suggestion = line.replace('date__year=2024', 'date__year=current_year')
                    file_suggestions['suggestions'].append({
                        'line': issue['line'],
                        'original': line,
                        'suggestion': suggestion,
                        'reason': 'Χρησιμοποιήστε current_year = datetime.now().year'
                    })
                elif 'datetime(2024,' in line:
                    suggestion = line.replace('datetime(2024,', 'datetime(current_year,')
                    file_suggestions['suggestions'].append({
                        'line': issue['line'],
                        'original': line,
                        'suggestion': suggestion,
                        'reason': 'Χρησιμοποιήστε current_year αντί για hardcoded 2024'
                    })
                elif '"2024"' in line or "'2024'" in line:
                    suggestion = line.replace('"2024"', 'f"{current_year}"').replace("'2024'", "f'{current_year}'")
                    file_suggestions['suggestions'].append({
                        'line': issue['line'],
                        'original': line,
                        'suggestion': suggestion,
                        'reason': 'Χρησιμοποιήστε f-string με current_year'
                    })
        
        if file_suggestions['suggestions']:
            suggestions.append(file_suggestions)
    
    return suggestions

def main():
    """Κύρια συνάρτηση"""
    
    print("🔍 ΕΛΕΓΧΟΣ HARDCODED ΕΤΩΝ ΣΤΟΝ ΚΩΔΙΚΑ")
    print("=" * 70)
    
    # Έλεγχος του backend directory
    backend_dir = os.path.join(os.path.dirname(__file__))
    
    print(f"📁 Έλεγχος directory: {backend_dir}")
    print()
    
    hardcoded_files = find_hardcoded_years(backend_dir)
    
    if not hardcoded_files:
        print("✅ Δεν βρέθηκαν hardcoded έτη!")
        return
    
    print(f"❌ Βρέθηκαν {len(hardcoded_files)} αρχεία με hardcoded έτη:")
    print()
    
    for file_info in hardcoded_files:
        print(f"📄 {file_info['file']}")
        for issue in file_info['issues']:
            print(f"   Line {issue['line']}: {issue['content']}")
        print()
    
    # Προτάσεις διορθώσεων
    suggestions = suggest_fixes(hardcoded_files)
    
    if suggestions:
        print("🔧 ΠΡΟΤΑΣΕΙΣ ΔΙΟΡΘΩΣΕΩΝ:")
        print("=" * 70)
        
        for suggestion in suggestions:
            print(f"📄 {suggestion['file']}")
            for fix in suggestion['suggestions']:
                print(f"   Line {fix['line']}:")
                print(f"   ❌ {fix['original']}")
                print(f"   ✅ {fix['suggestion']}")
                print(f"   💡 {fix['reason']}")
                print()
    
    print("=" * 70)
    print("✅ Ο έλεγχος ολοκληρώθηκε!")

if __name__ == "__main__":
    main()
