# Generated by Django 5.2.4 on 2025-07-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='office_address',
            field=models.CharField(blank=True, help_text='Διεύθυνση του γραφείου διαχείρισης', max_length=255, verbose_name='Διεύθυνση Γραφείου Διαχείρισης'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_name',
            field=models.CharField(blank=True, help_text='Όνομα της εταιρείας/γραφείου διαχείρισης', max_length=255, verbose_name='Όνομα Γραφείου Διαχείρισης'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_phone',
            field=models.CharField(blank=True, help_text='Τηλέφωνο επικοινωνίας με το γραφείο διαχείρισης', max_length=20, verbose_name='Τηλέφωνο Γραφείου Διαχείρισης'),
        ),
    ]
