# Generated by Django 5.2.5 on 2025-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_office_address_customuser_office_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='office_logo',
            field=models.ImageField(blank=True, help_text='Logo της εταιρείας διαχείρισης', null=True, upload_to='office_logos/', verbose_name='Logo Γραφείου Διαχείρισης'),
        ),
    ]
