# Generated by Django 5.2.5 on 2025-08-31 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_office_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='office_bank_account',
            field=models.CharField(blank=True, help_text='Αριθμός τραπεζικού λογαριασμού', max_length=50, verbose_name='Αριθμός Λογαριασμού'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_bank_beneficiary',
            field=models.CharField(blank=True, help_text='Όνομα δικαιούχου του λογαριασμού', max_length=255, verbose_name='Δικαιούχος'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_bank_iban',
            field=models.CharField(blank=True, help_text='IBAN για πληρωμές', max_length=34, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='office_bank_name',
            field=models.CharField(blank=True, help_text='Όνομα της τράπεζας για πληρωμές', max_length=100, verbose_name='Όνομα Τράπεζας'),
        ),
    ]
