# Generated by Django 5.2.1 on 2025-05-25 14:03

from django.db import migrations, models  # type: ignore  # type: ignore


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('resident', 'Resident'), ('admin', 'Admin')], max_length=20, null=True),
        ),
    ]
