# Generated by Django 5.2.7 on 2025-10-16 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_office_bank_account_and_more'),
    ]

    operations = [
    ]
