# Generated by Django 5.2.7 on 2025-10-16 04:04

from django.db import migrations
from django.contrib.auth.models import Group, Permission
from django.contrib.contenttypes.models import ContentType


def create_groups_and_permissions(apps, schema_editor):
    """
    Δημιουργία Groups και ανάθεση permissions για το RBAC σύστημα.
    
    Groups:
    - Manager: Πλήρη δικαιώματα διαχείρισης
    - Resident: Περιορισμένα δικαιώματα ανάγνωσης και υποβολής αιτημάτων
    """
    
    # Δημιουργία Groups
    manager_group, created = Group.objects.get_or_create(name='Manager')
    resident_group, created = Group.objects.get_or_create(name='Resident')
    
    if created:
        print(f"✅ Created groups: Manager, Resident")
    else:
        print(f"ℹ️  Groups already exist: Manager, Resident")
    
    # Λήψη ContentTypes για τα models
    try:
        # Financial models
        expense_ct = ContentType.objects.get_for_model(apps.get_model('financial', 'Expense'))
        payment_ct = ContentType.objects.get_for_model(apps.get_model('financial', 'Payment'))
        transaction_ct = ContentType.objects.get_for_model(apps.get_model('financial', 'Transaction'))
        
        # Maintenance models
        maintenance_ticket_ct = ContentType.objects.get_for_model(apps.get_model('maintenance', 'MaintenanceTicket'))
        contractor_ct = ContentType.objects.get_for_model(apps.get_model('maintenance', 'Contractor'))
        service_receipt_ct = ContentType.objects.get_for_model(apps.get_model('maintenance', 'ServiceReceipt'))
        
        # Building models
        building_ct = ContentType.objects.get_for_model(apps.get_model('buildings', 'Building'))
        apartment_ct = ContentType.objects.get_for_model(apps.get_model('apartments', 'Apartment'))
        
        # User models
        user_ct = ContentType.objects.get_for_model(apps.get_model('users', 'CustomUser'))
        
        # Διαγραφή παλιών permissions από groups (για clean state)
        manager_group.permissions.clear()
        resident_group.permissions.clear()
        
        # ===== MANAGER PERMISSIONS =====
        # Financial permissions - Full CRUD
        manager_permissions = [
            # Expense permissions
            Permission.objects.get(content_type=expense_ct, codename='add_expense'),
            Permission.objects.get(content_type=expense_ct, codename='change_expense'),
            Permission.objects.get(content_type=expense_ct, codename='delete_expense'),
            Permission.objects.get(content_type=expense_ct, codename='view_expense'),
            
            # Payment permissions
            Permission.objects.get(content_type=payment_ct, codename='add_payment'),
            Permission.objects.get(content_type=payment_ct, codename='change_payment'),
            Permission.objects.get(content_type=payment_ct, codename='delete_payment'),
            Permission.objects.get(content_type=payment_ct, codename='view_payment'),
            
            # Transaction permissions (view only for audit)
            Permission.objects.get(content_type=transaction_ct, codename='view_transaction'),
            
            # Maintenance permissions - Full CRUD
            Permission.objects.get(content_type=maintenance_ticket_ct, codename='add_maintenanceticket'),
            Permission.objects.get(content_type=maintenance_ticket_ct, codename='change_maintenanceticket'),
            Permission.objects.get(content_type=maintenance_ticket_ct, codename='delete_maintenanceticket'),
            Permission.objects.get(content_type=maintenance_ticket_ct, codename='view_maintenanceticket'),
            
            Permission.objects.get(content_type=contractor_ct, codename='add_contractor'),
            Permission.objects.get(content_type=contractor_ct, codename='change_contractor'),
            Permission.objects.get(content_type=contractor_ct, codename='delete_contractor'),
            Permission.objects.get(content_type=contractor_ct, codename='view_contractor'),
            
            Permission.objects.get(content_type=service_receipt_ct, codename='add_servicereceipt'),
            Permission.objects.get(content_type=service_receipt_ct, codename='change_servicereceipt'),
            Permission.objects.get(content_type=service_receipt_ct, codename='delete_servicereceipt'),
            Permission.objects.get(content_type=service_receipt_ct, codename='view_servicereceipt'),
            
            # Building permissions - View only
            Permission.objects.get(content_type=building_ct, codename='view_building'),
            Permission.objects.get(content_type=apartment_ct, codename='view_apartment'),
        ]
        
        # ===== RESIDENT PERMISSIONS =====
        # Περιορισμένα δικαιώματα - μόνο view και add για maintenance tickets
        resident_permissions = [
            # Financial permissions - View only
            Permission.objects.get(content_type=expense_ct, codename='view_expense'),
            Permission.objects.get(content_type=payment_ct, codename='view_payment'),
            Permission.objects.get(content_type=transaction_ct, codename='view_transaction'),
            
            # Maintenance permissions - Add tickets, view own tickets
            Permission.objects.get(content_type=maintenance_ticket_ct, codename='add_maintenanceticket'),
            Permission.objects.get(content_type=maintenance_ticket_ct, codename='view_maintenanceticket'),
            
            # View contractors for ticket creation
            Permission.objects.get(content_type=contractor_ct, codename='view_contractor'),
            
            # Building permissions - View only
            Permission.objects.get(content_type=building_ct, codename='view_building'),
            Permission.objects.get(content_type=apartment_ct, codename='view_apartment'),
        ]
        
        # Ανάθεση permissions σε groups
        manager_group.permissions.set(manager_permissions)
        resident_group.permissions.set(resident_permissions)
        
        print(f"✅ Manager group: {len(manager_permissions)} permissions assigned")
        print(f"✅ Resident group: {len(resident_permissions)} permissions assigned")
        
    except Exception as e:
        print(f"❌ Error assigning permissions: {e}")
        # Συνεχίζουμε ακόμα κι αν υπάρχει πρόβλημα με permissions
        pass


def reverse_groups_and_permissions(apps, schema_editor):
    """Αναστροφή της migration - διαγραφή groups"""
    try:
        Group.objects.filter(name__in=['Manager', 'Resident']).delete()
        print("✅ Groups deleted successfully")
    except Exception as e:
        print(f"❌ Error deleting groups: {e}")


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_office_bank_account_and_more'),
        ('financial', '0001_initial'),  # Βεβαιώνουμε ότι τα financial models υπάρχουν
        ('maintenance', '0001_initial'),  # Βεβαιώνουμε ότι τα maintenance models υπάρχουν
        ('buildings', '0001_initial'),  # Βεβαιώνουμε ότι τα building models υπάρχουν
        ('apartments', '0001_initial'),  # Βεβαιώνουμε ότι τα apartment models υπάρχουν
    ]

    operations = [
        migrations.RunPython(
            create_groups_and_permissions,
            reverse_groups_and_permissions,
        ),
    ]
