# Generated by Django 5.2.1 on 2025-06-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Office Manager')], help_text='Ρόλος σε επίπεδο tenant (π.χ. γραφείο διαχείρισης)', max_length=20, null=True),
        ),
    ]
