# Generated by Django 5.2.7 on 2025-10-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_email_verification_sent_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['email'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_notifications_enabled',
            field=models.BooleanField(default=True, help_text='Ενεργοποίηση email ειδοποιήσεων', verbose_name='Email Notifications Enabled'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_announcements',
            field=models.BooleanField(default=True, help_text='Ειδοποιήσεις για ανακοινώσεις', verbose_name='Announcements'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_financial_updates',
            field=models.BooleanField(default=True, help_text='Ειδοποιήσεις για οικονομικές ενημερώσεις', verbose_name='Financial Updates'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_maintenance_updates',
            field=models.BooleanField(default=True, help_text='Ειδοποιήσεις για αιτήματα συντήρησης', verbose_name='Maintenance Updates'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='notify_votes',
            field=models.BooleanField(default=True, help_text='Ειδοποιήσεις για ψηφοφορίες', verbose_name='Votes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='sms_notifications_enabled',
            field=models.BooleanField(default=False, help_text='Ενεργοποίηση SMS ειδοποιήσεων', verbose_name='SMS Notifications Enabled'),
        ),
    ]
