# Generated by Django 5.2.7 on 2025-10-16 12:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_account_security_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='failed_login_attempts',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_failed_login',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='locked_until',
        ),
        migrations.CreateModel(
            name='UserLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email που χρησιμοποιήθηκε για την προσπάθεια σύνδεσης', max_length=254, verbose_name='Email')),
                ('ip_address', models.GenericIPAddressField(help_text='IP διεύθυνση από την οποία έγινε η προσπάθεια', verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, help_text='User agent string του browser/client', verbose_name='User Agent')),
                ('success', models.BooleanField(default=False, help_text='Αν η προσπάθεια σύνδεσης ήταν επιτυχής', verbose_name='Success')),
                ('failure_reason', models.CharField(blank=True, help_text='Λόγος αποτυχίας (αν υπάρχει)', max_length=100, verbose_name='Failure Reason')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, help_text='Ώρα που έγινε η προσπάθεια', verbose_name='Attempted At')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='login_attempts', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Login Attempt',
                'verbose_name_plural': 'User Login Attempts',
                'ordering': ['-attempted_at'],
                'indexes': [models.Index(fields=['email', 'attempted_at'], name='users_userl_email_596691_idx'), models.Index(fields=['ip_address', 'attempted_at'], name='users_userl_ip_addr_2a04b2_idx'), models.Index(fields=['success', 'attempted_at'], name='users_userl_success_22038d_idx')],
            },
        ),
    ]
