# Generated by Django 5.2.7 on 2025-10-16 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_add_login_attempt_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Αριθμός αποτυχημένων προσπαθειών σύνδεσης', verbose_name='Failed Login Attempts'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, help_text='Τελευταία αποτυχημένη προσπάθεια σύνδεσης', null=True, verbose_name='Last Failed Login'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='locked_until',
            field=models.DateTimeField(blank=True, help_text='Λογαριασμός κλειδωμένος μέχρι αυτή την ημερομηνία', null=True, verbose_name='Locked Until'),
        ),
    ]
