# Generated by Django 5.2.7 on 2025-10-18 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_add_security_fields_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='oauth_provider',
            field=models.CharField(blank=True, help_text='OAuth provider (google, microsoft, etc.)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='oauth_provider_id',
            field=models.CharField(blank=True, help_text='User ID from OAuth provider', max_length=100, null=True),
        ),
    ]
