# Generated by Django 5.2.7 on 2025-10-20 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_client_is_active_client_trial_days'),
        ('users', '0011_customuser_oauth_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, help_text='Temporary Stripe checkout session ID for polling', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Tenant that this user belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tenants.client'),
        ),
    ]
