# Generated by Django 5.2.8 on 2025-11-13 20:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_username_field_state_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, db_column='username', default='', help_text='Legacy username field for compatibility with existing data', max_length=150),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='invited_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_user_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invited By'),
        ),
        migrations.CreateModel(
            name='TenantInvitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(help_text='Email address of the invited user', max_length=254)),
                ('invited_role', models.CharField(choices=[('resident', 'Resident'), ('manager', 'Manager'), ('staff', 'Staff')], default='resident', help_text='Role the user will have when they accept', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Invitation expiration date/time')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.TextField(blank=True, help_text='Optional personal message to the invitee')),
                ('created_user', models.ForeignKey(blank=True, help_text='User created from this invitation (if accepted)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL)),
                ('invited_by', models.ForeignKey(help_text='User who sent the invitation', on_delete=django.db.models.deletion.CASCADE, related_name='sent_tenant_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-invited_at'],
                'indexes': [models.Index(fields=['email', 'status'], name='users_tenan_email_405961_idx'), models.Index(fields=['invited_by', 'status'], name='users_tenan_invited_8d8333_idx'), models.Index(fields=['status', 'expires_at'], name='users_tenan_status_b8b2b5_idx')],
                'unique_together': {('email', 'invited_by', 'status')},
            },
        ),
    ]
