# Generated by Django 5.2.8 on 2025-11-25 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_office_phone_emergency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Office Manager'), ('internal_manager', 'Internal Manager'), ('resident', 'Resident')], help_text='Ρόλος σε επίπεδο tenant (π.χ. γραφείο διαχείρισης)', max_length=20, null=True),
        ),
    ]
