# Generated by Django 5.2.8 on 2025-11-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_fix_userinvitation_created_user_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('manager', 'Office Manager'), ('office_staff', 'Office Staff'), ('internal_manager', 'Internal Manager'), ('resident', 'Resident')], help_text='Ρόλος σε επίπεδο tenant (π.χ. γραφείο διαχείρισης)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tenantinvitation',
            name='invited_role',
            field=models.CharField(choices=[('resident', 'Resident'), ('manager', 'Manager'), ('staff', 'Staff'), ('internal_manager', 'Internal Manager')], default='resident', help_text='Role the user will have when they accept', max_length=20),
        ),
    ]
