# Generated by Django 5.2.8 on 2025-11-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_userinvitation_apartment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='auto_approved',
            field=models.BooleanField(default=False, help_text='Αν η πρόσκληση είναι αυτόματα εγκεκριμένη (για kiosk registrations)', verbose_name='Auto Approved'),
        ),
        migrations.AddField(
            model_name='userinvitation',
            name='source',
            field=models.CharField(choices=[('admin', 'Admin/Manager Invitation'), ('kiosk', 'Kiosk Self-Registration')], default='admin', help_text='Πηγή της πρόσκλησης (admin ή kiosk)', max_length=20, verbose_name='Invitation Source'),
        ),
        migrations.AlterField(
            model_name='userinvitation',
            name='invitation_type',
            field=models.CharField(choices=[('registration', 'Registration'), ('building_access', 'Building Access'), ('role_assignment', 'Role Assignment'), ('kiosk_registration', 'Kiosk Registration')], default='registration', max_length=20, verbose_name='Invitation Type'),
        ),
    ]
