# Generated by Django 5.2.8 on 2025-12-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_add_building_to_tenant_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvitation',
            name='tenant_schema_name',
            field=models.CharField(blank=True, help_text='Schema name του tenant στον οποίο ανήκει η πρόσκληση', max_length=63, null=True, verbose_name='Tenant Schema Name'),
        ),
    ]
