# Generated by Codex on 2026-01-10

from django.db import migrations


def add_username_column_if_missing(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    table_name = CustomUser._meta.db_table
    field = CustomUser._meta.get_field('username')

    with schema_editor.connection.cursor() as cursor:
        existing_tables = schema_editor.connection.introspection.table_names(cursor)
        if table_name not in existing_tables:
            return
        columns = [
            col.name
            for col in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        ]

    if field.column not in columns:
        schema_editor.add_field(CustomUser, field)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_add_tenant_schema_name_to_invitation'),
    ]

    operations = [
        migrations.RunPython(
            add_username_column_if_missing,
            migrations.RunPython.noop,
        ),
    ]
