# Generated by Django 5.2.4 on 2025-08-03 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0005_apartment_current_balance_and_more'),
        ('buildings', '0007_building_current_reserve'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος Δαπάνης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό (€)')),
                ('date', models.DateField(verbose_name='Ημερομηνία')),
                ('category', models.CharField(choices=[('cleaning', 'Καθαρισμός Κοινοχρήστων Χώρων'), ('electricity_common', 'ΔΕΗ Κοινοχρήστων'), ('water_common', 'Νερό Κοινοχρήστων'), ('garbage_collection', 'Συλλογή Απορριμμάτων'), ('security', 'Ασφάλεια Κτιρίου'), ('concierge', 'Συνεργείο Καθαρισμού'), ('elevator_maintenance', 'Ετήσια Συντήρηση Ανελκυστήρα'), ('elevator_repair', 'Επισκευή Ανελκυστήρα'), ('elevator_inspection', 'Επιθεώρηση Ανελκυστήρα'), ('elevator_modernization', 'Αναβάθμιση Ανελκυστήρα'), ('heating_fuel', 'Πετρέλαιο Θέρμανσης'), ('heating_gas', 'Φυσικό Αέριο Θέρμανσης'), ('heating_maintenance', 'Συντήρηση Καυστήρα'), ('heating_repair', 'Επισκευή Θερμαντικών'), ('heating_inspection', 'Επιθεώρηση Θερμαντικών'), ('heating_modernization', 'Αναβάθμιση Θερμαντικών'), ('electrical_maintenance', 'Συντήρηση Ηλεκτρικών'), ('electrical_repair', 'Επισκευή Ηλεκτρικών'), ('electrical_upgrade', 'Αναβάθμιση Ηλεκτρικών'), ('lighting_common', 'Φωτισμός Κοινοχρήστων'), ('intercom_system', 'Σύστημα Εσωτερικής Επικοινωνίας'), ('plumbing_maintenance', 'Συντήρηση Υδραυλικών'), ('plumbing_repair', 'Επισκευή Υδραυλικών'), ('water_tank_cleaning', 'Καθαρισμός Δεξαμενής Νερού'), ('water_tank_maintenance', 'Συντήρηση Δεξαμενής Νερού'), ('sewage_system', 'Σύστημα Αποχέτευσης'), ('building_insurance', 'Ασφάλεια Κτιρίου'), ('building_maintenance', 'Συντήρηση Κτιρίου'), ('roof_maintenance', 'Συντήρηση Στέγης'), ('roof_repair', 'Επισκευή Στέγης'), ('facade_maintenance', 'Συντήρηση Πρόσοψης'), ('facade_repair', 'Επισκευή Πρόσοψης'), ('painting_exterior', 'Βαψίματα Εξωτερικών'), ('painting_interior', 'Βαψίματα Εσωτερικών Κοινοχρήστων'), ('garden_maintenance', 'Συντήρηση Κήπου'), ('parking_maintenance', 'Συντήρηση Χώρων Στάθμευσης'), ('entrance_maintenance', 'Συντήρηση Εισόδου'), ('emergency_repair', 'Έκτακτη Επισκευή'), ('storm_damage', 'Ζημιές από Κακοκαιρία'), ('flood_damage', 'Ζημιές από Πλημμύρα'), ('fire_damage', 'Ζημιές από Πυρκαγιά'), ('earthquake_damage', 'Ζημιές από Σεισμό'), ('vandalism_repair', 'Επισκευή Βανδαλισμών'), ('locksmith', 'Κλειδαράς'), ('glass_repair', 'Επισκευή Γυαλιών'), ('door_repair', 'Επισκευή Πόρτας'), ('window_repair', 'Επισκευή Παραθύρων'), ('balcony_repair', 'Επισκευή Μπαλκονιού'), ('staircase_repair', 'Επισκευή Σκάλας'), ('security_system', 'Σύστημα Ασφάλειας'), ('cctv_installation', 'Εγκατάσταση CCTV'), ('access_control', 'Σύστημα Ελέγχου Πρόσβασης'), ('fire_alarm', 'Σύστημα Πυρασφάλειας'), ('fire_extinguishers', 'Πυροσβεστήρες'), ('legal_fees', 'Δικαστικά Έξοδα'), ('notary_fees', 'Συμβολαιογραφικά Έξοδα'), ('surveyor_fees', 'Εκτιμητής'), ('architect_fees', 'Αρχιτέκτονας'), ('engineer_fees', 'Μηχανικός'), ('accounting_fees', 'Λογιστικά Έξοδα'), ('management_fees', 'Διοικητικά Έξοδα'), ('asbestos_removal', 'Αφαίρεση Ασβέστη'), ('lead_paint_removal', 'Αφαίρεση Μολύβδου'), ('mold_removal', 'Αφαίρεση Μούχλας'), ('pest_control', 'Εντομοκτονία'), ('tree_trimming', 'Κλάδεμα Δέντρων'), ('snow_removal', 'Καθαρισμός Χιονιού'), ('energy_upgrade', 'Ενεργειακή Αναβάθμιση'), ('insulation_work', 'Θερμομόνωση'), ('solar_panel_installation', 'Εγκατάσταση Φωτοβολταϊκών'), ('led_lighting', 'Αντικατάσταση με LED'), ('smart_systems', 'Έξυπνα Συστήματα'), ('special_contribution', 'Έκτακτη Εισφορά'), ('reserve_fund', 'Αποθεματικό Ταμείο'), ('emergency_fund', 'Ταμείο Έκτακτης Ανάγκης'), ('renovation_fund', 'Ταμείο Ανακαίνισης'), ('miscellaneous', 'Διάφορες Δαπάνες'), ('consulting_fees', 'Εργασίες Συμβούλου'), ('permits_licenses', 'Άδειες & Αποδοχές'), ('taxes_fees', 'Φόροι & Τέλη'), ('utilities_other', 'Άλλες Κοινόχρηστες Υπηρεσίες')], max_length=50, verbose_name='Κατηγορία')),
                ('distribution_type', models.CharField(choices=[('by_participation_mills', 'Ανά Χιλιοστά'), ('equal_share', 'Ισόποσα'), ('specific_apartments', 'Συγκεκριμένα'), ('by_meters', 'Μετρητές')], max_length=50, verbose_name='Τρόπος Κατανομής')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='expenses/', verbose_name='Επισύναψη')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('is_issued', models.BooleanField(default=False, verbose_name='Εκδοθείσα')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Δαπάνη',
                'verbose_name_plural': 'Δαπάνες',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό')),
                ('date', models.DateField(verbose_name='Ημερομηνία Πληρωμής')),
                ('method', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('check', 'Επιταγή'), ('card', 'Κάρτα')], max_length=20, verbose_name='Τρόπος Πληρωμής')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='payment_receipts/', verbose_name='Απόδειξη')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apartments.apartment')),
            ],
            options={
                'verbose_name': 'Πληρωμή',
                'verbose_name_plural': 'Πληρωμές',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Ημερομηνία')),
                ('type', models.CharField(choices=[('common_expense_payment', 'Πληρωμή Κοινοχρήστων'), ('expense_payment', 'Πληρωμή Δαπάνης'), ('refund', 'Επιστροφή'), ('common_expense_charge', 'Χρέωση Κοινοχρήστων')], max_length=50, verbose_name='Τύπος')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('apartment_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Αριθμός Διαμερίσματος')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό')),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Υπόλοιπο Μετά')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts/', verbose_name='Απόδειξη')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Κίνηση Ταμείου',
                'verbose_name_plural': 'Κινήσεις Ταμείου',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseApartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='apartments.apartment')),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affected_apartments', to='financial.expense')),
            ],
            options={
                'verbose_name': 'Δαπάνη-Διαμέρισμα',
                'verbose_name_plural': 'Δαπάνες-Διαμερίσματα',
                'unique_together': {('expense', 'apartment')},
            },
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_date', models.DateField(verbose_name='Ημερομηνία Μετρήσης')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Τιμή Μετρήσης')),
                ('meter_type', models.CharField(choices=[('heating', 'Θέρμανση'), ('water', 'Νερό'), ('electricity', 'Ηλεκτρικό')], max_length=50, verbose_name='Τύπος Μετρητή')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meter_readings', to='apartments.apartment')),
            ],
            options={
                'verbose_name': 'Μετρήση',
                'verbose_name_plural': 'Μετρήσεις',
                'ordering': ['-reading_date', '-created_at'],
                'unique_together': {('apartment', 'reading_date', 'meter_type')},
            },
        ),
    ]
