# Generated by Django 5.2.4 on 2025-08-02 17:44

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apartments', '0004_apartment_is_closed'),
        ('buildings', '0005_building_management_office_address_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('operating', 'Λειτουργικός'), ('reserve', 'Αποθεματικό'), ('special', 'Ειδικός')], max_length=20, verbose_name='Τύπος Λογαριασμού')),
                ('account_number', models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Λογαριασμού')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Όνομα Τράπεζας')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Τρέχον Υπόλοιπο')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='buildings.building', verbose_name='Κτίριο')),
            ],
            options={
                'verbose_name': 'Λογαριασμός Κτιρίου',
                'verbose_name_plural': 'Λογαριασμοί Κτιρίου',
                'unique_together': {('building', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='FinancialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', 'Έσοδο'), ('expense', 'Έξοδο')], max_length=20, verbose_name='Τύπος Συναλλαγής')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('transaction_date', models.DateField(verbose_name='Ημερομηνία Συναλλαγής')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Αναφοράς')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Κατηγορία')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='financial.buildingaccount', verbose_name='Λογαριασμός')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_transactions', to='buildings.building', verbose_name='Κτίριο')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Οικονομική Συναλλαγή',
                'verbose_name_plural': 'Οικονομικές Συναλλαγές',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('common_expenses', 'Κοινοχρήστων'), ('heating', 'Θέρμανση'), ('electricity_common', 'Ηλεκτρικό Κοινοχρήστων'), ('cleaning', 'Καθαριότητα'), ('security', 'Ασφάλεια'), ('elevator', 'Ανελκυστήρες'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Πληρωμής')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό')),
                ('due_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('status', models.CharField(choices=[('pending', 'Εκκρεμεί'), ('paid', 'Πληρωμένο'), ('overdue', 'Ληξιπρόθεσμο'), ('partial', 'Μερική Πληρωμή')], default='pending', max_length=20, verbose_name='Κατάσταση')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Πληρωμής')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ποσό που Πληρώθηκε')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Μέθοδος Πληρωμής')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Αναφοράς')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='apartments.apartment', verbose_name='Διαμέρισμα')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
            ],
            options={
                'verbose_name': 'Πληρωμή',
                'verbose_name_plural': 'Πληρωμές',
                'ordering': ['-due_date'],
            },
        ),
        migrations.CreateModel(
            name='FinancialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('check', 'Επιταγή'), ('online', 'Online Πληρωμή'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Απόδειξης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό')),
                ('receipt_date', models.DateField(verbose_name='Ημερομηνία Απόδειξης')),
                ('receipt_file', models.FileField(blank=True, upload_to='financial_receipts/%Y/%m/', verbose_name='Αρχείο Απόδειξης')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Αναφοράς')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='financial.payment', verbose_name='Πληρωμή')),
            ],
            options={
                'verbose_name': 'Απόδειξη Εισπράξεως',
                'verbose_name_plural': 'Αποδείξεις Εισπράξεων',
                'ordering': ['-receipt_date'],
            },
        ),
    ]
