# Generated by Django 5.2.4 on 2025-08-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_current_balance_and_more'),
        ('buildings', '0007_building_current_reserve'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='apartments.apartment', verbose_name='Διαμέρισμα'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='balance_before',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Υπόλοιπο Πριν'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='created_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Δημιουργήθηκε από'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Αναφορά'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Τύπος Αναφοράς'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Εκκρεμεί'), ('completed', 'Ολοκληρώθηκε'), ('cancelled', 'Ακυρώθηκε'), ('failed', 'Απέτυχε')], default='completed', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('common_expense_payment', 'Πληρωμή Κοινοχρήστων'), ('expense_payment', 'Πληρωμή Δαπάνης'), ('refund', 'Επιστροφή'), ('common_expense_charge', 'Χρέωση Κοινοχρήστων'), ('payment_received', 'Πληρωμή Ληφθείσα'), ('expense_created', 'Δαπάνη Δημιουργήθηκε'), ('expense_issued', 'Δαπάνη Εκδόθηκε'), ('balance_adjustment', 'Προσαρμογή Υπολοίπου'), ('interest_charge', 'Χρέωση Τόκων'), ('penalty_charge', 'Χρέωση Προστίμου')], max_length=50, verbose_name='Τύπος'),
        ),
        migrations.CreateModel(
            name='FinancialAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία/Ώρα')),
                ('action', models.CharField(choices=[('CREATE', 'Δημιουργία'), ('UPDATE', 'Ενημέρωση'), ('DELETE', 'Διαγραφή'), ('ISSUE', 'Έκδοση'), ('PAYMENT', 'Πληρωμή'), ('CALCULATE', 'Υπολογισμός'), ('EXPORT', 'Εξαγωγή'), ('LOGIN', 'Σύνδεση'), ('LOGOUT', 'Αποσύνδεση'), ('VIEW', 'Προβολή')], max_length=20, verbose_name='Ενέργεια')),
                ('description', models.TextField(verbose_name='Περιγραφή')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Διεύθυνση')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_method', models.CharField(blank=True, max_length=10, verbose_name='HTTP Μέθοδος')),
                ('request_path', models.CharField(blank=True, max_length=255, verbose_name='Request Path')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Αλλαγές')),
                ('session_id', models.CharField(blank=True, max_length=100, verbose_name='Session ID')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='buildings.building', verbose_name='Πολυκατοικία')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Χρήστης')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='financial_f_timesta_9a7578_idx'), models.Index(fields=['user'], name='financial_f_user_id_7967c0_idx'), models.Index(fields=['action'], name='financial_f_action_2bb324_idx'), models.Index(fields=['building'], name='financial_f_buildin_043e91_idx'), models.Index(fields=['content_type', 'object_id'], name='financial_f_content_6b93db_idx')],
            },
        ),
    ]
