# Generated by Django 5.0.14 on 2025-08-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_transaction_apartment_transaction_balance_before_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='attachment',
            field=models.FileField(blank=True, help_text='Παραστατικό ή άλλο σχετικό αρχείο', null=True, upload_to='expenses/', verbose_name='Επισύναψη'),
        ),
    ]
