# Generated by Django 5.2.4 on 2025-08-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_current_balance_and_more'),
        ('financial', '0003_alter_expense_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['apartment', 'meter_type', 'reading_date'], name='financial_m_apartme_1c79a0_idx'),
        ),
        migrations.AddIndex(
            model_name='meterreading',
            index=models.Index(fields=['reading_date'], name='financial_m_reading_0aadc3_idx'),
        ),
    ]
