# Generated by Django 5.2.4 on 2025-08-03 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_meterreading_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='meterreading',
            name='financial_m_apartme_1c79a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='meterreading',
            name='financial_m_reading_0aadc3_idx',
        ),
        migrations.RemoveField(
            model_name='meterreading',
            name='updated_at',
        ),
    ]
