# Generated by Django 5.2.4 on 2025-08-05 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0007_building_current_reserve'),
        ('financial', '0005_remove_meterreading_financial_m_apartme_1c79a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Είσπραξη', 'verbose_name_plural': 'Εισπράξεις'},
        ),
        migrations.AlterField(
            model_name='financialauditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Δημιουργία'), ('UPDATE', 'Ενημέρωση'), ('DELETE', 'Διαγραφή'), ('ISSUE', 'Έκδοση'), ('PAYMENT', 'Είσπραξη'), ('CALCULATE', 'Υπολογισμός'), ('EXPORT', 'Εξαγωγή'), ('LOGIN', 'Σύνδεση'), ('LOGOUT', 'Αποσύνδεση'), ('VIEW', 'Προβολή')], max_length=20, verbose_name='Ενέργεια'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='date',
            field=models.DateField(verbose_name='Ημερομηνία Εισπράξεως'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('check', 'Επιταγή'), ('card', 'Κάρτα')], max_length=20, verbose_name='Τρόπος Εισπράξεως'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('common_expense_payment', 'Είσπραξη Κοινοχρήστων'), ('expense_payment', 'Είσπραξη Δαπάνης'), ('refund', 'Επιστροφή'), ('common_expense_charge', 'Χρέωση Κοινοχρήστων'), ('payment_received', 'Είσπραξη Ληφθείσα'), ('expense_created', 'Δαπάνη Δημιουργήθηκε'), ('expense_issued', 'Δαπάνη Εκδόθηκε'), ('balance_adjustment', 'Προσαρμογή Υπολοίπου'), ('interest_charge', 'Χρέωση Τόκων'), ('penalty_charge', 'Χρέωση Προστίμου')], max_length=50, verbose_name='Τύπος'),
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Όνομα Προμηθευτή')),
                ('category', models.CharField(choices=[('electricity', 'ΔΕΗ (Ηλεκτρικό Ρεύμα)'), ('water', 'ΕΥΔΑΠ (Νερό)'), ('cleaning', 'Καθαρισμός'), ('elevator', 'Ανελκυστήρας'), ('heating', 'Θέρμανση'), ('insurance', 'Ασφάλεια'), ('administrative', 'Διοικητικά'), ('repairs', 'Επισκευές'), ('other', 'Άλλοι')], max_length=50, verbose_name='Κατηγορία')),
                ('account_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Λογαριασμού')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Τηλέφωνο')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Διεύθυνση')),
                ('vat_number', models.CharField(blank=True, max_length=50, verbose_name='ΑΦΜ')),
                ('contract_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Συμβολαίου')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργός')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Προμηθευτής',
                'verbose_name_plural': 'Προμηθευτές',
                'ordering': ['name'],
                'unique_together': {('building', 'name', 'category')},
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financial.supplier', verbose_name='Προμηθευτής'),
        ),
    ]
