# Generated by Django 5.2.4 on 2025-08-05 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_current_balance_and_more'),
        ('buildings', '0007_building_current_reserve'),
        ('financial', '0006_alter_payment_options_alter_financialauditlog_action_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonExpensePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_name', models.CharField(max_length=255, verbose_name='Όνομα Περιόδου')),
                ('start_date', models.DateField(verbose_name='Ημερομηνία Έναρξης')),
                ('end_date', models.DateField(verbose_name='Ημερομηνία Λήξης')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ενεργή')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='common_expense_periods', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Περίοδος Κοινοχρήστων',
                'verbose_name_plural': 'Περίοδοι Κοινοχρήστων',
                'ordering': ['-start_date'],
                'unique_together': {('building', 'period_name')},
            },
        ),
        migrations.CreateModel(
            name='ApartmentShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικό Ποσό')),
                ('previous_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Προηγούμενο Υπόλοιπο')),
                ('total_due', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολική Οφειλή')),
                ('breakdown', models.JSONField(default=dict, verbose_name='Ανάλυση Δαπανών')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='apartments.apartment')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartment_shares', to='financial.commonexpenseperiod')),
            ],
            options={
                'verbose_name': 'Μερίδιο Διαμερίσματος',
                'verbose_name_plural': 'Μερίδια Διαμερισμάτων',
                'unique_together': {('period', 'apartment')},
            },
        ),
    ]
