# Generated by Django 5.0.14 on 2025-08-05 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0007_commonexpenseperiod_apartmentshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(choices=[('common_expense', 'Κοινόχρηστα'), ('reserve_fund', 'Ταμείο Εφεδρείας'), ('special_expense', 'Ειδική Δαπάνη'), ('advance', 'Προκαταβολή'), ('other', 'Άλλο')], default='common_expense', max_length=20, verbose_name='Τύπος Εισπράξεως'),
        ),
        migrations.AddField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Αναφοράς'),
        ),
    ]
