# Generated by Django 5.2.4 on 2025-08-06 06:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0008_payment_payment_type_payment_reference_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, verbose_name='Επικοινωνία'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Λήξης Συμβολαίου'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Έναρξης Συμβολαίου'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='emergency_contact',
            field=models.CharField(blank=True, max_length=50, verbose_name='Επείγουσα Επικοινωνία'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=50, verbose_name='Επείγουσο Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(blank=True, max_length=255, verbose_name='Όροι Πληρωμής'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Αξιολόγηση'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='reliability_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)], verbose_name='Βαθμός Αξιοπιστίας'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='response_time_hours',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Χρόνος Απόκρισης (ώρες)'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='status',
            field=models.CharField(choices=[('active', 'Ενεργός'), ('inactive', 'Ανενεργός'), ('suspended', 'Ανασταλμένος'), ('terminated', 'Τερματισμένος')], default='active', max_length=20, verbose_name='Κατάσταση'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='ΑΦΜ'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='website',
            field=models.URLField(blank=True, verbose_name='Ιστοσελίδα'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='category',
            field=models.CharField(choices=[('electricity', 'ΔΕΗ (Ηλεκτρικό Ρεύμα)'), ('water', 'ΕΥΔΑΠ (Νερό)'), ('cleaning', 'Καθαρισμός'), ('elevator', 'Ανελκυστήρας'), ('heating', 'Θέρμανση'), ('insurance', 'Ασφάλεια'), ('administrative', 'Διοικητικά'), ('repairs', 'Επισκευές'), ('maintenance', 'Συντήρηση'), ('security', 'Ασφάλεια'), ('landscaping', 'Κηπουρική'), ('technical', 'Τεχνικές Υπηρεσίες'), ('legal', 'Νομικές Υπηρεσίες'), ('accounting', 'Λογιστικές Υπηρεσίες'), ('other', 'Άλλοι')], max_length=50, verbose_name='Κατηγορία'),
        ),
    ]
