# Generated by Django 5.2.5 on 2025-08-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_apartment_general_expenses_mills'),
        ('financial', '0009_supplier_contact_person_supplier_contract_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='target_apartment',
            field=models.ForeignKey(blank=True, help_text='Συγκεκριμένο διαμέρισμα για ατομικές δαπάνες', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_expenses', to='apartments.apartment', verbose_name='Διαμέρισμα Προορισμού'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='distribution_type',
            field=models.CharField(choices=[('by_participation_mills', 'Ανά Χιλιοστά'), ('equal_share', 'Ισόποσα'), ('specific_apartments', 'Συγκεκριμένα'), ('by_meters', 'Μετρητές'), ('general_expenses', 'Γενικές Δαπάνες'), ('elevator_expenses', 'Δαπάνες Ανελκυστήρα'), ('heating_expenses', 'Δαπάνες Θέρμανσης'), ('individual_expense', 'Ατομική Δαπάνη')], max_length=50, verbose_name='Τρόπος Κατανομής'),
        ),
    ]
