# Generated by Django 5.2.4 on 2025-08-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0010_expense_target_apartment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='target_apartment',
        ),
        migrations.AlterField(
            model_name='expense',
            name='distribution_type',
            field=models.CharField(choices=[('by_participation_mills', 'Ανά Χιλιοστά'), ('equal_share', 'Ισόποσα'), ('specific_apartments', 'Συγκεκριμένα'), ('by_meters', 'Μετρητές')], max_length=50, verbose_name='Τρόπος Κατανομής'),
        ),
    ]
