# Generated by Django 5.2.5 on 2025-08-10 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0011_remove_expense_target_apartment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Όνομα Πληρωτή'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payer_type',
            field=models.CharField(choices=[('owner', 'Ιδιοκτήτης'), ('tenant', 'Ενοικιαστής'), ('other', 'Άλλος')], default='owner', max_length=20, verbose_name='Πληρωτής'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ημερομηνία'),
        ),
    ]
