# Generated by Django 5.2.5 on 2025-08-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0012_add_payer_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Όνομα Ενοίκου'),
        ),
    ]
