# Generated by Django 5.2.5 on 2025-08-16 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0013_alter_payment_payer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reserve_fund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Ποσό Αποθεματικού'),
        ),
    ]
