# Generated by Django 5.2.5 on 2025-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0014_payment_reserve_fund_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_issued',
            field=models.BooleanField(default=True, verbose_name='Εκδοθείσα'),
        ),
    ]
