# Generated by Django 5.0.14 on 2025-08-22 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0015_auto_issue_expenses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='is_issued',
        ),
    ]
