# Generated by Django 5.2.5 on 2025-08-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0016_remove_expense_is_issued'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='previous_debts_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Παλαιότερες Οφειλές'),
        ),
    ]
