# Generated by Django 5.2.5 on 2025-08-22 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0017_payment_previous_debts_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='previous_debts_amount',
        ),
        migrations.AddField(
            model_name='expense',
            name='is_issued',
            field=models.BooleanField(default=True, verbose_name='Εκδοθείσα'),
        ),
    ]
