# Generated by Django 5.2.5 on 2025-08-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0020_remove_payment_is_issued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='date',
            field=models.DateTimeField(verbose_name='Ημερομηνία'),
        ),
    ]
