# Generated by Django 5.2.5 on 2025-08-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0021_fix_transaction_date_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='previous_obligations_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Παλαιότερες Οφειλές'),
        ),
    ]
