# Generated by Django 5.2.5 on 2025-08-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0022_add_previous_obligations_amount_to_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='expense_type',
            field=models.CharField(choices=[('regular', 'Κανονική Δαπάνη'), ('management_fee', 'Διαχειριστικά Έξοδα'), ('reserve_fund', 'Εισφορά Αποθεματικού'), ('auto_generated', 'Αυτόματη Δαπάνη')], default='regular', help_text='Χρησιμοποιείται για αναγνώριση αυτόματων δαπανών', max_length=20, verbose_name='Τύπος Δαπάνης'),
        ),
    ]
