# Generated by Django 5.2.5 on 2025-08-31 16:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0023_add_expense_type_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_type', models.CharField(choices=[('cash', 'Μετρητά'), ('bank_transfer', 'Τραπεζική Μεταφορά'), ('check', 'Επιταγή'), ('card', 'Κάρτα'), ('online', 'Online Πληρωμή'), ('other', 'Άλλο')], max_length=20, verbose_name='Τύπος Απόδειξης')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ποσό')),
                ('receipt_date', models.DateField(verbose_name='Ημερομηνία Απόδειξης')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Αριθμός Απόδειξης')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='Αριθμός Αναφοράς')),
                ('payer_name', models.CharField(max_length=255, verbose_name='Όνομα Πληρωμέα')),
                ('payer_type', models.CharField(choices=[('owner', 'Ιδιοκτήτης'), ('tenant', 'Ενοικιαστής'), ('other', 'Άλλος')], max_length=20, verbose_name='Τύπος Πληρωμέα')),
                ('notes', models.TextField(blank=True, verbose_name='Σημειώσεις')),
                ('receipt_file', models.FileField(blank=True, null=True, upload_to='financial_receipts/%Y/%m/', verbose_name='Αρχείο Απόδειξης')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_financial_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='financial.payment', verbose_name='Πληρωμή')),
            ],
            options={
                'verbose_name': 'Απόδειξη Εισπράξεως',
                'verbose_name_plural': 'Αποδείξεις Εισπράξεων',
                'ordering': ['-receipt_date', '-created_at'],
            },
        ),
    ]
