# Generated by Django 5.2.6 on 2025-09-06 08:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0015_alter_building_grace_day_of_month'),
        ('financial', '0024_add_financial_receipt'),
        ('maintenance', '0008_servicereceipt_scheduled_maintenance'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Δημόσιο UID')),
                ('title', models.CharField(max_length=255, verbose_name='Τίτλος')),
                ('description', models.TextField(blank=True, verbose_name='Περιγραφή')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ποσό (€)')),
                ('service_date', models.DateField(blank=True, null=True, verbose_name='Ημερομηνία Υπηρεσίας')),
                ('category', models.CharField(choices=[('cleaning', 'Καθαρισμός Κοινοχρήστων Χώρων'), ('electricity_common', 'ΔΕΗ Κοινοχρήστων'), ('water_common', 'Νερό Κοινοχρήστων'), ('garbage_collection', 'Συλλογή Απορριμμάτων'), ('security', 'Ασφάλεια Κτιρίου'), ('concierge', 'Συνεργείο Καθαρισμού'), ('elevator_maintenance', 'Ετήσια Συντήρηση Ανελκυστήρα'), ('elevator_repair', 'Επισκευή Ανελκυστήρα'), ('elevator_inspection', 'Επιθεώρηση Ανελκυστήρα'), ('elevator_modernization', 'Αναβάθμιση Ανελκυστήρα'), ('heating_fuel', 'Πετρέλαιο Θέρμανσης'), ('heating_gas', 'Φυσικό Αέριο Θέρμανσης'), ('heating_maintenance', 'Συντήρηση Καυστήρα'), ('heating_repair', 'Επισκευή Θερμαντικών'), ('heating_inspection', 'Επιθεώρηση Θερμαντικών'), ('heating_modernization', 'Αναβάθμιση Θερμαντικών'), ('electrical_maintenance', 'Συντήρηση Ηλεκτρικών'), ('electrical_repair', 'Επισκευή Ηλεκτρικών'), ('electrical_upgrade', 'Αναβάθμιση Ηλεκτρικών'), ('lighting_common', 'Φωτισμός Κοινοχρήστων'), ('intercom_system', 'Σύστημα Εσωτερικής Επικοινωνίας'), ('plumbing_maintenance', 'Συντήρηση Υδραυλικών'), ('plumbing_repair', 'Επισκευή Υδραυλικών'), ('water_tank_cleaning', 'Καθαρισμός Δεξαμενής Νερού'), ('water_tank_maintenance', 'Συντήρηση Δεξαμενής Νερού'), ('sewage_system', 'Σύστημα Αποχέτευσης'), ('building_insurance', 'Ασφάλεια Κτιρίου'), ('building_maintenance', 'Συντήρηση Κτιρίου'), ('roof_maintenance', 'Συντήρηση Στέγης'), ('roof_repair', 'Επισκευή Στέγης'), ('facade_maintenance', 'Συντήρηση Πρόσοψης'), ('facade_repair', 'Επισκευή Πρόσοψης'), ('painting_exterior', 'Βαψίματα Εξωτερικών'), ('painting_interior', 'Βαψίματα Εσωτερικών Κοινοχρήστων'), ('garden_maintenance', 'Συντήρηση Κήπου'), ('parking_maintenance', 'Συντήρηση Χώρων Στάθμευσης'), ('entrance_maintenance', 'Συντήρηση Εισόδου'), ('emergency_repair', 'Έκτακτη Επισκευή'), ('storm_damage', 'Ζημιές από Κακοκαιρία'), ('flood_damage', 'Ζημιές από Πλημμύρα'), ('fire_damage', 'Ζημιές από Πυρκαγιά'), ('earthquake_damage', 'Ζημιές από Σεισμό'), ('vandalism_repair', 'Επισκευή Βανδαλισμών'), ('locksmith', 'Κλειδαράς'), ('glass_repair', 'Επισκευή Γυαλιών'), ('door_repair', 'Επισκευή Πόρτας'), ('window_repair', 'Επισκευή Παραθύρων'), ('balcony_repair', 'Επισκευή Μπαλκονιού'), ('staircase_repair', 'Επισκευή Σκάλας'), ('security_system', 'Σύστημα Ασφάλειας'), ('cctv_installation', 'Εγκατάσταση CCTV'), ('access_control', 'Σύστημα Ελέγχου Πρόσβασης'), ('fire_alarm', 'Σύστημα Πυρασφάλειας'), ('fire_extinguishers', 'Πυροσβεστήρες'), ('legal_fees', 'Δικαστικά Έξοδα'), ('notary_fees', 'Συμβολαιογραφικά Έξοδα'), ('surveyor_fees', 'Εκτιμητής'), ('architect_fees', 'Αρχιτέκτονας'), ('engineer_fees', 'Μηχανικός'), ('accounting_fees', 'Λογιστικά Έξοδα'), ('management_fees', 'Διοικητικά Έξοδα'), ('asbestos_removal', 'Αφαίρεση Ασβέστη'), ('lead_paint_removal', 'Αφαίρεση Μολύβδου'), ('mold_removal', 'Αφαίρεση Μούχλας'), ('pest_control', 'Εντομοκτονία'), ('tree_trimming', 'Κλάδεμα Δέντρων'), ('snow_removal', 'Καθαρισμός Χιονιού'), ('energy_upgrade', 'Ενεργειακή Αναβάθμιση'), ('insulation_work', 'Θερμομόνωση'), ('solar_panel_installation', 'Εγκατάσταση Φωτοβολταϊκών'), ('led_lighting', 'Αντικατάσταση με LED'), ('smart_systems', 'Έξυπνα Συστήματα'), ('special_contribution', 'Έκτακτη Εισφορά'), ('reserve_fund', 'Αποθεματικό Ταμείο'), ('emergency_fund', 'Ταμείο Έκτακτης Ανάγκης'), ('renovation_fund', 'Ταμείο Ανακαίνισης'), ('miscellaneous', 'Διάφορες Δαπάνες'), ('consulting_fees', 'Εργασίες Συμβούλου'), ('permits_licenses', 'Άδειες & Αποδοχές'), ('taxes_fees', 'Φόροι & Τέλη'), ('utilities_other', 'Άλλες Κοινόχρηστες Υπηρεσίες')], max_length=50, verbose_name='Κατηγορία')),
                ('distribution_type', models.CharField(choices=[('by_participation_mills', 'Ανά Χιλιοστά'), ('equal_share', 'Ισόποσα'), ('specific_apartments', 'Συγκεκριμένα'), ('by_meters', 'Μετρητές')], max_length=50, verbose_name='Τρόπος Κατανομής')),
                ('status', models.CharField(choices=[('draft', 'Πρόχειρο'), ('issued', 'Εκδόθηκε'), ('paid', 'Εξοφλήθηκε'), ('cancelled', 'Ακυρώθηκε')], default='draft', max_length=20, verbose_name='Κατάσταση')),
                ('payment_status', models.CharField(choices=[('unpaid', 'Απλήρωτο'), ('partial', 'Μερικώς Πληρωμένο'), ('paid', 'Πληρωμένο')], default='unpaid', max_length=20, verbose_name='Κατάσταση Πληρωμής')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Ακύρωσης')),
                ('cancel_reason', models.TextField(blank=True, verbose_name='Αιτιολογία Ακύρωσης')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='unified_receipts/', verbose_name='Επισύναψη')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unified_receipts', to='buildings.building')),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_unified_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Ακυρώθηκε από')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_unified_receipts', to=settings.AUTH_USER_MODEL, verbose_name='Δημιουργήθηκε από')),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_receipts', to='financial.expense')),
                ('scheduled_maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_receipts', to='maintenance.scheduledmaintenance', verbose_name='Έργο Συντήρησης')),
            ],
            options={
                'verbose_name': 'Ενιαίο Παραστατικό',
                'verbose_name_plural': 'Ενιαία Παραστατικά',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['building', 'status'], name='financial_u_buildin_f0aa91_idx'), models.Index(fields=['public_uid'], name='financial_u_public__13052a_idx')],
            },
        ),
    ]
