# Generated by Django 5.2.6 on 2025-09-06 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0025_unifiedreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='unifiedreceipt',
            name='credit_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unified_receipts_credits', to='financial.expense'),
        ),
    ]
