# Generated by Django 5.2.6 on 2025-09-06 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0027_backfill_unified_receipts'),
        ('maintenance', '0009_scheduledmaintenance_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='linked_scheduled_maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='maintenance.scheduledmaintenance', verbose_name='Σχετικό Έργο'),
        ),
    ]
