# Generated by Django 5.2.6 on 2025-09-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0028_expense_linked_scheduled_maintenance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='linked_scheduled_maintenance',
        ),
        migrations.DeleteModel(
            name='UnifiedReceipt',
        ),
    ]
