# Generated by Django 5.2.6 on 2025-09-10 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_current_balance_and_more'),
        ('financial', '0029_remove_expense_linked_scheduled_maintenance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='apartment',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='transactions', 
                to='apartments.apartment', 
                verbose_name='Διαμέρισμα'
            ),
        ),
    ]
