# Generated by Django 5.2.6 on 2025-09-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0030_add_apartment_field_to_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='add_to_calendar',
            field=models.BooleanField(default=False, help_text='Προσθήκη της δαπάνης στο ημερολόγιο για υπενθύμιση', verbose_name='Προσθήκη στο ημερολόγιο'),
        ),
        migrations.AddField(
            model_name='expense',
            name='due_date',
            field=models.DateField(blank=True, help_text='Ημερομηνία πληρωμής της δαπάνης', null=True, verbose_name='Πληρωτέο ως'),
        ),
    ]
