# Generated by Django 5.2.6 on 2025-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0031_add_due_date_and_calendar_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='add_to_calendar',
            field=models.BooleanField(default=True, help_text='Προσθήκη της δαπάνης στο ημερολόγιο για υπενθύμιση', verbose_name='Προσθήκη στο ημερολόγιο'),
        ),
    ]
