# Generated by Django 5.2.6 on 2025-09-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0034_update_existing_expenses_calendar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meterreading',
            name='meter_type',
            field=models.CharField(choices=[('water', 'Νερό'), ('electricity', 'Ηλεκτρικό'), ('heating_hours', 'Θέρμανση (Ώρες)'), ('heating_energy', 'Θέρμανση (kWh/MWh)')], default='water', max_length=20, verbose_name='Τύπος Μετρητή'),
        ),
        migrations.AlterField(
            model_name='meterreading',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ένδειξη'),
        ),
    ]
