# Generated by Django 5.2.6 on 2025-09-14 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0017_add_heating_system_fields'),
        ('financial', '0035_update_meter_reading_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Έτος')),
                ('month', models.PositiveIntegerField(verbose_name='Μήνας')),
                ('total_expenses', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικές Δαπάνες')),
                ('total_payments', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Συνολικές Εισπράξεις')),
                ('previous_obligations', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Παλιές Οφειλές')),
                ('carry_forward', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Προς Μεταφορά')),
                ('reserve_fund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Αποθεματικό')),
                ('management_fees', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Έξοδα Διαχείρισης')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Κλειστός Μήνας')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ημερομηνία Κλεισίματος')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_balances', to='buildings.building')),
            ],
            options={
                'verbose_name': 'Μηνιαίο Υπόλοιπο',
                'verbose_name_plural': 'Μηνιαία Υπόλοιπα',
                'ordering': ['-year', '-month'],
                'unique_together': {('building', 'year', 'month')},
            },
        ),
    ]
