# Generated by Django 5.2.6 on 2025-09-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0036_monthlybalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalance',
            name='scheduled_maintenance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Προγραμματισμένα Έργα'),
        ),
    ]
