# Generated by Django 5.2.6 on 2025-09-17 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0037_add_scheduled_maintenance_amount_to_monthly_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlybalance',
            name='scheduled_maintenance_amount',
        ),
    ]
