# Generated by Django 5.2.6 on 2025-09-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0038_remove_monthlybalance_scheduled_maintenance_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalance',
            name='annual_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Υπόλοιπο που μεταφέρεται στο νέο έτος (μόνο για Δεκέμβριο)', max_digits=10, verbose_name='Ετήσια Μεταφορά'),
        ),
        migrations.AddField(
            model_name='monthlybalance',
            name='balance_year',
            field=models.PositiveIntegerField(blank=True, help_text='Έτος που ανήκει το υπόλοιπο (για ετήσια μεταφορά)', null=True, verbose_name='Έτος Υπολοίπου'),
        ),
    ]
