# Generated by Django 5.2.6 on 2025-09-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0039_add_annual_balance_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalance',
            name='main_balance_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Μεταφορά κύριου υπολοίπου (κανονικές δαπάνες + παλαιότερες οφειλές)', max_digits=10, verbose_name='Κύριο Υπόλοιπο Μεταφορά'),
        ),
        migrations.AddField(
            model_name='monthlybalance',
            name='management_balance_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Μεταφορά υπολοίπου διαχείρισης (έξοδα διαχείρισης)', max_digits=10, verbose_name='Διαχείριση Υπόλοιπο Μεταφορά'),
        ),
        migrations.AddField(
            model_name='monthlybalance',
            name='reserve_balance_carry_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Μεταφορά αποθεματικού υπολοίπου (μόνο για αποταμίευση)', max_digits=10, verbose_name='Αποθεματικό Υπόλοιπο Μεταφορά'),
        ),
    ]
