# Generated by Django 5.2.7 on 2025-10-03 00:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0021_alter_building_reserve_fund_priority'),
        ('financial', '0040_add_hybrid_balance_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringExpenseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(choices=[('management_fee', 'Δαπάνες Διαχείρισης'), ('reserve_fund', 'Αποθεματικό Ταμείο')], max_length=20, verbose_name='Τύπος Δαπάνης')),
                ('effective_from', models.DateField(help_text='Ημερομηνία έναρξης ισχύος αυτής της ρύθμισης', verbose_name='Ισχύει από')),
                ('effective_until', models.DateField(blank=True, help_text='Ημερομηνία λήξης (null = ισχύει μέχρι σήμερα)', null=True, verbose_name='Ισχύει έως')),
                ('calculation_method', models.CharField(choices=[('fixed_per_apartment', 'Σταθερό Ποσό ανά Διαμέρισμα'), ('percentage_of_expenses', 'Ποσοστό επί Δαπανών'), ('fixed_total', 'Σταθερό Συνολικό Ποσό')], default='fixed_per_apartment', max_length=30, verbose_name='Μέθοδος Υπολογισμού')),
                ('amount_per_apartment', models.DecimalField(blank=True, decimal_places=2, help_text='Χρησιμοποιείται για fixed_per_apartment', max_digits=10, null=True, verbose_name='Ποσό ανά Διαμέρισμα (€)')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Χρησιμοποιείται για percentage_of_expenses (π.χ. 5.00 για 5%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Ποσοστό (%)')),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Χρησιμοποιείται για fixed_total', max_digits=10, null=True, verbose_name='Συνολικό Ποσό (€)')),
                ('distribution_type', models.CharField(choices=[('by_participation_mills', 'Ανά Χιλιοστά'), ('equal_share', 'Ισόποσα'), ('specific_apartments', 'Συγκεκριμένα'), ('by_meters', 'Μετρητές')], default='equal_share', max_length=50, verbose_name='Τρόπος Κατανομής')),
                ('is_active', models.BooleanField(default=True, help_text='Αν False, δεν θα δημιουργούνται νέες δαπάνες', verbose_name='Ενεργό')),
                ('notes', models.TextField(blank=True, help_text="π.χ. 'Αλλαγή λόγω νέου πακέτου διαχείρισης'", verbose_name='Σημειώσεις')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_expense_configs', to='buildings.building', verbose_name='Κτίριο')),
            ],
            options={
                'verbose_name': 'Ρύθμιση Επαναλαμβανόμενης Δαπάνης',
                'verbose_name_plural': 'Ρυθμίσεις Επαναλαμβανόμενων Δαπανών',
                'ordering': ['building', 'expense_type', '-effective_from'],
                'indexes': [models.Index(fields=['building', 'expense_type', 'effective_from'], name='financial_r_buildin_286db3_idx'), models.Index(fields=['building', 'expense_type', 'is_active'], name='financial_r_buildin_6b44f8_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(models.Q(('calculation_method', 'fixed_per_apartment'), ('amount_per_apartment__isnull', False)), models.Q(('calculation_method', 'percentage_of_expenses'), ('percentage__isnull', False)), models.Q(('calculation_method', 'fixed_total'), ('total_amount__isnull', False)), _connector='OR')), name='recurring_expense_valid_amount')],
            },
        ),
    ]
