# Generated by Django 5.2.7 on 2025-10-09 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0042_add_project_and_audit_trail_to_expense'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payer_responsibility',
            field=models.CharField(choices=[('owner', 'Ιδιοκτήτης'), ('tenant', 'Ενοικιαστής'), ('shared', 'Κοινή Ευθύνη')], default='tenant', help_text='Καθορίζει ποιος πληρώνει: Ιδιοκτήτης (έργα, αποθεματικό) ή Ενοικιαστής (τακτικά κοινόχρηστα)', max_length=20, verbose_name='Ευθύνη Πληρωμής'),
        ),
    ]
