# Generated by Django 5.2.7 on 2025-10-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0043_expense_payer_responsibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payer_responsibility',
            field=models.CharField(choices=[('owner', 'Ιδιοκτήτης'), ('resident', 'Ένοικος'), ('shared', 'Κοινή Ευθύνη')], default='resident', help_text='Καθορίζει ποιος πληρώνει: Ιδιοκτήτης (έργα, αποθεματικό) ή Ένοικος (τακτικά κοινόχρηστα)', max_length=20, verbose_name='Ευθύνη Πληρωμής'),
        ),
    ]
