# Generated by Django on 2025-10-10

from django.db import migrations
from decimal import Decimal
from datetime import date


def create_retroactive_monthly_charges(apps, schema_editor):
    """
    Data migration: Create monthly charges for existing buildings
    
    This runs ONCE to create Transaction-based monthly charges for buildings
    that already have financial_system_start_date and management_fee_per_apartment set.
    
    After this migration, the signal will handle new buildings automatically.
    """
    Building = apps.get_model('buildings', 'Building')
    Transaction = apps.get_model('financial', 'Transaction')
    Apartment = apps.get_model('apartments', 'Apartment')
    
    from django.utils import timezone
    from datetime import datetime
    
    print("\n" + "=" * 60)
    print("DATA MIGRATION: Creating retroactive monthly charges")
    print("=" * 60)
    
    # Find all buildings with management fees configured
    buildings = Building.objects.filter(
        financial_system_start_date__isnull=False,
        management_fee_per_apartment__gt=0
    )
    
    print(f"\nFound {buildings.count()} buildings with management fees configured")
    
    total_created = 0
    
    for building in buildings:
        print(f"\n📦 Processing: {building.name}")
        print(f"   Start date: {building.financial_system_start_date}")
        print(f"   Fee/apartment: €{building.management_fee_per_apartment}")
        
        # Check if charges already exist
        existing = Transaction.objects.filter(
            building=building,
            type='management_fee_charge'
        ).exists()
        
        if existing:
            print(f"   ⏭️ Skipping - charges already exist")
            continue
        
        # Get apartments for this building
        apartments = Apartment.objects.filter(building=building)
        apartment_count = apartments.count()
        
        if apartment_count == 0:
            print(f"   ⏭️ Skipping - no apartments")
            continue
        
        # Create charges from start_date to current month
        start_month = building.financial_system_start_date
        today = date.today()
        current_month = date(today.year, today.month, 1)
        
        # Loop through each month
        charge_month = date(start_month.year, start_month.month, 1)
        months_created = 0
        transactions_created = 0
        
        while charge_month <= current_month:
            # Create transaction for each apartment
            for apartment in apartments:
                Transaction.objects.create(
                    apartment=apartment,
                    building=building,
                    type='management_fee_charge',
                    amount=building.management_fee_per_apartment,
                    date=timezone.make_aware(datetime.combine(charge_month, datetime.min.time())),
                    description=f"Δαπάνες Διαχείρισης {charge_month.strftime('%B %Y')}",
                    balance_before=apartment.current_balance or Decimal('0.00'),
                    balance_after=(apartment.current_balance or Decimal('0.00')) + building.management_fee_per_apartment
                )
                
                # Update apartment balance
                apartment.current_balance = (apartment.current_balance or Decimal('0.00')) + building.management_fee_per_apartment
                apartment.save(update_fields=['current_balance'])
                
                transactions_created += 1
            
            months_created += 1
            
            # Next month
            if charge_month.month == 12:
                charge_month = date(charge_month.year + 1, 1, 1)
            else:
                charge_month = date(charge_month.year, charge_month.month + 1, 1)
        
        print(f"   ✅ Created {months_created} months × {apartment_count} apartments = {transactions_created} transactions")
        total_created += transactions_created
    
    print("\n" + "=" * 60)
    print(f"✅ MIGRATION COMPLETE: {total_created} transactions created")
    print("=" * 60 + "\n")


def reverse_migration(apps, schema_editor):
    """
    Reverse migration: Delete auto-created monthly charges
    
    ⚠️ WARNING: This will delete all management_fee_charge transactions!
    Use with caution.
    """
    Transaction = apps.get_model('financial', 'Transaction')
    
    deleted_count = Transaction.objects.filter(
        type='management_fee_charge'
    ).delete()[0]
    
    print(f"🗑️ Deleted {deleted_count} management fee transactions")


class Migration(migrations.Migration):
    dependencies = [
        ('financial', '0044_alter_expense_payer_responsibility'),
        ('buildings', '0001_initial'),  # Ensure Building model exists
        ('apartments', '0001_initial'),  # Ensure Apartment model exists
    ]

    operations = [
        migrations.RunPython(
            create_retroactive_monthly_charges,
            reverse_migration
        ),
    ]

