# Generated by Django 5.2.7 on 2025-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0045_create_retroactive_monthly_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlybalance',
            name='scheduled_maintenance_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Δόσεις προγραμματισμένων έργων για το μήνα', max_digits=10, verbose_name='Προγραμματισμένα Έργα'),
        ),
    ]
