# Generated by Django 5.2.7 on 2025-10-10 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0046_add_scheduled_maintenance_to_monthly_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='balance_after',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Υπόλοιπο Μετά'),
        ),
    ]
