# Generated by Django 5.2.8 on 2025-11-13 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0049_alter_expense_category'),
    ]

    operations = [
    ]
