# backend/tenants/views.py

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status
from rest_framework.permissions import AllowAny
from django.core.signing import TimestampSigner, SignatureExpired, BadSignature
from rest_framework_simplejwt.tokens import RefreshToken
from users.models import CustomUser
from .models import Client
import logging

logger = logging.getLogger(__name__)


class AcceptTenantInviteView(APIView):
    """
    Accept tenant workspace access via secure token (Stripe webhook workflow).
    This is DIFFERENT from resident/tenant invitations in the users module.
    
    This endpoint handles workspace access after Stripe payment completion.
    The token is generated by EmailService.send_tenant_welcome_email after webhook provisioning.
    
    For resident/tenant invitations, see: /api/users/invitations/accept/
    """
    permission_classes = [AllowAny]
    
    def post(self, request):
        token = request.data.get('token')
        
        logger.info(f"[TENANT_WORKSPACE_ACCESS] Received workspace access request with token: {token[:20] if token else 'None'}...")
        
        if not token:
            logger.warning(f"[TENANT_WORKSPACE_ACCESS] Token missing in request")
            return Response({
                'error': 'Token is required'
            }, status=status.HTTP_400_BAD_REQUEST)
        
        try:
            # Verify token (24h expiry)
            logger.debug(f"[TENANT_WORKSPACE_ACCESS] Validating workspace access token signature and expiry")
            signer = TimestampSigner()
            try:
                unsigned_data = signer.unsign(token, max_age=86400)  # 24 hours
                logger.debug(f"[TENANT_WORKSPACE_ACCESS] Token signature valid, unsigned data: {unsigned_data[:50]}...")
            except SignatureExpired as e:
                logger.warning(f"[TENANT_WORKSPACE_ACCESS] Workspace access token expired: {e}")
                return Response({
                    'error': 'Token has expired. Please login normally.'
                }, status=status.HTTP_400_BAD_REQUEST)
            except BadSignature as e:
                logger.warning(f"[TENANT_WORKSPACE_ACCESS] Invalid workspace access token signature: {e}")
                return Response({
                    'error': 'Invalid token'
                }, status=status.HTTP_400_BAD_REQUEST)
            
            # Parse token data: "user_id:tenant_id:domain"
            try:
                user_id, tenant_id, domain = unsigned_data.split(':')
                logger.debug(f"[TENANT_WORKSPACE_ACCESS] Parsed workspace access token - user_id: {user_id}, tenant_id: {tenant_id}, domain: {domain}")
            except ValueError as e:
                logger.error(f"[TENANT_WORKSPACE_ACCESS] Failed to parse workspace access token data: {e}, data: {unsigned_data}")
                return Response({
                    'error': 'Invalid token format'
                }, status=status.HTTP_400_BAD_REQUEST)
            
            # Validate user and tenant
            try:
                logger.debug(f"[TENANT_WORKSPACE_ACCESS] Querying user with id: {user_id}")
                user = CustomUser.objects.get(id=user_id)
                logger.info(f"[TENANT_WORKSPACE_ACCESS] Found user: {user.email} (ID: {user.id})")
            except CustomUser.DoesNotExist as e:
                logger.error(f"[TENANT_WORKSPACE_ACCESS] User not found with id: {user_id}, error: {e}")
                logger.error(f"[TENANT_WORKSPACE_ACCESS] Query executed: CustomUser.objects.get(id={user_id})")
                return Response({
                    'error': 'User not found'
                }, status=status.HTTP_404_NOT_FOUND)
            except Exception as e:
                logger.error(f"[TENANT_WORKSPACE_ACCESS] Unexpected error querying user {user_id}: {e}", exc_info=True)
                return Response({
                    'error': 'Failed to validate user'
                }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
            
            try:
                logger.debug(f"[TENANT_WORKSPACE_ACCESS] Querying tenant with id: {tenant_id}")
                tenant = Client.objects.get(id=tenant_id)
                logger.info(f"[TENANT_WORKSPACE_ACCESS] Found tenant: {tenant.name} (ID: {tenant.id}, schema: {tenant.schema_name})")
            except Client.DoesNotExist as e:
                logger.error(f"[TENANT_WORKSPACE_ACCESS] Tenant not found with id: {tenant_id}, error: {e}")
                logger.error(f"[TENANT_WORKSPACE_ACCESS] Query executed: Client.objects.get(id={tenant_id})")
                return Response({
                    'error': 'Tenant not found'
                }, status=status.HTTP_404_NOT_FOUND)
            except Exception as e:
                logger.error(f"[TENANT_WORKSPACE_ACCESS] Unexpected error querying tenant {tenant_id}: {e}", exc_info=True)
                return Response({
                    'error': 'Failed to validate tenant'
                }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)
            
            # Verify user is linked to this tenant
            logger.debug(f"[TENANT_WORKSPACE_ACCESS] Verifying user.tenant_id ({user.tenant_id}) matches tenant_id ({tenant_id})")
            if user.tenant_id != int(tenant_id):
                logger.warning(f"[TENANT_WORKSPACE_ACCESS] Tenant mismatch - user.tenant_id: {user.tenant_id}, token tenant_id: {tenant_id}")
                return Response({
                    'error': 'Invalid tenant access'
                }, status=status.HTTP_403_FORBIDDEN)
            
            logger.info(f"[TENANT_WORKSPACE_ACCESS] Tenant verification passed - user {user.id} linked to tenant {tenant.id}")
            
            # Generate JWT tokens
            logger.debug(f"[TENANT_WORKSPACE_ACCESS] Generating JWT tokens for user {user.id}")
            refresh = RefreshToken.for_user(user)
            access_token = str(refresh.access_token)
            logger.info(f"[TENANT_WORKSPACE_ACCESS] Generated tokens for user {user.email}, tenant: {tenant.schema_name}")
            
            logger.info(f"[TENANT_WORKSPACE_ACCESS] ✅ Successfully granted workspace access for user {user.id}, tenant {tenant.id} (schema: {tenant.schema_name})")
            
            # Build tenant URL for redirect
            from django.conf import settings
            import os
            
            # Determine environment based on settings and environment variables
            is_production = not settings.DEBUG or os.getenv('RAILWAY_ENVIRONMENT', '').lower() == 'production'
            
            # Check if we're on Vercel (shared domain, no subdomains)
            frontend_url = settings.FRONTEND_URL
            is_vercel = 'vercel.app' in frontend_url.lower()
            
            if is_vercel:
                # Vercel: Use query parameter approach (no subdomains)
                # Keep user on same domain, use query param for tenant switching
                tenant_url = f"{frontend_url}/dashboard?tenant={tenant.schema_name}"
                logger.info(f"[TENANT_WORKSPACE_ACCESS] Vercel deployment detected, using query parameter approach")
            elif is_production:
                # Production with subdomains: https://schema_name.newconcierge.app
                frontend_base = frontend_url.replace('https://', '').replace('http://', '').split('/')[0]
                # Extract base domain (e.g., 'newconcierge.app' from 'https://newconcierge.app')
                if '.' in frontend_base:
                    base_domain = frontend_base
                else:
                    base_domain = 'newconcierge.app'  # Fallback
                tenant_url = f"https://{tenant.schema_name}.{base_domain}/dashboard"
            else:
                # Development: http://schema_name.localhost:3000/dashboard
                tenant_url = f"http://{tenant.schema_name}.localhost:3000/dashboard"
            
            logger.info(f"[TENANT_WORKSPACE_ACCESS] Generated tenant_url: {tenant_url}")
            
            return Response({
                'status': 'success',
                'access': access_token,
                'refresh': str(refresh),
                'tenant': {
                    'schema_name': tenant.schema_name,
                    'name': tenant.name,
                    'domain': domain,
                    'tenant_url': tenant_url  # Full URL for redirect
                },
                'user': {
                    'email': user.email,
                    'first_name': user.first_name,
                    'last_name': user.last_name,
                    'role': user.role
                }
            })
            
        except Exception as e:
            logger.error(f"[TENANT_WORKSPACE_ACCESS] ❌ Unexpected error processing workspace access: {e}", exc_info=True)
            return Response({
                'error': 'Failed to process workspace access request'
            }, status=status.HTTP_500_INTERNAL_SERVER_ERROR)